--------------------------------------------------------
--  File created - Friday-October-18-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BR_MASTER
--------------------------------------------------------

  CREATE TABLE "DATA_DOCKIN"."BR_MASTER" 
   (	"BRCODE" NUMBER(10,0), 
	"BRNAME" VARCHAR2(30 BYTE), 
	"LOCATION" VARCHAR2(30 BYTE), 
	"REV_STATE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_DOCKIN_TBS" ;
REM INSERTING into DATA_DOCKIN.BR_MASTER
SET DEFINE OFF;
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (107,'LUDHIANA','Ludhiana',null);
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (108,'LUCKNOW','Lucknow',null);
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (106,'PIPARIYA (106)','Pipariya',null);
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (109,'KADODARA (109)','Surat',null);
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (110,'HINJILICUT (110)','Orissa',null);
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (112,'GADARWARA (112)','Madhya Pradesh',null);
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (113,'DUNGURIPALI (113)','Orissa',null);
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (115,'SONGADH (115)','Surat',null);
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (117,'MANDIDEEP (117)','Madhya Pradesh',null);
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (118,'NANA RASANA (118)','Gujarat',null);
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (111,'JAIPUR (111)','Jaipur',null);
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (114,'VASAD (114)','Ahmedabad',null);
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (116,'ATTABIRA (116)','Orissa',null);
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (119,'NOIDA (119)','Noida',null);
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (121,'JAGANNATHPUR (121)','Orissa',null);
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (120,'VIJAYAWADA (120)',null,null);
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (122,'AKIVIDU (122)',null,null);
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (874,'VIJAYWADA (874)','Hyderabad','Andhra Pradesh');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (900,'MUMBAI - NPC (900)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (100,'VADODARA (100)','Vadodara','Gujarat');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (1,'MUMBAI MAIN OFFICE  (001)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (2,'KALBADEVI  (002)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (3,'DHARAVI (003)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (4,'ANDHERI - WEST (004)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (5,'BANDRA (005)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (6,'BYCULLA (006)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (7,'DAHISAR (007)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (8,'GOREGAON  (008)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (9,'HASANABAD (009)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (10,'JOGESHWARI  BRANCH (010)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (11,'KURLA (011)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (12,'MUMBRA (012)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (13,'NESBIT ROAD (013)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (14,'PUNE (014)','Pune','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (15,'WARANGAL (015)','Hyderabad','Andhra Pradesh');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (16,'TREASURY (016)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (17,'VERSOVA  (017)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (18,'THANE (018)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (19,'MOHAMEDALI ROAD (019)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (20,'CENTRAL ADM. OFFFICE (020)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (22,'NANDED (022)','Pune','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (23,'NARIMAN POINT (023)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (24,'MAHIM (024)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (25,'MALAD  (025)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (26,'SANTA CRUZ (026)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (27,'HYDERABAD (027)','Hyderabad','Andhra Pradesh');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (28,'RELIEF ROAD  (028)','Ahmedabad','Gujarat');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (29,'KAUSA (029)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (30,'VASHI (030)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (31,'LOKHANDWALA  (031)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (32,'AURANAGABAD (032)','Aurangabad','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (33,'SURAT (033)','Surat','Gujarat');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (34,'VAPI (034)','Vapi','Gujarat');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (35,'SIDHPUR (035)','Sidhpur','Gujarat');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (36,'C.G.ROAD (036)','Ahmedabad','Gujarat');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (38,'BANGALORE (038)','Bangalore','Karnataka');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (39,'MIRA ROAD (039)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (40,'RAJKOT (040)','Rajkot','Gujarat');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (41,'GANDHINAGAR (041)','Ahmedabad','Gujarat');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (42,'BHUJ (042)','Bhuj','Gujarat');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (43,'NARIMAN POINT (043)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (44,'DAMAN (044)','Ahmedabad','Daman');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (45,'ANKLESHWAR (045)','Ankleshwar','Gujarat');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (46,'NEW DELHI (046)','Delhi','New Delhi');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (47,'SILVASSA (047)','Ahmedabad','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (48,'J.M.ROAD - PUNE (048)','Pune','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (49,'MADHAPUR (049)','Hyderabad','Andhra Pradesh');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (50,'HABSIGUDA (050)','Hyderabad','Andhra Pradesh');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (51,'A.S.RAO NAGAR (051)','Hyderabad','Andhra Pradesh');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (52,'VIRAR (052)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (53,'SABOO SIDDIQUE (053)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (54,'VASCO-DA-GAMA (054)','Goa','Goa');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (55,'PANAJI (055)','Goa','Goa');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (56,'MARGAO (056)','Goa','Goa');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (57,'MAPUSA (057)','Goa','Goa');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (58,'SECUNDRABAD (058)','Hyderabad','Andhra Pradesh');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (59,'NAKKALGUTTA (059)','Hyderabad','Andhra Pradesh');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (60,'CHENNAI (060)','Chennai','Tamilnadu');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (61,'ANDHERI EAST (061)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (62,'JHARSA (062)','Delhi','Haryana');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (69,'PREET VIHAR (069)','Delhi','New Delhi');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (70,'GREATER KAILASH (070)','Delhi','New Delhi');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (71,'RAJAJI NAGAR - BLR (071)','Bangalore','Karnataka');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (72,'S.R.NAGAR (072)','Hyderabad','Andhra Pradesh');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (76,'GADDIANNARAMM (076)','Hyderabad','Andhra Pradesh');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (79,'SHAKESPEAR SARANI (079)','Kolkata','West Bengal');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (80,'VEJALPUR (080)','Ahmedabad','Gujarat');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (81,'SATARA ROAD, PUNE (081)','Pune','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (82,'JAYA NAGAR (082)','Bangalore','Karnataka');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (83,'GHATLODIA (083)','Ahmedabad','Gujarat');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (84,'KAMOTHE (084)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (85,'CHANDANAGAR  (085)','Hyderabad','Andhra Pradesh');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (86,'MUCHHALA POLYTECHNIC (086)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (87,'GARIAHAT (087)','Kolkata','West Bengal');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (88,'DEDIAPADA (088)','Dediapada','Gujarat');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (89,'BRABOURNE ROAD-KOLKOTA (089)','Kolkata','West Bengal');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (90,'JAKKASANDRA (090)','Bangalore','Karnataka');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (91,'CHANDNI CHOWK (091)','Delhi','New Delhi');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (92,'KAPASHERA (092)','Delhi','New Delhi');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (93,'KONDLI (093)','Delhi','New Delhi');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (94,'VASAI (094)','Mumbai','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (95,'NASHIK (095)','Nashik','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (96,'JODHPUR (096)','Jodhpur','Rajasthan');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (97,'CHENNAI BROADWAY (097)','Chennai','Tamilnadu');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (98,'KONDHAVE KHURD (098)','Pune','Maharashtra');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (870,'CHANDIGARH (870)','Chandigarh','New Delhi');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (871,'JAIPUR (871)','Jaipur','New Delhi');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (872,'COIMBATORE (872)','Coimbatore','Tamilnadu');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (873,'SALEM (873)','Salem','Tamilnadu');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (105,'KOCHI (105)','Bangalore','Karnataka');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (101,'MANDVI (101)','Mandvi','Gujarat');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (102,'NETRANG (102)','Netrang','Gujarat');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (103,'BARGARH (103)','Bargarh','Orissa');
Insert into DATA_DOCKIN.BR_MASTER (BRCODE,BRNAME,LOCATION,REV_STATE) values (104,'ITARSI (104)','Itarsi','Madhya Pradesh');
