--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Procedure HP_INS_HREP_REGULATORY_EQUITY
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE HP_INS_HREP_REGULATORY_EQUITY AS 
BEGIN
INSERT INTO HREP_REGULATORY_EQUITY(SEBI_STAMPING	,
MCR_ASSET_TYPE	,
MCR_SUB_ASSET_TYPE	,
SECTOR_ALT	,
SCHEMECODE	,
SEBISCHEMECLASS	,
SEBI_SCHEME_CATEGORYY	,
IND1	,
QUANTIS_DATE	,
INDUSTRY_NAME	,
SECURITY	,
ISIN_CODE	,
SECURITY_NAME	,
ASSET_NAME	,
SECTOR_CATEGORY	,
ISSUER	,
ISSUER_NAME	,
COUPON_RATE	,
PORTFOLIO	,
FACE_VALUE	,
TRANS_DATE	,
ASSET_CLASS	,
QTY_LOGICAL	,
ACQU_COST_TCY	,
NET_CURRENT_ASSETS	,
NET_ASSET_VALUE	,
MARKET_VALUE	,
MATURITY_DATE	,
PORTFOLIO_CATEGORY_NAME	,
FF_VC1	,
FRONTEND_RATING	,
MATURITY_DAYS	,
REGULATORY_STAMPING	
)
SELECT SEBI_STAMPING	,
MCR_ASSET_TYPE	,
MCR_SUB_ASSET_TYPE	,
SECTOR_ALT	,
SCHEMECODE	,
SEBISCHEMECLASS	,
SEBI_SCHEME_CATEGORYY	,
IND1	,
QUANTIS_DATE	,
INDUSTRY_NAME	,
SECURITY	,
ISIN_CODE	,
SECURITY_NAME	,
ASSET_NAME	,
SECTOR_CATEGORY	,
ISSUER	,
ISSUER_NAME	,
COUPON_RATE	,
PORTFOLIO	,
FACE_VALUE	,
TRANS_DATE	,
ASSET_CLASS	,
QTY_LOGICAL	,
ACQU_COST_TCY	,
NET_CURRENT_ASSETS	,
NET_ASSET_VALUE	,
MARKET_VALUE	,
MATURITY_DATE	,
PORTFOLIO_CATEGORY_NAME	,
FF_VC1	,
FRONTEND_RATING	,
MATURITY_DAYS	,
REGULATORY_STAMPING	
FROM HV_REGULATORY_MF_EQUITY;
END;

/
