--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Procedure HPROC_MKTPRICE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE HPROC_MKTPRICE 
AS
  V_COUNT       NUMBER;
  EX_UPLOAD     EXCEPTION;
  FILE_NOTFOUND EXCEPTION;
  V_CNT         NUMBER;
  V_EXISTS      BOOLEAN;
  V_LENGTH      NUMBER;
  V_BLOCKSIZE   NUMBER;
  V_AUDIT       NUMBER;
BEGIN
  UTL_FILE.FGETATTR('HG_HAMC_PUMP_DIR', 'MKTPRICE.csv', V_EXISTS, V_LENGTH, V_BLOCKSIZE);
  IF V_EXISTS THEN
    /*
    NEED TO CHECK THE DATA SO THAT THE DATA DOES NOT GET INSERTED INTO THE TEMPOPARY TABLE
    MULTIPLE TIMES EVEN IF THE PROCEDURE IS RUNNED MULTIPLE TIMES
    */
    SELECT COUNT(*)
    INTO V_COUNT
    FROM HPER_MKTPRICE HPER_MKTPRICE,
      HTMP_MKTPRICE_EXT HTMP_MKTPRICE_EXT
    WHERE HPER_MKTPRICE.MKTPRICE_DATE = HTMP_MKTPRICE_EXT.MKTPRICE_DATE
    AND HPER_MKTPRICE.INSTRUMENT      = HTMP_MKTPRICE_EXT.INSTRUMENT
    AND HPER_MKTPRICE.UNDERLYING_CODE = HTMP_MKTPRICE_EXT.UNDERLYING_CODE
    AND HPER_MKTPRICE.EXPIRY_DATE     = HTMP_MKTPRICE_EXT.EXPIRY_DATE
    AND HPER_MKTPRICE.MKTPRICE        = HTMP_MKTPRICE_EXT.MKTPRICE
    AND HPER_MKTPRICE.UPD_DT          = SYSDATE;
    IF V_COUNT                        < 1 THEN
      /*
      INSERTING THE DATA FROM THE TEMPORARY TABLE INTO THE PERMANENT TABLE
      */
      INSERT
      INTO HPER_MKTPRICE
        (
          MKTPRICE_DATE,
          INSTRUMENT,
          UNDERLYING_CODE,
          EXPIRY_DATE,
          MKTPRICE,
          UPD_DT,
          VALUE_DATE,
          STATUS
        )
      SELECT HTMP_MKTPRICE_EXT.MKTPRICE_DATE,
        HTMP_MKTPRICE_EXT.INSTRUMENT,
        HTMP_MKTPRICE_EXT.UNDERLYING_CODE,
        HTMP_MKTPRICE_EXT.EXPIRY_DATE,
        HTMP_MKTPRICE_EXT.MKTPRICE,
        SYSDATE,
        SYSDATE,
        'A'
      FROM HTMP_MKTPRICE_EXT;
      COMMIT;
    ELSE
      /*
      NEED TO THROW AN EXCEPTION IF THE RECORD ALREADY EXISTS.
      */
      RAISE EX_UPLOAD;
    END IF;
    /*
    NEED TO CHECK THE DATA SO THAT THE DATA DOES NOT GET INSERTED INTO THE PERMENANT TABLE
    MULTIPLE TIMES EVEN IF THE PROCEDURE IS RUNNED MULTIPLE TIMES
    */
    SELECT COUNT(*)
    INTO V_CNT
    FROM HPER_MKTPRICE HPER_MKTPRICE,
      HUPD_MKTPRICE_UPLOAD HUPD_MKTPRICE_UPLOAD
    WHERE HUPD_MKTPRICE_UPLOAD.MKTPRICE_DATE = HPER_MKTPRICE.MKTPRICE_DATE
    AND HUPD_MKTPRICE_UPLOAD.INSTRUMENT      = HPER_MKTPRICE.INSTRUMENT
    AND HUPD_MKTPRICE_UPLOAD.UNDERLYING_CODE = HPER_MKTPRICE.UNDERLYING_CODE
    AND HUPD_MKTPRICE_UPLOAD.EXPIRY_DATE     = HPER_MKTPRICE.EXPIRY_DATE
    AND HUPD_MKTPRICE_UPLOAD.MKTPRICE        = HPER_MKTPRICE.MKTPRICE;
    IF V_CNT                                 < 1 THEN
      /*
      INSERTING THE DATA FROM PERMANENT TABLE TO HI TABLES SINCE WE NEED TO TRUNCATE THE PERMANENT TABLE
      REGULARLY AND ALSO WE WILL PICK ONLY SELECTED COLUMNS IN THE HI TABLE .
      */
      INSERT
      INTO HUPD_MKTPRICE_UPLOAD
        (
          MKTPRICE_ID,
          MKTPRICE_DATE,
          INSTRUMENT,
          UNDERLYING_CODE,
          EXPIRY_DATE,
          MKTPRICE,
          UPLOAD_DATE
        )
      SELECT MKTPRICE_SEQ.NEXTVAL,
        MKTPRICE_DATE,
        INSTRUMENT,
        UNDERLYING_CODE,
        EXPIRY_DATE,
        MKTPRICE,
        SYSDATE
      FROM HPER_MKTPRICE;
      COMMIT;
    ELSE
      RAISE EX_UPLOAD;
    END IF;
    /*
    INSERTING THE DATA IN THE AUDITLOG TABLE FOR FURTHER REFERENCE.
    */
    SELECT COUNT(*)
    INTO V_AUDIT
    FROM HI_AUDITLOG
    WHERE PROCEDURE_NAME = 'HPROC_MKTPRICE'
    AND TABLE_NAME       = 'HUPD_MKTPRICE_UPLOAD'
    AND AUDIT_DT         = SYSDATE
    AND PROCEDURE_FLAG   = 'Y';
    IF V_AUDIT           < 1 THEN
      INSERT
      INTO HI_AUDITLOG
        (
          AUDITLOG_ID,
          PROCEDURE_NAME,
          TABLE_NAME,
          REPO_NAME,
          PROCEDURE_FLAG,
          TABLE_FLAG,
          REPO_FLAG,
          AUDIT_DT
        )
      SELECT AUDIT_SEQ.NEXTVAL ,
        'HPROC_MKTPRICE'       AS PROC_NAME,
        'HUPD_MKTPRICE_UPLOAD' AS TABLE_NAME,
        NULL                   AS REP0_NAME,
        'Y'                    AS PROCEDURE_FLAG,
        'Y'                    AS TABLE_FLAG,
        NULL                   AS REPO_FLAG,
        SYSDATE                AS AUDIT_DT
      FROM DUAL;
      COMMIT;
    ELSE
      RAISE EX_UPLOAD;
    END IF;
    /*
    AFTER INSERTING THE DATA THE PERMANENT TABLE SHOULD BE REFERESED PERIODICALLY
    FOR EXAMPLE WE ARE DELETING THE RECORDS WHICH ARE GREATER THAN A WEEK FOR THIS TABLE.
    DELETE
    FROM HPER_MKTPRICE
    WHERE UPD_DT >= TRUNC (UPD_DT) - 7;
    COMMIT;*/
    UTL_FILE.FREMOVE ('HG_HAMC_PUMP_DIR', 'MKTPRICE.csv');
  ELSE
    RAISE FILE_NOTFOUND;
  END IF;
EXCEPTION
WHEN EX_UPLOAD THEN
  RAISE_APPLICATION_ERROR(-20001,'DATA IS ALREADY UPLOADED IN THE SYSTEM FOR TODAY. YOU WILL NOT BE ABLE TO UPLOAD THE FILE FOR TODAY PLEASE TRY TO UPLOAD THE TOMORROW.');
WHEN FILE_NOTFOUND THEN
  RAISE_APPLICATION_ERROR(-20002,'FILE NOT FOUND IN THE DIRECTORY.');
END HPROC_MKTPRICE;

/
