--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Procedure HPROC_CAMS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE HPROC_CAMS 
AS
  V_COUNT       NUMBER;
  EX_UPLOAD     EXCEPTION;
  FILE_NOTFOUND EXCEPTION;
  V_CNT         NUMBER;
  V_EXISTS      BOOLEAN;
  V_LENGTH      NUMBER;
  V_BLOCKSIZE   NUMBER;
  V_AUDIT       NUMBER;
BEGIN
  UTL_FILE.FGETATTR('HG_HAMC_PUMP_DIR', 'CAMS.CSV', V_EXISTS, V_LENGTH, V_BLOCKSIZE);
  IF V_EXISTS THEN
    /*
    NEED TO CHECK THE DATA SO THAT THE DATA DOES NOT GET INSERTED INTO THE TEMPOPARY TABLE
    MULTIPLE TIMES EVEN IF THE PROCEDURE IS RUNNED MULTIPLE TIMES
    */
    SELECT COUNT(*)
    INTO V_COUNT
    FROM HPER_CAMS HPER_CAMS,
      HTMP_CAMS_EXT HTMP_CAMS_EXT
    WHERE HPER_CAMS.HDFC_AMC_CODE = HTMP_CAMS_EXT.HDFC_AMC_CODE
    AND HPER_CAMS.CAMS_CODE       = HTMP_CAMS_EXT.CAMS_CODE
    AND HPER_CAMS.SCHEME          = HTMP_CAMS_EXT.SCHEME
    AND HPER_CAMS.CLOSING_BALANCE = HTMP_CAMS_EXT.CLOSING_BALANCE
    AND HPER_CAMS.OTHERS          = HTMP_CAMS_EXT.OTHERS
    AND HPER_CAMS.C_PAYOUT        = HTMP_CAMS_EXT.C_PAYOUT
    AND HPER_CAMS.C_REINVEST      = HTMP_CAMS_EXT.C_REINVEST
    AND HPER_CAMS.IND_HUF         = HTMP_CAMS_EXT.IND_HUF
    AND HPER_CAMS.R_PAYOUT        = HTMP_CAMS_EXT.R_PAYOUT
    AND HPER_CAMS.R_REINVEST      = HTMP_CAMS_EXT.R_REINVEST
    AND HPER_CAMS.C_BLANK         = HTMP_CAMS_EXT.C_BLANK
    AND HPER_CAMS.R_BLANK         = HTMP_CAMS_EXT.R_BLANK
    AND HPER_CAMS.UPLOAD_DT       = SYSDATE;
    IF V_COUNT                    < 1 THEN
      /*
      INSERTING THE DATA FROM THE TEMPORARY TABLE INTO THE PERMANENT TABLE
      */
      INSERT
      INTO HPER_CAMS
        (
          HDFC_AMC_CODE,
          CAMS_CODE,
          SCHEME,
          CLOSING_BALANCE,
          OTHERS,
          C_PAYOUT,
          C_REINVEST,
          IND_HUF,
          R_PAYOUT,
          R_REINVEST,
          C_BLANK,
          R_BLANK,
          UPLOAD_DT,
          VALUE_DATE,
          STATUS
        )
      SELECT HTMP_CAMS_EXT.HDFC_AMC_CODE,
        HTMP_CAMS_EXT.CAMS_CODE,
        HTMP_CAMS_EXT.SCHEME,
        HTMP_CAMS_EXT.CLOSING_BALANCE,
        HTMP_CAMS_EXT.OTHERS,
        HTMP_CAMS_EXT.C_PAYOUT,
        HTMP_CAMS_EXT.C_REINVEST,
        HTMP_CAMS_EXT.IND_HUF,
        HTMP_CAMS_EXT.R_PAYOUT,
        HTMP_CAMS_EXT.R_REINVEST,
        HTMP_CAMS_EXT.C_BLANK,
        HTMP_CAMS_EXT.R_BLANK,
        SYSDATE,
        SYSDATE,
        'A'
      FROM HTMP_CAMS_EXT;
      COMMIT;
    ELSE
      /*
      NEED TO THROW AN EXCEPTION IF THE RECORD ALREADY EXISTS.
      */
      RAISE EX_UPLOAD;
    END IF;
    /*
    NEED TO CHECK THE DATA SO THAT THE DATA DOES NOT GET INSERTED INTO THE PERMENANT TABLE
    MULTIPLE TIMES EVEN IF THE PROCEDURE IS RUNNED MULTIPLE TIMES
    */
    SELECT COUNT(*)
    INTO V_CNT
    FROM HPER_CAMS HPER_CAMS,
      HUPD_CAPITAL_CONTROL_CAMS HUPD_CAPITAL_CONTROL_CAMS
    WHERE HUPD_CAPITAL_CONTROL_CAMS.HDFC_AMC_CODE = HPER_CAMS.HDFC_AMC_CODE
    AND HPER_CAMS.CAMS_CODE                       = HUPD_CAPITAL_CONTROL_CAMS.CAMS_CODE
    AND HPER_CAMS.SCHEME                          = HUPD_CAPITAL_CONTROL_CAMS.SCHEME
    AND HPER_CAMS.CLOSING_BALANCE                 = HUPD_CAPITAL_CONTROL_CAMS.CLOSING_BALANCE
    AND HPER_CAMS.OTHERS                          = HUPD_CAPITAL_CONTROL_CAMS.OTHERS
    AND HPER_CAMS.C_PAYOUT                        = HUPD_CAPITAL_CONTROL_CAMS.C_PAYOUT
    AND HPER_CAMS.C_REINVEST                      = HUPD_CAPITAL_CONTROL_CAMS.C_REINVEST
    AND HPER_CAMS.IND_HUF                         = HUPD_CAPITAL_CONTROL_CAMS.IND_HUF
    AND HPER_CAMS.R_PAYOUT                        = HUPD_CAPITAL_CONTROL_CAMS.R_PAYOUT
    AND HPER_CAMS.R_REINVEST                      = HUPD_CAPITAL_CONTROL_CAMS.R_REINVEST
    AND HPER_CAMS.C_BLANK                         = HUPD_CAPITAL_CONTROL_CAMS.C_BLANK
    AND HPER_CAMS.R_BLANK                         = HUPD_CAPITAL_CONTROL_CAMS.R_BLANK;
    IF V_CNT                                      < 1 THEN
      /*
      INSERTING THE DATA FROM PERMANENT TABLE TO HI TABLES SINCE WE NEED TO TRUNCATE THE PERMANENT TABLE
      REGULARLY AND ALSO WE WILL PICK ONLY SELECTED COLUMNS IN THE HI TABLE .
      */
      INSERT
      INTO HUPD_CAPITAL_CONTROL_CAMS
        (
          CAMS_ID,
          HDFC_AMC_CODE,
          CAMS_CODE,
          SCHEME,
          CLOSING_BALANCE,
          OTHERS,
          C_PAYOUT,
          C_REINVEST,
          IND_HUF,
          R_PAYOUT,
          R_REINVEST,
          C_BLANK,
          R_BLANK,
          UPLOAD_DT
        )
      SELECT CAMS_SEQ.NEXTVAL,
        HDFC_AMC_CODE,
        CAMS_CODE,
        SCHEME,
        CLOSING_BALANCE,
        OTHERS,
        C_PAYOUT,
        C_REINVEST,
        IND_HUF,
        R_PAYOUT,
        R_REINVEST,
        C_BLANK,
        R_BLANK,
        SYSDATE
      FROM HPER_CAMS;
      COMMIT;
    ELSE
      RAISE EX_UPLOAD;
    END IF;
    /*
    INSERTING THE DATA IN THE AUDITLOG TABLE FOR FURTHER REFERENCE.
    */
    SELECT COUNT(*)
    INTO V_AUDIT
    FROM HI_AUDITLOG
    WHERE PROCEDURE_NAME = 'HPROC_CAMS'
    AND TABLE_NAME       = 'HUPD_CAPITAL_CONTROL_CAMS'
    AND AUDIT_DT         = SYSDATE
    AND PROCEDURE_FLAG   = 'Y';
    IF V_AUDIT           < 1 THEN
      INSERT
      INTO HI_AUDITLOG
        (
          AUDITLOG_ID,
          PROCEDURE_NAME,
          TABLE_NAME,
          REPO_NAME,
          PROCEDURE_FLAG,
          TABLE_FLAG,
          REPO_FLAG,
          AUDIT_DT
        )
      SELECT AUDIT_SEQ.NEXTVAL ,
        'HPROC_CAMS'                AS PROC_NAME,
        'HUPD_CAPITAL_CONTROL_CAMS' AS TABLE_NAME,
        NULL                        AS REP0_NAME,
        'Y'                         AS PROCEDURE_FLAG,
        'Y'                         AS TABLE_FLAG,
        NULL                        AS REPO_FLAG,
        SYSDATE                     AS AUDIT_DT
      FROM DUAL;
      COMMIT;
    ELSE
      RAISE EX_UPLOAD;
    END IF;
    /*
    AFTER INSERTING THE DATA THE PERMANENT TABLE SHOULD BE REFERESED PERIODICALLY
    FOR EXAMPLE WE ARE DELETING THE RECORDS WHICH ARE GREATER THAN A WEEK FOR THIS TABLE.
    DELETE
    FROM HPER_CAMS
    WHERE UPD_DT >= TRUNC (UPD_DT) - 7;
    COMMIT;*/
    UTL_FILE.FREMOVE ('HG_HAMC_PUMP_DIR', 'CAMS.CSV');
  ELSE
    RAISE FILE_NOTFOUND;
  END IF;
EXCEPTION
WHEN EX_UPLOAD THEN
  RAISE_APPLICATION_ERROR(-20001,'DATA IS ALREADY UPLOADED IN THE SYSTEM FOR TODAY. YOU WILL NOT BE ABLE TO UPLOAD THE FILE FOR TODAY PLEASE TRY TO UPLOAD THE TOMORROW.');
WHEN FILE_NOTFOUND THEN
  RAISE_APPLICATION_ERROR(-20002,'FILE NOT FOUND IN THE DIRECTORY.');
END HPROC_CAMS;

/
