--------------------------------------------------------
--  File created - Friday-October-18-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View DISB_MONTH
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "RIGEL"."DISB_MONTH" ("MONTHS", "DISB_AMT") AS 
  SELECT TO_CHAR(HAS.TXN_DT,'MONTH') MONTHS,
--  SUM(HAS.FF_N3) ROI,
  SUM(HAT.BASE_AMOUNT) Disb_Amt
FROM HI_ACCOUNT_TXN HAT,
  HI_ACCOUNT_SNAPSHOT HAS
WHERE HAT.ACCOUNT_ID    = HAT.ACCOUNT_ID
AND HAT.TXN_TYPE_ID     = 101
AND TO_DATE(HAT.TXN_DT) = '01-MAR-13'
  --AND TO_DATE(HAT.TXN_DT)     < '31-MAR-13'
AND hat.txn_dt = has.TXN_DT
GROUP BY HAS.TXN_DT
UNION ALL
-- April Disbursment Amount
SELECT TO_CHAR(HAS.TXN_DT,'MONTH') MONTHS,
 -- NVL(SUM(HAS.FF_N3),0) ROI,
  SUM(HAT.BASE_AMOUNT) Disb_Amt
FROM HI_ACCOUNT_TXN HAT,
  HI_ACCOUNT_SNAPSHOT HAS
WHERE HAT.ACCOUNT_ID    = HAT.ACCOUNT_ID
AND HAT.TXN_TYPE_ID     = 101
AND TO_DATE(HAT.TXN_DT) = '01-APR-13'
  --AND hat.txn_dt      < '30-APR-13'
AND hat.txn_dt = has.TXN_DT
GROUP BY HAS.TXN_DT
UNION ALL
-- MAY Disbursment Amount
SELECT TO_CHAR(HAS.TXN_DT,'MONTH') MONTHS,
 -- SUM(HAS.FF_N3) ROI,
  SUM(HAT.BASE_AMOUNT) Disb_Amt
FROM HI_ACCOUNT_TXN HAT,
  HI_ACCOUNT_SNAPSHOT HAS
WHERE HAT.ACCOUNT_ID    = HAT.ACCOUNT_ID
AND HAT.TXN_TYPE_ID     = 101
AND TO_DATE(HAT.TXN_DT) = '01-MAY-13'
  --AND hat.txn_dt      < '30-MAY-13'
AND HAT.TXN_DT = HAS.TXN_DT
GROUP BY HAS.TXN_DT
UNION ALL
-- JUNE Disbursment Amount
SELECT TO_CHAR(HAS.TXN_DT,'MONTH') MONTHS,
 -- SUM(HAS.FF_N3) ROI,
  SUM(HAT.BASE_AMOUNT) Disb_Amt
FROM HI_ACCOUNT_TXN HAT,
  HI_ACCOUNT_SNAPSHOT HAS
WHERE HAT.ACCOUNT_ID    = HAT.ACCOUNT_ID
AND HAT.TXN_TYPE_ID     = 101
AND TO_DATE(HAT.TXN_DT) = '01-JUN-13'
  --AND hat.txn_dt      < '30-JUN-13'
AND HAT.TXN_DT = HAS.TXN_DT
GROUP BY HAS.TXN_DT
UNION ALL
-- JULY Disbursment Amount
SELECT TO_CHAR(HAS.TXN_DT,'MONTH') MONTHS,
 -- SUM(HAS.FF_N3) ROI,
  SUM(HAT.BASE_AMOUNT) Disb_Amt
FROM HI_ACCOUNT_TXN HAT,
  HI_ACCOUNT_SNAPSHOT HAS
WHERE HAT.ACCOUNT_ID    = HAT.ACCOUNT_ID
AND HAT.TXN_TYPE_ID     = 101
AND TO_DATE(HAT.TXN_DT) = '01-JUL-13'
  --AND hat.txn_dt      < '30-JUL-13'
AND HAT.TXN_DT = HAS.TXN_DT
GROUP BY HAS.TXN_DT
UNION ALL
-- AUG Disbursment Amount
SELECT TO_CHAR(HAS.TXN_DT,'MONTH') MONTHS,
 -- SUM(HAS.FF_N3) ROI,
  SUM(HAT.BASE_AMOUNT) Disb_Amt
FROM HI_ACCOUNT_TXN HAT,
  HI_ACCOUNT_SNAPSHOT HAS
WHERE HAT.ACCOUNT_ID    = HAT.ACCOUNT_ID
AND HAT.TXN_TYPE_ID     = 101
AND TO_DATE(HAT.TXN_DT) = '01-AUG-13'
  --AND TO_DATE(HAT.TXN_DT)     < '30-AUG-13'
AND HAT.TXN_DT = HAS.TXN_DT
GROUP BY HAS.TXN_DT
UNION ALL
-- SEPT Disbursment Amount
SELECT TO_CHAR(HAS.TXN_DT,'MONTH') MONTHS,
  --SUM(HAS.FF_N3) ROI,
  SUM(HAT.BASE_AMOUNT) Disb_Amt
FROM HI_ACCOUNT_TXN HAT,
  HI_ACCOUNT_SNAPSHOT HAS
WHERE HAT.ACCOUNT_ID    = HAT.ACCOUNT_ID
AND HAT.TXN_TYPE_ID     = 101
AND TO_DATE(HAT.TXN_DT) = '01-SEP-13'
  --AND TO_DATE(HAT.TXN_DT)     < '30-SEP-13'
AND HAT.TXN_DT = HAS.TXN_DT
GROUP BY HAS.TXN_DT;
REM INSERTING into RIGEL.DISB_MONTH
SET DEFINE OFF;
Insert into RIGEL.DISB_MONTH (MONTHS,DISB_AMT) values ('MARCH    ',420119855928);
Insert into RIGEL.DISB_MONTH (MONTHS,DISB_AMT) values ('JUNE     ',1106282500000);
Insert into RIGEL.DISB_MONTH (MONTHS,DISB_AMT) values ('JULY     ',4127600000);
Insert into RIGEL.DISB_MONTH (MONTHS,DISB_AMT) values ('AUGUST   ',109016366000);
