--------------------------------------------------------
--  File created - Friday-October-18-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View HV_APPLICATION_DEVIATION_DIMS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "RIGEL"."HV_APPLICATION_DEVIATION_DIMS" ("APPLICATION_NO", "POLICY_DEV_REASON_CODE", "SENT_FOR_APPROVAL_AMOUNT", "LOCATION", "BRANCH_NAME", "RELATIONSHIP_OFFICER", "SALES_MANAGER", "SOURCE_DSA_DIRECT_BRANCH", "PROGRAM_REGULAR_HIGH_YIELD", "PRODUCT_HL_HE", "PRODUCT_VARIANT", "SCHEME", "LOGIN_DATE", "RELOGIN_STATUS", "CONSTITUTION", "LOAN_AMT_APPLIED", "LOGIN_LMF_AMOUNT", "SECURITY_PROPERTY", "CURRENT_STATUS", "CURRENT_STATUS_DATE", "MONTH", "YEAR", "WEEK", "FIRST_STAGE_CREDIT_DECISION", "FIRST_STAGE_DECISION_DATE", "FINAL_DECISION_AMT", "REJECTION_REASON", "APPROVAL_COUNT", "REJECTED_COUNT", "DELOGGED_COUNT", "PENDING_COUNT", "DISCREPANT_COUNT", "SENT_FOR_APPROVAL_COUNT", "APPROVED_AMOUNT", "REJECTED_AMOUNT", "DELOGGED_AMOUNT", "PENDING_AMOUNT", "DISCREPANT_AMOUNT", "SR_NO") AS 
  select dm.application_no,dm.policy_dev_reason_code,
sum(had.SENT_FOR_APPROVAL_AMOUNT) SENT_FOR_APPROVAL_AMOUNT,
had.LOCATION,
had.BRANCH_NAME,
had.RELATIONSHIP_OFFICER,
had.SALES_MANAGER,
had.SOURCE_DSA_DIRECT_BRANCH,
had.PROGRAM_REGULAR_HIGH_YIELD,
had.PRODUCT_HL_HE,
had.PRODUCT_VARIANT,
had.SCHEME,
had.LOGIN_DATE,
had.RELOGIN_STATUS,
had.CONSTITUTION,
sum(had.LOAN_AMT_APPLIED) LOAN_AMT_APPLIED,
sum(had.LOGIN_LMF_AMOUNT) LOGIN_LMF_AMOUNT,
had.SECURITY_PROPERTY,
had.CURRENT_STATUS,
had.CURRENT_STATUS_DATE,
NVL(had.MONTH,TO_CHAR(to_date('30-09-2013','DD-MM-YYYY'),'MONTH')) MONTH,
  nvl(had.YEAR,to_char(to_date('30-09-2013','DD-MM-YYYY'),'YY')) YEAR,
  nvl(had.WEEK,to_char(to_date('30-09-2013','DD-MM-YYYY'),'WW')) WEEK,
had.FIRST_STAGE_CREDIT_DECISION,
had.FIRST_STAGE_DECISION_DATE,
sum(had.FINAL_DECISION_AMT) FINAL_DECISION_AMT,
had.REJECTION_REASON,
sum(had.APPROVAL_COUNT) APPROVAL_COUNT,
sum(had.REJECTED_COUNT) REJECTED_COUNT,
sum(had.DELOGGED_COUNT) DELOGGED_COUNT,
sum(had.PENDING_COUNT) PENDING_COUNT,
sum(had.DISCREPANT_COUNT) DISCREPANT_COUNT,
sum(had.SENT_FOR_APPROVAL_COUNT) SENT_FOR_APPROVAL_COUNT,
sum(had.APPROVED_AMOUNT) APPROVED_AMOUNT,

sum(had.REJECTED_AMOUNT) REJECTED_AMOUNT,
sum(had.DELOGGED_AMOUNT) DELOGGED_AMOUNT,
sum(had.PENDING_AMOUNT) PENDING_AMOUNT,
sum(had.DISCREPANT_AMOUNT) DISCREPANT_AMOUNT ,
had.SR_NO 
from hv_application_data had,tmp_app_deviation_mapping dm
where had.sr_no  =dm.sr_no (+) 
group by
dm.application_no,
had.LOCATION,
had.BRANCH_NAME,
had.RELATIONSHIP_OFFICER,
had.SALES_MANAGER,
had.SOURCE_DSA_DIRECT_BRANCH,
had.PROGRAM_REGULAR_HIGH_YIELD,
had.PRODUCT_HL_HE,
had.PRODUCT_VARIANT,
had.SCHEME,
had.LOGIN_DATE,
had.RELOGIN_STATUS,
had.CONSTITUTION,
dm.policy_dev_reason_code,
had.SECURITY_PROPERTY,
had.CURRENT_STATUS,
had.CURRENT_STATUS_DATE,
had.MONTH,
 had.YEAR,
 had.WEEK,
had.FIRST_STAGE_CREDIT_DECISION,
had.FIRST_STAGE_DECISION_DATE,
had.REJECTION_REASON,
had.SR_NO;
