--------------------------------------------------------
--  File created - Friday-October-18-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View HV_BOUNCE_PRESENTATION
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "RIGEL"."HV_BOUNCE_PRESENTATION" ("ACCOUNT_ID", "APPLICATION_NO", "TXN_DT", "BOUNCE_MONTH", "BOUNCE_COUNT", "PRESENTATION_COUNT") AS 
  SELECT ACCOUNT_ID,APPLICATION_NO,TXN_DT,BOUNCE_MONTH,SUM(BOUNCE_COUNT) BOUNCE_COUNT ,SUM(PRESENTATION_COUNT) PRESENTATION_COUNT
FROM (select HAT.ACCOUNT_ID ACCOUNT_ID,HAT.APPLICATION_NO APPLICATION_NO,HAT.TXN_DT,to_char(HAT.TXN_DT, 'MONTH') BOUNCE_MONTH,count(HAT.TXN_DT) BOUNCE_COUNT, NULL PRESENTATION_COUNT
from
HI_ACCOUNT_TXN HAT
where HAT.TXN_TYPE_ID = 115
GROUP BY to_char(HAT.TXN_DT, 'MONTH'),HAT.APPLICATION_NO,HAT.TXN_DT,HAT.ACCOUNT_ID
UNION ALL
select HAT.ACCOUNT_ID,HAT.APPLICATION_NO APPLICATION_NO,HAT.TXN_DT,to_char(HAT.TXN_DT, 'MONTH') BOUNCE_MONTH,NULL BOUNCE_COUNT,count(HAT.TXN_DT) PRESENTATION_COUNT
from
HI_ACCOUNT_TXN HAT
where HAT.TXN_TYPE_ID = 114
GROUP BY to_char(HAT.TXN_DT, 'MONTH'),HAT.APPLICATION_NO,HAT.TXN_DT,HAT.ACCOUNT_ID) A GROUP  BY ACCOUNT_ID,TXN_DT,BOUNCE_MONTH,APPLICATION_NO;
