--------------------------------------------------------
--  File created - Friday-October-18-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View HV_BOOKED_POS_30
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "RIGEL"."HV_BOOKED_POS_30" ("WEEK_OF_YEAR", "MONTH_LONG", "MONTH_LONG_DESC", "QUARTER_ID", "HALF_OF_YEAR_ID", "YEAR_ID", "ORG_ID", "TXN_DT", "SANCTION_DATE", "MONTHLY_POS", "CURRENT_POS", "BOOKED_AMT", "SANCTION_AMT", "POS_COUNT", "BOOKED_COUNT", "SANCTION_COUNT", "TOTAL_INTEREST_OS_BASE_AMOUNT", "POS_MON", "POS_CURRENT", "D31_60", "D61_90", "D91_180", "G_180", "NUMERATOR", "DENOMINATOR", "APPLICATION_NO", "ACCOUNT_ID", "SCHEME_CODE", "AMOUNT_APPROVED", "PRODUCT_CODE", "PRODUCT_DESC1", "PRORGAM", "PROMOTION", "ACTIVE", "SOURCE_OFFICE_ID", "GEO_ID", "BUSINESS_LINE", "BUSINESS_SUBLINE", "FACILITY", "PRODUCT", "AGE_BRACKET", "NET_INCOME_BRACKET", "AGENCY_NAME1", "AGENCY_TYPE_DESC1", "CIBIL_SCORE", "LTV_DESC1", "DBR_DESC1", "RM_NAME", "PROPERTY_TPE", "BOUNCE_MONTH", "BOUNCE_COUNT", "PRESENTATION_COUNT", "BOUNCE_RATIO", "DPD_COUNT", "DPD_CLASSIFICATION_DESC1", "DPD_CLASSIFICATION_DESC2", "BASE_AMT") AS 
  SELECT TIME1.WEEK_OF_YEAR,
  TIME1.MONTH_LONG,
  TIME1.MONTH_LONG_DESC,
  TIME1.QUARTER_ID,
  TIME1.HALF_OF_YEAR_ID,
  TIME1.YEAR_ID,
  HAS.ORG_ID,
  HAS.TXN_DT TXN_DT,
  NULL SANCTION_DATE,
  (HAS.TOTAL_PRIN_OS_BASE_AMOUNT/10000000) MONTHLY_POS ,
  --DECODE(HAS.TXN_DT,TO_DATE('01-08-13','dd-mm-yy'),HAS.TOTAL_PRIN_OS_BASE_AMOUNT, 0) CURRENT_POS,
(DECODE(to_char(HAS.TXN_DT,'dd-mm-yy'),to_char((SELECT MAX(HAS1.TXN_DT) FROM HI_ACCOUNT_SNAPSHOT HAS1 where Has1.Account_Id = has.account_id),'dd-mm-yy'),HAS.TOTAL_PRIN_OS_BASE_AMOUNT, 0)/10000000) CURRENT_POS,
  NULL BOOKED_AMT,
  NULL SANCTION_AMT,
  TO_NUMBER(1) POS_COUNT,
  TO_NUMBER(0) BOOKED_COUNT,
  TO_NUMBER(0) SANCTION_COUNT,
  HAS.TOTAL_INTEREST_OS_BASE_AMOUNT,
  NULL POS_MON,
  NULL POS_CURRENT,
  NULL D31_60,
  NULL D61_90,
  NULL D91_180,
  NULL G_180,
 -- NULL CD,
   NULL NUMERATOR,
    NULL DENOMINATOR,
  HAS.APPLICATION_NO,
  HAS.ACCOUNT_ID,
  HAF.SCHEME_CODE,
  HAF.AMOUNT_APPROVED,
  HAF.PRODUCT_CODE,
  HAF.PRODUCT_DESC1,
  HAF.FF_VC4 PRORGAM,
  HAF.FF_VC5 PROMOTION,
  HAS.ACTIVE,
  HAD.SOURCE_OFFICE_ID,
  BRANCH.GEO_ID,
  HOD.HOD_PRODUCT_DESC1 BUSINESS_LINE,
  HOD.HOD_SUBPRODUCT_DESC1 BUSINESS_SUBLINE,
  HOD.HOD_FACILITY_DESC1 FACILITY,
  HOD.HOD_SCHEME_DESC1 PRODUCT,
  HD.AGE_BRACKET_DESC1 AGE_BRACKET,
  HD.INCOME_BRACKET_DESC1 NET_INCOME_BRACKET,
  AGENCY.AGENCY_NAME1,
  AGENCY. AGENCY_TYPE_DESC1,
  HD.SCORECARD_DESC1 CIBIL_SCORE,
  HD.LTV_DESC1,
  HD.DBR_DESC1 ,
  HAC. EMPLOYEE_NAME1 RM_NAME, 
    HAF.FF_VC1 PROPERTY_TPE,
     NULL BOUNCE_MONTH,
    NULL BOUNCE_COUNT,
    NULL PRESENTATION_COUNT,
    NULL BOUNCE_RATIO,
        TO_NUMBER(0) DPD_COUNT,
NULL DPD_CLASSIFICATION_DESC1,
NULL DPD_CLASSIFICATION_DESC2,
NULL BASE_AMT
FROM HI_APPLICATION_FACILITIES HAF,
  TIME_CAL_DIM TIME1,
  HI_APPLICATION_DEMOGRAPHICS HAD,
  HI_ACCOUNT_SNAPSHOT HAS,
  UM_GEOGRAPHY BRANCH,
  HI_APPLICATION_AGENCY HAC,
  UM_AGENCY AGENCY,
  HDM_OFFERING_DIM HOD,
  HDM_CUSTOMER HD
WHERE BRANCH.GEO_CODE  = TO_CHAR(HAD.SOURCE_OFFICE_ID)
AND HAS.APPLICATION_NO = HAC.APPLICATION_NO
AND HAF.APPLICATION_NO = HAD.APPLICATION_NO
AND TIME1.DAY_ID (+)   = HAS.TXN_DT
AND TIME1.ORG_ID (+)   = HAS.ORG_ID
AND AGENCY.AGENCY_CODE = HAC.AGENCY_CODE
--AND HD.UID_NO (+)      = HAS.ACCOUNT_ID
AND HAS.APPLICATION_NO = HD.UID_NO
AND HAF.ORG_ID         =777
AND HAF.ACCOUNT_ID     = HAS.ACCOUNT_ID
AND HAF.PRODUCT_CODE   = HOD.HOD_SCHEME_CODE
AND HAS.ACCOUNT_ID     = HAF.ACCOUNT_ID
AND HAS.ORG_ID         =777
UNION ALL
SELECT TIME1.WEEK_OF_YEAR,
  TIME1.MONTH_LONG,
  TIME1.MONTH_LONG_DESC,
  TIME1.QUARTER_ID,
  TIME1.HALF_OF_YEAR_ID,
  TIME1.YEAR_ID,
  HAT.ORG_ID,
  HAT.TXN_DT TXN_DT,
  HAF.FF_D1 SANCTION_DATE,
  NULL MONTHLY_POS,
  NULL CURRENT_POS,
  round((HAT.BASE_AMOUNT/10000000),5) BOOKED_AMT,
  round((HAF.AMOUNT_APPROVED/10000000),5) SANCTION_AMT,
  TO_NUMBER(0) POS_COUNT,
  TO_NUMBER(1)BOOKED_COUNT,
 -- TO_NUMBER(1) SANCTION_COUNT,
  DECODE(nvl(HAF.AMOUNT_APPROVEd,0),0,TO_NUMBER(0), TO_NUMBER(1)) SANCTION_COUNT,
  NULL TOTAL_INTEREST_OS_BASE_AMOUNT,
  NULL POS_MON,
  NULL POS_CURRENT,
  NULL D31_60,
  NULL D61_90,
  NULL D91_180,
  NULL G_180,
 -- NULL CD,
  NULL NUMERATOR,
    NULL DENOMINATOR,

  HAF.APPLICATION_NO,
  HAF.ACCOUNT_ID,
  HAF.SCHEME_CODE,
  HAF.AMOUNT_APPROVED,
  HAF.PRODUCT_CODE,
  HAF.PRODUCT_DESC1,
  HAF.FF_VC4 PRORGAM,
  HAF.FF_VC5 PROMOTION,
  HAT.ACTIVE,
  HAD.SOURCE_OFFICE_ID,
  BRANCH.GEO_ID,
  HOD.HOD_PRODUCT_DESC1 BUSINESS_LINE,
  HOD.HOD_SUBPRODUCT_DESC1 BUSINESS_SUBLINE,
  HOD.HOD_FACILITY_DESC1 FACILITY,
  HOD.HOD_SCHEME_DESC1 PRODUCT,
  HD.AGE_BRACKET_DESC1 AGE_BRACKET,
  HD.INCOME_BRACKET_DESC1 NET_INCOME_BRACKET,
  AGENCY.AGENCY_NAME1,
  AGENCY.AGENCY_TYPE_DESC1,
  HD.SCORECARD_DESC1 CIBIL_SCORE,
  HD.LTV_DESC1,
  HD.DBR_DESC1 ,
  HAC. EMPLOYEE_NAME1 RM_NAME, 
    HAF.FF_VC1 PROPERTY_TPE,
     NULL BOUNCE_MONTH,
    NULL BOUNCE_COUNT,
    NULL PRESENTATION_COUNT,
    NULL BOUNCE_RATIO,
        TO_NUMBER(0) DPD_COUNT,
NULL DPD_CLASSIFICATION_DESC1,
NULL DPD_CLASSIFICATION_DESC2,
NULL BASE_AMT
FROM HI_APPLICATION_FACILITIES HAF,
  TIME_CAL_DIM TIME1,
  HI_ACCOUNT_TXN HAT,
  HI_APPLICATION_DEMOGRAPHICS HAD,
  UM_GEOGRAPHY BRANCH,
  HI_APPLICATION_AGENCY HAC,
  UM_AGENCY AGENCY,
  HDM_OFFERING_DIM HOD,
  HDM_CUSTOMER HD
WHERE HAF.APPLICATION_NO = HAT.APPLICATION_NO
AND BRANCH.GEO_CODE      = TO_CHAR(HAD.SOURCE_OFFICE_ID)
AND HAT.APPLICATION_NO   = HAC.APPLICATION_NO
AND HAF.APPLICATION_NO   = HAD.APPLICATION_NO
AND HAF.APPLICATION_NO   = HAD.APPLICATION_NO
--AND HAT.ACCOUNT_ID       = HD.UID_NO (+)
AND HAT.APPLICATION_NO = HD.UID_NO
AND TIME1.DAY_ID (+)     = HAT.TXN_DT
AND TIME1.ORG_ID (+)     = HAT.ORG_ID
AND HAT.TXN_TYPE_ID      =101
AND AGENCY.AGENCY_CODE   = HAC.AGENCY_CODE
AND HAF.ORG_ID           =777
AND HAF.ACCOUNT_ID       = HAT.ACCOUNT_ID
AND HAF.PRODUCT_CODE     = HOD.HOD_SCHEME_CODE
UNION ALL
SELECT TIME1.WEEK_OF_YEAR,
  TIME1.MONTH_LONG,
  TIME1.MONTH_LONG_DESC,
  TIME1.QUARTER_ID,
  TIME1.HALF_OF_YEAR_ID,
  TIME1.YEAR_ID,
  NULL ORG_ID,
  --  TO_DATE(TO_CHAR(HCD.TXN_DT,'DD-MM-YY'),'DD-MM-YY') TXN_DT,
  HCD.TXN_DT TXN_DT,
  HAF.FF_D1 SANCTION_DATE,
  NULL MONTHLY_POS,
  NULL CURRENT_POS,
  NULL BOOKED_AMT,
  NULL SANCTION_AMT,
  TO_NUMBER(0) POS_COUNT,
  TO_NUMBER(0)BOOKED_COUNT,
  TO_NUMBER(0) SANCTION_COUNT,
  NULL TOTAL_INTEREST_OS_BASE_AMOUNT,
  HCD.POS_MON,
  HCD.POS_CURRENT,
  HCD.D31_60,
  HCD.D61_90,
  HCD.D91_180,
  HCD.G_180,
    --DECODE((HCD.POS_CURRENT),0,0,NVL(ROUND((((NVL(HCD.D31_60,0))+(NVL(HCD.D61_90,0))+(NVL(HCD.D91_180,0))+(NVL(HCD.G_180,0)))/((NVL(HCD.POS_CURRENT,0)) + (((NVL(HCD.D31_60,0))+(NVL(HCD.D61_90,0))+(NVL(HCD.D91_180,0))+(NVL(HCD.G_180,0)))))),5),0)) CD,
    NVL(ROUND((((NVL(HCD.D31_60,0))+(NVL(HCD.D61_90,0))+(NVL(HCD.D91_180,0))+(NVL(HCD.G_180,0)))),5),0) NUMERATOR,
    ((NVL(HCD.POS_CURRENT,0)) + (((NVL(HCD.D31_60,0))+(NVL(HCD.D61_90,0))+(NVL(HCD.D91_180,0))+(NVL(HCD.G_180,0))))) DENOMINATOR,
  HAF.APPLICATION_NO,
  HAF.ACCOUNT_ID,
  HAF.SCHEME_CODE,
  HAF.AMOUNT_APPROVED,
  HAF.PRODUCT_CODE,
  HAF.PRODUCT_DESC1,
  HAF.FF_VC4 PRORGAM,
  HAF.FF_VC5 PROMOTION,
  NULL ACTIVE,
  HAD.SOURCE_OFFICE_ID,
  BRANCH.GEO_ID,
  HOD.HOD_PRODUCT_DESC1 BUSINESS_LINE,
  HOD.HOD_SUBPRODUCT_DESC1 BUSINESS_SUBLINE,
  HOD.HOD_FACILITY_DESC1 PRODUCT,
  HOD.HOD_SCHEME_DESC1 FACILITY,
  HD.AGE_BRACKET_DESC1 AGE_BRACKET,
  HD.INCOME_BRACKET_DESC1 NET_INCOME_BRACKET,
  HCD.AGENCY_NAME1 AGENCY_NAME1,
  HCD.AGENCY_TYPE_DESC1 AGENCY_TYPE_DESC1,
  HD.SCORECARD_DESC1 CIBIL_SCORE,
  HD.LTV_DESC1,
  HD.DBR_DESC1 ,
  NULL RM_NAME, 
    HAF.FF_VC1 PROPERTY_TPE,
    NULL BOUNCE_MONTH,
    NULL BOUNCE_COUNT,
    NULL PRESENTATION_COUNT,
    NULL BOUNCE_RATIO,
        TO_NUMBER(0) DPD_COUNT,
  NULL DPD_CLASSIFICATION_DESC1,
NULL DPD_CLASSIFICATION_DESC2,
NULL BASE_AMT
FROM HI_APPLICATION_FACILITIES HAF,
  TIME_CAL_DIM TIME1,
  HI_APPLICATION_DEMOGRAPHICS HAD,
  UM_GEOGRAPHY BRANCH,
  HDM_OFFERING_DIM HOD,
  HDM_CUSTOMER HD,
  HV_CD_30 HCD
WHERE BRANCH.GEO_CODE  = TO_CHAR(HAD.SOURCE_OFFICE_ID)
AND HAF.APPLICATION_NO = HAD.APPLICATION_NO
--AND HCD.ACCOUNT_ID     = HD.UID_NO (+)

AND HCD.APPLICATION_NO = HD.UID_NO
AND UPPER(HCD.POS_MON) = UPPER(TIME1.MONTH_LONG)
AND TIME1.DAY_ID (+)   = TO_DATE(TO_CHAR(HCD.TXN_DT,'DD-MM-YY'),'DD-MM-YY')  --to_date(HCD.TXN_DT,'dd-mm-yy')
AND TIME1.ORG_ID      = 777
  --AND HAT.TXN_TYPE_ID      =101
 -- AND AGENCY.AGENCY_CODE   = HAC.AGENCY_CODE
  AND HAF.ORG_ID           =777
  AND HAF.ACCOUNT_ID        = HCD.ACCOUNT_ID
  AND HAF.PRODUCT_CODE     = HOD.HOD_SCHEME_CODE
  UNION ALL
  
-- TO COMPUTE BOUNCE RATE
SELECT TIME1.WEEK_OF_YEAR,
  TIME1.MONTH_LONG,
  TIME1.MONTH_LONG_DESC,
  TIME1.QUARTER_ID,
  TIME1.HALF_OF_YEAR_ID,
  TIME1.YEAR_ID,
  NULL ORG_ID,
  --  TO_DATE(TO_CHAR(HCD.TXN_DT,'DD-MM-YY'),'DD-MM-YY') TXN_DT,
  HBP.TXN_DT TXN_DT,
  HAF.FF_D1 SANCTION_DATE,
  NULL MONTHLY_POS,
  NULL CURRENT_POS,
  NULL BOOKED_AMT,
  NULL SANCTION_AMT,
  TO_NUMBER(0) POS_COUNT,
  TO_NUMBER(0)BOOKED_COUNT,
  TO_NUMBER(0) SANCTION_COUNT,
  NULL TOTAL_INTEREST_OS_BASE_AMOUNT,
  NULL POS_MON,
  NULL POS_CURRENT,
  NULL D31_60,
  NULL D61_90,
  NULL D91_180,
  NULL G_180,
    null NUMERATOR,
    null DENOMINATOR,
  HAF.APPLICATION_NO,
  HAF.ACCOUNT_ID,
  HAF.SCHEME_CODE,
  HAF.AMOUNT_APPROVED,
  HAF.PRODUCT_CODE,
  HAF.PRODUCT_DESC1,
  HAF.FF_VC4 PRORGAM,
  HAF.FF_VC5 PROMOTION,
  NULL ACTIVE,
  HAD.SOURCE_OFFICE_ID,
  BRANCH.GEO_ID,
  HOD.HOD_PRODUCT_DESC1 BUSINESS_LINE,
  HOD.HOD_SUBPRODUCT_DESC1 BUSINESS_SUBLINE,
  HOD.HOD_FACILITY_DESC1 PRODUCT,
  HOD.HOD_SCHEME_DESC1 FACILITY,
  HD.AGE_BRACKET_DESC1 AGE_BRACKET,
  HD.INCOME_BRACKET_DESC1 NET_INCOME_BRACKET,
  AGENCY.AGENCY_NAME1 AGENCY_NAME1,
  NULL AGENCY_TYPE_DESC1,
  HD.SCORECARD_DESC1 CIBIL_SCORE,
  HD.LTV_DESC1,
  HD.DBR_DESC1 ,
  NULL RM_NAME, 
    HAF.FF_VC1 PROPERTY_TPE,
    HBP.BOUNCE_MONTH BOUNCE_MONTH,
    (HBP.BOUNCE_COUNT*100) BOUNCE_COUNT ,
    HBP.PRESENTATION_COUNT PRESENTATION_COUNT,
    ((HBP.BOUNCE_COUNT/HBP.PRESENTATION_COUNT)*100) BOUNCE_RATIO,
    TO_NUMBER(0) DPD_COUNT,
NULL DPD_CLASSIFICATION_DESC1,
NULL DPD_CLASSIFICATION_DESC2,
NULL BASE_AMT
    FROM HI_APPLICATION_FACILITIES HAF,
    TIME_CAL_DIM TIME1,
    HI_APPLICATION_DEMOGRAPHICS HAD,
    HI_ACCOUNT_SNAPSHOT HAS,
    HV_BOUNCE_PRESENTATION HBP,
    UM_GEOGRAPHY BRANCH,
    HI_APPLICATION_AGENCY HAC,
    UM_AGENCY AGENCY,
    HDM_OFFERING_DIM HOD,
    HDM_CUSTOMER HD
  WHERE BRANCH.GEO_CODE  = TO_CHAR(HAD.SOURCE_OFFICE_ID)
  AND HBP.ACCOUNT_ID     = HAS.ACCOUNT_ID
  AND HAS.APPLICATION_NO = HAC.APPLICATION_NO
  AND HAF.APPLICATION_NO = HAD.APPLICATION_NO
  AND TIME1.DAY_ID (+)   = HBP.TXN_DT
  AND TIME1.ORG_ID       = HAS.ORG_ID
  AND AGENCY.AGENCY_CODE = HAC.AGENCY_CODE
 -- AND HD.UID_NO (+)      = HBP.ACCOUNT_ID
   AND HD.UID_NO       = HBP.APPLICATION_NO
  AND HAF.ORG_ID         =HAS.ORG_ID
  AND HAF.ACCOUNT_ID     = HBP.ACCOUNT_ID
  AND HAF.PRODUCT_CODE   = HOD.HOD_SCHEME_CODE
  AND HAS.ACCOUNT_ID     = HBP.ACCOUNT_ID
  AND HAS.ORG_ID         =777
  UNION ALL
  -- TO COMPUTE Deliquency RATE
SELECT TIME1.WEEK_OF_YEAR,
  TIME1.MONTH_LONG,
  TIME1.MONTH_LONG_DESC,
  TIME1.QUARTER_ID,
  TIME1.HALF_OF_YEAR_ID,
  TIME1.YEAR_ID,
  NULL ORG_ID,
  --  TO_DATE(TO_CHAR(HCD.TXN_DT,'DD-MM-YY'),'DD-MM-YY') TXN_DT,
  DPD.EFFECTIVE_DT TXN_DT,
  HAF.FF_D1 SANCTION_DATE,
  NULL MONTHLY_POS,
  NULL CURRENT_POS,
  NULL BOOKED_AMT,
  NULL SANCTION_AMT,
  TO_NUMBER(0) POS_COUNT,
  TO_NUMBER(0)BOOKED_COUNT,
  TO_NUMBER(0) SANCTION_COUNT,
  NULL TOTAL_INTEREST_OS_BASE_AMOUNT,
  NULL POS_MON,
  NULL POS_CURRENT,
  NULL D31_60,
  NULL D61_90,
  NULL D91_180,
  NULL G_180,
    null NUMERATOR,
    null DENOMINATOR,
  HAF.APPLICATION_NO,
  HAF.ACCOUNT_ID,
  HAF.SCHEME_CODE,
  HAF.AMOUNT_APPROVED,
  HAF.PRODUCT_CODE,
  HAF.PRODUCT_DESC1,
  HAF.FF_VC4 PRORGAM,
  HAF.FF_VC5 PROMOTION,
  NULL ACTIVE,
  HAD.SOURCE_OFFICE_ID,
  BRANCH.GEO_ID,
  HOD.HOD_PRODUCT_DESC1 BUSINESS_LINE,
  HOD.HOD_SUBPRODUCT_DESC1 BUSINESS_SUBLINE,
  HOD.HOD_FACILITY_DESC1 PRODUCT,
  HOD.HOD_SCHEME_DESC1 FACILITY,
  HD.AGE_BRACKET_DESC1 AGE_BRACKET,
  HD.INCOME_BRACKET_DESC1 NET_INCOME_BRACKET,
  AGENCY.AGENCY_NAME1 AGENCY_NAME1,
  NULL AGENCY_TYPE_DESC1,
  HD.SCORECARD_DESC1 CIBIL_SCORE,
  HD.LTV_DESC1,
  HD.DBR_DESC1 ,
  NULL RM_NAME, 
    HAF.FF_VC1 PROPERTY_TPE,
    NULL BOUNCE_MONTH,
    NULL BOUNCE_COUNT,
    NULL PRESENTATION_COUNT,
    NULL BOUNCE_RATIO,
   TO_NUMBER(1) DPD_COUNT,
DPD.DPD_CLASSIFICATION_DESC1 DPD_CLASSIFICATION_DESC1,
DPD.DPD_CLASSIFICATION_DESC2 DPD_CLASSIFICATION_DESC2,
round(DPD.BASE_AMT/10000000,5) BASE_AMT
    FROM HI_APPLICATION_FACILITIES HAF,
    TIME_CAL_DIM TIME1,
    HI_APPLICATION_DEMOGRAPHICS HAD,
    HI_ACCOUNT_SNAPSHOT HAS,
    HI_COLLECTION_DPD DPD,
    UM_GEOGRAPHY BRANCH,
    HI_APPLICATION_AGENCY HAC,
    UM_AGENCY AGENCY,
    HDM_OFFERING_DIM HOD,
    HDM_CUSTOMER HD
  WHERE BRANCH.GEO_CODE  = TO_CHAR(HAD.SOURCE_OFFICE_ID)
  AND DPD.ACCOUNT_ID     = HAS.ACCOUNT_ID
  AND HAS.APPLICATION_NO = HAC.APPLICATION_NO
  AND HAF.APPLICATION_NO = HAD.APPLICATION_NO
  AND TIME1.DAY_ID (+)   = DPD.EFFECTIVE_DT
  AND TIME1.ORG_ID       = HAS.ORG_ID
  AND AGENCY.AGENCY_CODE = HAC.AGENCY_CODE
 -- AND HD.UID_NO (+)      = HBP.ACCOUNT_ID
   AND HD.UID_NO       = DPD.CASE_NO
  AND HAF.ORG_ID         =HAS.ORG_ID
  AND HAF.ACCOUNT_ID     = DPD.ACCOUNT_ID
  AND HAF.PRODUCT_CODE   = HOD.HOD_SCHEME_CODE
  AND HAS.ACCOUNT_ID     = DPD.ACCOUNT_ID
  AND HAS.ORG_ID         =777;
