--------------------------------------------------------
--  File created - Friday-October-18-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View HV_BOOKED_AMNT
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "RIGEL"."HV_BOOKED_AMNT" ("WEEK_OF_YEAR", "MONTH_LONG", "MONTH_LONG_DESC", "QUARTER", "HALF_OF_YEAR_ID", "YEAR_ID", "ORG_ID", "BOOKED_DT", "APPLICATION_NO", "ACCOUNT_ID", "SCHEME_CODE", "AMOUNT_APPROVED", "BOOKED_AMT", "PRODUCT_CODE", "PRODUCT_DESC1", "ACTIVE", "ACTIVATION_DT", "DEACTIVATION_DT", "SOURCE_OFFICE_ID", "GEO_ID", "BUSINESS_LINE", "BUSINESS_SUBLINE", "FACILITY", "PRODUCT", "AGE_AT_TIME_OF_APP", "AGE_BRACKET", "NET_INCOME", "NET_INCOME_BRACKET", "AGENCY_CODE", "AGENCY_NAME1", "AGENCY_TYPE_DESC1") AS 
  SELECT 
time1.WEEK_OF_YEAR,
time1.MONTH_LONG,
time1.MONTH_LONG_DESC,
time1.QUARTER,
time1.HALF_OF_YEAR_ID,
time1.YEAR_ID,
HAT.ORG_ID,
HAT.TXN_DT BOOKED_DT,
HAF.APPLICATION_NO,
HAF.ACCOUNT_ID,
HAF.SCHEME_CODE,
HAF.AMOUNT_APPROVED,
hat.BASE_AMOUNT BOOKED_AMT,
HAF.PRODUCT_CODE,
HAF.PRODUCT_DESC1,
hat.active,
hat.activation_dt,
hat.deactivation_dt,
HAD.SOURCE_OFFICE_ID,
BRANCH.GEO_ID,
HOD.HOD_PRODUCT_DESC1 Business_Line,
HOD.HOD_SUBPRODUCT_DESC1 Business_SubLine,
HOD.HOD_FACILITY_DESC1 facility,
HOD.HOD_SCHEME_DESC1 product,
had.age_at_time_of_app,
(CASE
WHEN had.age_at_time_of_app = 0 THEN 'AGE DATA NOT AVAILABLE'
WHEN had.age_at_time_of_app BETWEEN 18 AND 25 THEN '18-25'
WHEN had.age_at_time_of_app BETWEEN 26 AND 35 THEN '26-35'
WHEN had.age_at_time_of_app BETWEEN 36 AND 50 THEN '36-50'
WHEN had.age_at_time_of_app BETWEEN 51 AND 60 THEN '51-60'
WHEN had.age_at_time_of_app > 60 THEN 'MORE THAN 60'
ELSE 'UNSPECIFIED'
END) AGE_BRACKET,
had.NET_INCOME,
(CASE
WHEN had.NET_INCOME = 0 THEN 'INCOME DATA NOT AVAILABLE'
WHEN had.NET_INCOME BETWEEN 1 AND 999999 THEN 'BELOW 10 LACS'
WHEN had.NET_INCOME BETWEEN 1000000 AND 3000000 THEN '10-30 LACS'
WHEN had.NET_INCOME BETWEEN 3000001 AND 5000000 THEN '31-50 LACS'
WHEN had.NET_INCOME > 5000001 THEN 'ABOVE 50 LACS'
END) NET_INCOME_BRACKET,
AGENCY.AGENCY_CODE,
AGENCY.AGENCY_NAME1,
AGENCY_TYPE_DESC1
FROM HI_APPLICATION_FACILITIES HAF,
TIME_CAL_DIM TIME1,
HI_ACCOUNT_TXN HAT,
HI_APPLICATION_DEMOGRAPHICS HAD,
UM_GEOGRAPHY BRANCH,
HI_APPLICATION_AGENCY HAC,
UM_AGENCY AGENCY,
HDM_OFFERING_DIM HOD
WHERE haf.application_no = hat.application_no
AND BRANCH.GEO_CODE= TO_CHAR(HAD.SOURCE_OFFICE_ID)
AND HAT.application_no = HAC.application_no  
AND haf.application_no = had.application_no
AND haf.application_no = had.application_no
AND TIME1.DAY_ID (+) = HAT.TXN_DT
AND TIME1.ORG_ID (+) = haT.org_id
AND hat.TXN_TYPE_ID =101
AND AGENCY.AGENCY_CODE = HAC.AGENCY_CODE
AND haf.org_id =777
AND HAF.ACCOUNT_ID = HAT.ACCOUNT_ID
AND HAF.PRODUCT_CODE = HOD.HOD_SCHEME_CODE;
