--------------------------------------------------------
--  File created - Friday-October-18-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View HV_CD_PLUS_30
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "RIGEL"."HV_CD_PLUS_30" ("AGENCY_CODE", "AGENCY_NAME1", "AGENCY_TYPE_DESC1", "POS_MON", "POS_CURRENT", "D31_60", "D61_90", "D91_180", "G_180", "CD") AS 
  SELECT AGENCY_CODE,
AGENCY_NAME1,
AGENCY_TYPE_DESC1,POS_MON,SUM(POS) POS_CURRENT,SUM(D31_60) D31_60,SUM(D61_90) D61_90,SUM(D91_180) D91_180,SUM(G_180) G_180,
ROUND(((SUM(D31_60)+SUM(D61_90)+SUM(D91_180)+SUM(G_180))/(SUM(POS) + SUM(D31_60)+ SUM(D61_90)+SUM(D91_180)+SUM(G_180))),5) CD
FROM 
(SELECT AGENCY.AGENCY_CODE,
AGENCY.AGENCY_NAME1,AGENCY_TYPE_DESC1,to_char(HAS.TXN_DT,'MONTH') POS_MON,
SUM(has.total_prin_os_base_amount) POS,NULL D31_60,NULL D61_90,NULL D91_180,NULL G_180
FROM hi_account_snapshot HAS,
HI_APPLICATION_AGENCY HAC,
UM_AGENCY AGENCY
WHERE haS.org_id =777
and 
HAS.application_no = HAC.application_no 
 AND AGENCY.AGENCY_CODE = HAC.AGENCY_CODE
GROUP BY to_char(HAS.TXN_DT,'MONTH') ,AGENCY.AGENCY_CODE,
AGENCY.AGENCY_NAME1,AGENCY_TYPE_DESC1
UNION ALL
SELECT AGENCY.AGENCY_CODE,
AGENCY.AGENCY_NAME1,
AGENCY_TYPE_DESC1,to_char(DPD.EFFECTIVE_DT,'MONTH') POS_MON,
SUM(dpd.base_amt) POS, NULL D31_60,NULL D61_90,NULL D91_180,NULL G_180
FROM 
HI_COLLECTION_DPD DPD, HI_APPLICATION_AGENCY HAC,
UM_AGENCY AGENCY
WHERE DPD.org_id =777
AND DPD.DPD_CLASSIFICATION_DESC2 = 'DPD 1 (1 TO 30 DAYS)'
and 
dpd.case_no = HAC.application_no 
 AND AGENCY.AGENCY_CODE = HAC.AGENCY_CODE
GROUP BY to_char(DPD.EFFECTIVE_DT,'MONTH'),AGENCY.AGENCY_CODE,
AGENCY.AGENCY_NAME1,
AGENCY_TYPE_DESC1
UNION ALL
SELECT AGENCY.AGENCY_CODE,
AGENCY.AGENCY_NAME1,
AGENCY_TYPE_DESC1,to_char(DPD.EFFECTIVE_DT,'MONTH') POS_MON,
NULL POS,SUM(dpd.base_amt) D31_60,NULL D61_90,NULL D91_180,NULL G_180
FROM 
HI_COLLECTION_DPD DPD,HI_APPLICATION_AGENCY HAC,
UM_AGENCY AGENCY
WHERE DPD.org_id =777
AND DPD.DPD_CLASSIFICATION_DESC2 = 'DPD 2 (31 TO 60 DAYS)'
and 
dpd.case_no = HAC.application_no 
 AND AGENCY.AGENCY_CODE = HAC.AGENCY_CODE
GROUP BY to_char(DPD.EFFECTIVE_DT,'MONTH'),AGENCY.AGENCY_CODE,
AGENCY.AGENCY_NAME1,
AGENCY_TYPE_DESC1
UNION ALL
SELECT AGENCY.AGENCY_CODE,
AGENCY.AGENCY_NAME1,
AGENCY_TYPE_DESC1,to_char(DPD.EFFECTIVE_DT,'MONTH') POS_MON,
NULL POS,NULL D31_60,SUM(dpd.base_amt) D61_90,NULL D91_180,NULL G_180
FROM 
HI_COLLECTION_DPD DPD,HI_APPLICATION_AGENCY HAC,
UM_AGENCY AGENCY
WHERE DPD.org_id =777
AND DPD.DPD_CLASSIFICATION_DESC2 = 'DPD 3 (61 TO 90 DAYS)'and 
dpd.case_no = HAC.application_no 
 AND AGENCY.AGENCY_CODE = HAC.AGENCY_CODE
GROUP BY to_char(DPD.EFFECTIVE_DT,'MONTH'),AGENCY.AGENCY_CODE,
AGENCY.AGENCY_NAME1,
AGENCY_TYPE_DESC1
UNION ALL
SELECT AGENCY.AGENCY_CODE,
AGENCY.AGENCY_NAME1,
AGENCY_TYPE_DESC1,to_char(DPD.EFFECTIVE_DT,'MONTH') POS_MON,
NULL POS,NULL D31_60, NULL D61_90,SUM(dpd.base_amt) D91_180,NULL G_180
FROM 
HI_COLLECTION_DPD DPD,HI_APPLICATION_AGENCY HAC,
UM_AGENCY AGENCY
WHERE DPD.org_id =777
AND DPD.DPD_CLASSIFICATION_DESC2 = 'DPD 4 (90 TO 180 DAYS)'
and 
dpd.case_no = HAC.application_no 
 AND AGENCY.AGENCY_CODE = HAC.AGENCY_CODE
GROUP BY to_char(DPD.EFFECTIVE_DT,'MONTH'),AGENCY.AGENCY_CODE,
AGENCY.AGENCY_NAME1,
AGENCY_TYPE_DESC1
UNION ALL
SELECT AGENCY.AGENCY_CODE,
AGENCY.AGENCY_NAME1,
AGENCY_TYPE_DESC1,to_char(DPD.EFFECTIVE_DT,'MONTH') POS_MON,
NULL POS,NULL D31_60, NULL D61_90,NULL D91_180,SUM(dpd.base_amt) G_180
FROM 
HI_COLLECTION_DPD DPD,HI_APPLICATION_AGENCY HAC,
UM_AGENCY AGENCY
WHERE DPD.org_id =777
AND DPD.DPD_CLASSIFICATION_DESC2 = 'DPD 5 (GREATER THEN 181 DAYS)'
and 
dpd.case_no = HAC.application_no 
 AND AGENCY.AGENCY_CODE = HAC.AGENCY_CODE
GROUP BY to_char(DPD.EFFECTIVE_DT,'MONTH'),AGENCY.AGENCY_CODE,
AGENCY.AGENCY_NAME1,
AGENCY_TYPE_DESC1) A
GROUP BY POS_MON,AGENCY_CODE,
AGENCY_NAME1,
AGENCY_TYPE_DESC1;
