--------------------------------------------------------
--  File created - Friday-October-18-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View HV_GEO_DIM
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "RIGEL"."HV_GEO_DIM" ("BRANCH_GEOID", "BRANCH", "CITY", "STATE", "COUNTRY") AS 
  SELECT DISTINCT BRANCH.GEO_ID BRANCH_GEOID,
  BRANCH.GEO_DESC1 BRANCH,
        CITY.GEO_DESC1 CITY,
    STATE.GEO_DESC1 STATE,
     CRTY.GEO_DESC1 COUNTRY
  FROM 
    UM_GEOGRAPHY CRTY,
    UM_GEOGRAPHY STATE,
    UM_GEOGRAPHY CITY,
    UM_GEOGRAPHY BRANCH
WHERE 
 BRANCH.ORG_ID = 777
     AND STATE.LEVEL_PRED_ID = CRTY.GEO_ID
  AND CITY.LEVEL_PRED_ID  = STATE.GEO_ID
  AND BRANCH.LEVEL_PRED_ID  = CITY.GEO_ID;
REM INSERTING into RIGEL.HV_GEO_DIM
SET DEFINE OFF;
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50346,'KOCHI (105)','Bangalore','Karnataka','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50333,'JAKKASANDRA (090)','Bangalore','Karnataka','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50281,'SANTA CRUZ (026)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50279,'MAHIM (024)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50276,'CENTRAL ADM. OFFFICE (020)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50265,'HASANABAD (009)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50263,'DAHISAR (007)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50283,'RELIEF ROAD  (028)','Ahmedabad','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50328,'CHANDANAGAR  (085)','Hyderabad','Andhra Pradesh','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50305,'A.S.RAO NAGAR (051)','Hyderabad','Andhra Pradesh','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50303,'MADHAPUR (049)','Hyderabad','Andhra Pradesh','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50349,'BARGARH (103)','Bargarh','Orissa','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50239,'PIPARIYA (106)','Pipariya','Gujarat','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50289,'VAPI (034)','Vapi','Gujarat','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50331,'DEDIAPADA (088)','Dediapada','Gujarat','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50344,'COIMBATORE (872)','Coimbatore','Tamilnadu','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50309,'PANAJI (055)','Goa','Goa','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50247,'JAIPUR (111)','Jaipur','New Delhi','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50273,'VERSOVA  (017)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50272,'TREASURY (016)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50264,'GOREGAON  (008)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50329,'MUCHHALA POLYTECHNIC (086)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50291,'C.G.ROAD (036)','Ahmedabad','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50321,'GADDIANNARAMM (076)','Hyderabad','Andhra Pradesh','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50313,'NAKKALGUTTA (059)','Hyderabad','Andhra Pradesh','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50242,'GADARWARA (112)','Madhya Pradesh','Madhya Pradesh','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50241,'HINJILICUT (110)','Orissa','Orissa','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50347,'MANDVI (101)','Mandvi','Gujarat','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50237,'LUDHIANA','Ludhiana','Punjab','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50335,'KAPASHERA (092)','Delhi','Haryana','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50318,'GREATER KAILASH (070)','Delhi','Haryana','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50300,'NEW DELHI (046)','Delhi','Haryana','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50262,'BYCULLA (006)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50259,'DHARAVI (003)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50337,'VASAI (094)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50324,'SATARA ROAD, PUNE (081)','Pune','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50323,'VEJALPUR (080)','Ahmedabad','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50339,'JODHPUR (096)','Jodhpur','Rajasthan','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50249,'ATTABIRA (116)','Orissa','Orissa','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50256,'VADODARA (100)','Vadodara','Gujarat','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50290,'SIDHPUR (035)','Sidhpur','Gujarat','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50330,'GARIAHAT (087)','Kolkata','West Bengal','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50317,'PREET VIHAR (069)','Delhi','Haryana','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50314,'CHENNAI (060)','Chennai','Tamilnadu','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50325,'JAYA NAGAR (082)','Bangalore','Karnataka','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50278,'NARIMAN POINT (023)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50261,'BANDRA (005)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50255,'MUMBAI - NPC (900)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50248,'VASAD (114)','Ahmedabad','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50326,'GHATLODIA (083)','Ahmedabad','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50295,'GANDHINAGAR (041)','Ahmedabad','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50252,'VIJAYAWADA (120)','VIJAYAWADA ','Andhra Pradesh','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50253,'AKIVIDU (122)','AKIVIDU','Andhra Pradesh','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50282,'HYDERABAD (027)','Hyderabad','Andhra Pradesh','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50271,'WARANGAL (015)','Hyderabad','Andhra Pradesh','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50254,'VIJAYWADA (874)','Hyderabad','Andhra Pradesh','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50312,'SECUNDRABAD (058)','Hyderabad','Andhra Pradesh','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50304,'HABSIGUDA (050)','Hyderabad','Andhra Pradesh','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50246,'NANA RASANA (118)','Gujarat','Gujarat','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50348,'NETRANG (102)','Netrang','Gujarat','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50238,'LUCKNOW','Lucknow','Uttar Pradesh','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50332,'BRABOURNE ROAD-KOLKOTA (089)','Kolkata','West Bengal','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50336,'KONDLI (093)','Delhi','Haryana','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50319,'RAJAJI NAGAR - BLR (071)','Bangalore','Karnataka','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50275,'MOHAMEDALI ROAD (019)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50268,'MUMBRA (012)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50257,'MUMBAI MAIN OFFICE  (001)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50338,'NASHIK (095)','Nashik','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50240,'KADODARA (109)','Surat','Gujarat','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50299,'ANKLESHWAR (045)','Ankleshwar','Gujarat','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50250,'NOIDA (119)','Noida','Uttar Pradesh','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50345,'SALEM (873)','Salem','Tamilnadu','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50311,'MAPUSA (057)','Goa','Goa','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50310,'MARGAO (056)','Goa','Goa','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50308,'VASCO-DA-GAMA (054)','Goa','Goa','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50343,'JAIPUR (871)','Jaipur','New Delhi','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50292,'BANGALORE (038)','Bangalore','Karnataka','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50285,'VASHI (030)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50280,'MALAD  (025)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50267,'KURLA (011)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50260,'ANDHERI - WEST (004)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50341,'KONDHAVE KHURD (098)','Pune','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50245,'MANDIDEEP (117)','Madhya Pradesh','Madhya Pradesh','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50243,'DUNGURIPALI (113)','Orissa','Orissa','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50251,'JAGANNATHPUR (121)','Orissa','Orissa','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50294,'RAJKOT (040)','Rajkot','Gujarat','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50296,'BHUJ (042)','Bhuj','Gujarat','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50293,'MIRA ROAD (039)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50286,'LOKHANDWALA  (031)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50269,'NESBIT ROAD (013)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50258,'KALBADEVI  (002)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50307,'SABOO SIDDIQUE (053)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50306,'VIRAR (052)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50270,'PUNE (014)','Pune','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50298,'DAMAN (044)','Ahmedabad','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50320,'S.R.NAGAR (072)','Hyderabad','Andhra Pradesh','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50322,'SHAKESPEAR SARANI (079)','Kolkata','West Bengal','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50334,'CHANDNI CHOWK (091)','Delhi','Haryana','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50316,'JHARSA (062)','Delhi','Haryana','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50340,'CHENNAI BROADWAY (097)','Chennai','Tamilnadu','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50342,'CHANDIGARH (870)','Chandigarh','New Delhi','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50284,'KAUSA (029)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50274,'THANE (018)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50266,'JOGESHWARI  BRANCH (010)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50327,'KAMOTHE (084)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50315,'ANDHERI EAST (061)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50297,'NARIMAN POINT (043)','Mumbai','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50277,'NANDED (022)','Pune','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50302,'J.M.ROAD - PUNE (048)','Pune','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50287,'AURANAGABAD (032)','Aurangabad','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50301,'SILVASSA (047)','Ahmedabad','Maharashtra','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50350,'ITARSI (104)','Itarsi','Madhya Pradesh','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50244,'SONGADH (115)','Surat','Gujarat','INDIA');
Insert into RIGEL.HV_GEO_DIM (BRANCH_GEOID,BRANCH,CITY,STATE,COUNTRY) values (50288,'SURAT (033)','Surat','Gujarat','INDIA');
