--------------------------------------------------------
--  File created - Friday-October-18-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View HV_MOB_SIX_MONTHS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "RIGEL"."HV_MOB_SIX_MONTHS" ("ACCOUNT_ID", "BOOKED_DATE", "MONTHS", "YEARS", "MOB_COUNT", "DISB_COUNT") AS 
  select ACCOUNT_ID, BOOKED_DATE BOOKED_DATE,TO_Char(BOOKED_DATE,'MONTH') MONTHS, TO_Char(BOOKED_DATE,'YYYY') YEARS , sum(MOB_Count) MOB_Count, TO_NUMBER(0) disb_count --, ACCOUNT_ID 
from (
SELECT
TO_DATE(TO_CHAR(ACTT.DISBURSEMENT_DATE,'DD-MON-YYYY'), 'DD-MON-YYYY') BOOKED_DATE,
--TO_CHAR(ACTT.DISBURSEMENT_DATE,'DD-MON-YYYY') BOOKED_DATE,
--ACTT.DISB_COUNT DISB_COUNT ,
count(dpd.account_id) MOB_Count,
dpd.account_id ACCOUNT_ID,
TO_CHAR(MIN(DPD.EFFECTIVE_DT), 'MON-YYYY') DEFAULT_DATE,
TO_CHAR(ACTT.MOB_DATE, 'MON-YYYY') MOB ,
ACTT.MOB_DATE MOB_DATE
FROM 
HI_COLLECTION_DPD dpd, (SELECT
MIN(TO_DATE(TO_CHAR(ACT.TXN_DT, 'MON-YYYY'),'MON-YYYY')) DISBURSEMENT_DATE ,
ADD_MONTHS(TO_DATE(TO_CHAR(ACT.TXN_DT , 'MON-YYYY'), 'MON-YYYY'),6) MOB_DATE ,
ACT.APPLICATION_NO APPLICATION_NO,
ACT.ACCOUNT_ID ACCOUNT_ID,
count(ACT.APPLICATION_NO) DISB_COUNT,
sum(ACT.BASE_AMOUNT) DISB_AMT
FROM 
HI_ACCOUNT_TXN ACT
WHERE ACT.TXN_TYPE_ID = 101
AND TO_DATE(TO_CHAR(ACT.TXN_DT,'DD-MM-YY'),'DD-MM-YY') BETWEEN  TO_DATE('01-09-12','DD-MM-YY') AND  TO_DATE('28-02-13','DD-MM-YY') 
group by 
ACT.APPLICATION_NO,
ACT.BASE_AMOUNT,
ACT.ACCOUNT_ID,
TO_CHAR(ACT.TXN_DT, 'MON-YYYY')
order by 1 desc ) ACTT
WHERE DPD.CASE_NO =  ACTT.APPLICATION_NO
AND ROUND((DPD.EFFECTIVE_DT - ACTT.DISBURSEMENT_DATE)/30) <=6
group by 
dpd.ACCOUNT_ID,
ACTT.DISB_COUNT,
ACTT.DISB_AMT,
ACTT.DISBURSEMENT_DATE,
TO_CHAR(ACTT.MOB_DATE, 'MON-YYYY'),
TO_CHAR(ACTT.MOB_DATE, 'MONTH'), 
TO_CHAR(ACTT.MOB_DATE, 'YYYY'),
ACTT.MOB_DATE) a group by ACCOUNT_ID,BOOKED_DATE,TO_Char(BOOKED_DATE,'MONTH'), TO_Char(BOOKED_DATE,'YYYY') --,ACCOUNT_ID
union all
select  ACCOUNT_ID, DISBURSEMENT_DATE BOOKED_DATE,TO_Char(DISBURSEMENT_DATE,'MONTH') MONTHS, TO_Char(DISBURSEMENT_DATE,'YYYY') YEARS, 0 MOB_Count,  sum(DISB_COUNT) DISB_COUNT --,ACCOUNT_ID  
from ( 
SELECT
MIN(TO_DATE(TO_CHAR(ACT.TXN_DT, 'DD-MON-YYYY'), 'DD-MON-YYYY')) DISBURSEMENT_DATE ,
ADD_MONTHS(TO_DATE(TO_CHAR(ACT.TXN_DT , 'MON-YYYY'), 'MON-YYYY'),6) MOB ,
count(ACT.APPLICATION_NO) DISB_COUNT,
act.account_id ACCOUNT_ID
FROM 
HI_ACCOUNT_TXN ACT
WHERE ACT.TXN_TYPE_ID = 101
AND TO_DATE(TO_CHAR(ACT.TXN_DT,'DD-MM-YY'),'DD-MM-YY') BETWEEN  TO_DATE('01-09-12','DD-MM-YY') AND  TO_DATE('28-02-13','DD-MM-YY') 
group by 
ACT.APPLICATION_NO,
ACT.BASE_AMOUNT,
ACT.ACCOUNT_ID,
TO_CHAR(ACT.TXN_DT, 'MON-YYYY')
order by 1 desc) a group by ACCOUNT_ID,DISBURSEMENT_DATE,TO_Char(DISBURSEMENT_DATE,'MONTH'), TO_Char(DISBURSEMENT_DATE,'YYYY');
