--------------------------------------------------------
--  File created - Friday-October-18-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View HV_POS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "RIGEL"."HV_POS" ("WEEK_OF_YEAR", "MONTH_LONG", "MONTH_LONG_DESC", "QUARTER_ID", "HALF_OF_YEAR_ID", "YEAR_ID", "ORG_ID", "TXN_DT", "SANCTION_DATE", "MONTHLY_POS", "CURRENT_POS", "BOOKED_AMT", "SANCTION_AMT", "POS_COUNT", "BOOKED_COUNT", "SANCTION_COUNT", "TOTAL_INTEREST_OS_BASE_AMOUNT", "APPLICATION_NO", "ACCOUNT_ID", "SCHEME_CODE", "AMOUNT_APPROVED", "PRODUCT_CODE", "PRODUCT_DESC1", "PRORGAM", "PROMOTION", "ACTIVE", "SOURCE_OFFICE_ID", "GEO_ID", "BUSINESS_LINE", "BUSINESS_SUBLINE", "FACILITY", "PRODUCT", "AGE_BRACKET", "NET_INCOME_BRACKET", "AGENCY_NAME1", "AGENCY_TYPE_DESC1", "CIBIL_SCORE", "LTV_DESC1", "DBR_DESC1", "RM_NAME") AS 
  SELECT TIME1.WEEK_OF_YEAR,
    TIME1.MONTH_LONG,
    TIME1.MONTH_LONG_DESC,
    TIME1.QUARTER_ID,
    TIME1.HALF_OF_YEAR_ID,
    TIME1.YEAR_ID,
    HAS.ORG_ID,
    HAS.TXN_DT TXN_DT,
    NULL SANCTION_DATE,
    HAS.TOTAL_PRIN_OS_BASE_AMOUNT MONTHLY_POS,
    --(SELECT MAX(TO_DATE(HAS1.TXN_DT,'DD-MM-YY')) FROM HI_ACCOUNT_SNAPSHOT HAS1) MAX_DATE
    DECODE(HAS.TXN_DT,TO_DATE('01-08-13','DD-MM-YY'),HAS.TOTAL_PRIN_OS_BASE_AMOUNT, 0) CURRENT_POS,
    NULL BOOKED_AMT,
    NULL SANCTION_AMT,
    TO_NUMBER(1) POS_COUNT,--COUNT(HAS.ACCOUNT_ID)
    TO_NUMBER(0) BOOKED_COUNT,
    TO_NUMBER(0) SANCTION_COUNT,
    HAS.TOTAL_INTEREST_OS_BASE_AMOUNT,
    HAS.APPLICATION_NO,
    HAS.ACCOUNT_ID,
    HAF.SCHEME_CODE,
    HAF.AMOUNT_APPROVED,
    HAF.PRODUCT_CODE,
    HAF.PRODUCT_DESC1,
    HAF.FF_VC4 PRORGAM,
    HAF.FF_VC5 PROMOTION,
    HAS.ACTIVE,
    --HAS.ACTIVATION_DT,
    --HAS.DEACTIVATION_DT,
    HAD.SOURCE_OFFICE_ID,
    BRANCH.GEO_ID,
    HOD.HOD_PRODUCT_DESC1 BUSINESS_LINE,
    HOD.HOD_SUBPRODUCT_DESC1 BUSINESS_SUBLINE,
    HOD.HOD_FACILITY_DESC1 FACILITY,
    HOD.HOD_SCHEME_DESC1 PRODUCT,
    HD.AGE_BRACKET_DESC1 AGE_BRACKET,
    HD.INCOME_BRACKET_DESC1 NET_INCOME_BRACKET,
    --AGENCY.AGENCY_CODE,
    AGENCY.AGENCY_NAME1,
    AGENCY. AGENCY_TYPE_DESC1,
     HD.SCORECARD_DESC1 CIBIL_SCORE,
     HD.LTV_DESC1,
     HD.DBR_DESC1
,
 HAC. EMPLOYEE_NAME1 RM_NAME
  FROM HI_APPLICATION_FACILITIES HAF,
    TIME_CAL_DIM TIME1,
    HI_APPLICATION_DEMOGRAPHICS HAD,
    HI_ACCOUNT_SNAPSHOT HAS,
    UM_GEOGRAPHY BRANCH,
    HI_APPLICATION_AGENCY HAC,
    UM_AGENCY AGENCY,
    HDM_OFFERING_DIM HOD,
    HDM_CUSTOMER HD
  WHERE BRANCH.GEO_CODE  = TO_CHAR(HAD.SOURCE_OFFICE_ID)
  AND HAS.APPLICATION_NO = HAC.APPLICATION_NO
  AND HAF.APPLICATION_NO = HAD.APPLICATION_NO
  AND TIME1.DAY_ID (+)   = HAS.TXN_DT
  AND TIME1.ORG_ID (+)   = HAS.ORG_ID
  AND AGENCY.AGENCY_CODE = HAC.AGENCY_CODE
  AND HD.UID_NO (+)      = HAS.ACCOUNT_ID
  AND HAF.ORG_ID         =777
  AND HAF.ACCOUNT_ID     = HAS.ACCOUNT_ID
  AND HAF.PRODUCT_CODE   = HOD.HOD_SCHEME_CODE
  AND HAS.ACCOUNT_ID     = HAF.ACCOUNT_ID
  AND HAS.ORG_ID         =777
  UNION ALL
  SELECT TIME1.WEEK_OF_YEAR,
    TIME1.MONTH_LONG,
    TIME1.MONTH_LONG_DESC,
    TIME1.QUARTER_ID,
    TIME1.HALF_OF_YEAR_ID,
    TIME1.YEAR_ID,
    HAT.ORG_ID,
    HAT.TXN_DT TXN_DT,
    HAF.FF_D1 SANCTION_DATE,
    NULL MONTHLY_POS,
    NULL CURRENT_POS,
    HAT.BASE_AMOUNT BOOKED_AMT,
    HAF.AMOUNT_APPROVED SANCTION_AMT,
    TO_NUMBER(0) POS_COUNT,
    TO_NUMBER(1)BOOKED_COUNT,
    --COUNT(HAT.ACCOUNT_ID) BOOKED_COUNT,
    TO_NUMBER(1) SANCTION_COUNT,
    --COUNT(DECODE (HAF.FF_D1, NULL,1,0) SANCTION_COUNT,
    NULL TOTAL_INTEREST_OS_BASE_AMOUNT,
    HAF.APPLICATION_NO,
    HAF.ACCOUNT_ID,
    HAF.SCHEME_CODE,
    HAF.AMOUNT_APPROVED,
    HAF.PRODUCT_CODE,
    HAF.PRODUCT_DESC1,
    HAF.FF_VC4 PRORGAM,
    HAF.FF_VC5 PROMOTION,
    HAT.ACTIVE,
    --HAT.ACTIVATION_DT,
    --HAT.DEACTIVATION_DT,
    HAD.SOURCE_OFFICE_ID,
    BRANCH.GEO_ID,
    HOD.HOD_PRODUCT_DESC1 BUSINESS_LINE,
    HOD.HOD_SUBPRODUCT_DESC1 BUSINESS_SUBLINE,
    HOD.HOD_FACILITY_DESC1 FACILITY,
    HOD.HOD_SCHEME_DESC1 PRODUCT,
    HD.AGE_BRACKET_DESC1 AGE_BRACKET,
   HD.INCOME_BRACKET_DESC1 NET_INCOME_BRACKET,
    --AGENCY.AGENCY_CODE,
    AGENCY.AGENCY_NAME1,
     AGENCY.AGENCY_TYPE_DESC1,
    HD.SCORECARD_DESC1 CIBIL_SCORE,
    HD.LTV_DESC1,
    HD.DBR_DESC1
,
 HAC. EMPLOYEE_NAME1 RM_NAME
  FROM HI_APPLICATION_FACILITIES HAF,
    TIME_CAL_DIM TIME1,
    HI_ACCOUNT_TXN HAT,
    HI_APPLICATION_DEMOGRAPHICS HAD,
    UM_GEOGRAPHY BRANCH,
    HI_APPLICATION_AGENCY HAC,
    UM_AGENCY AGENCY,
    HDM_OFFERING_DIM HOD,
    HDM_CUSTOMER HD
  WHERE HAF.APPLICATION_NO = HAT.APPLICATION_NO
  AND BRANCH.GEO_CODE      = TO_CHAR(HAD.SOURCE_OFFICE_ID)
  AND HAT.APPLICATION_NO   = HAC.APPLICATION_NO
  AND HAF.APPLICATION_NO   = HAD.APPLICATION_NO
  AND HAF.APPLICATION_NO   = HAD.APPLICATION_NO
  AND HAT.ACCOUNT_ID       = HD.UID_NO (+)
  AND TIME1.DAY_ID (+)     = HAT.TXN_DT
  AND TIME1.ORG_ID (+)     = HAT.ORG_ID
  AND HAT.TXN_TYPE_ID      =101
  AND AGENCY.AGENCY_CODE   = HAC.AGENCY_CODE
  AND HAF.ORG_ID           =777
  AND HAF.ACCOUNT_ID       = HAT.ACCOUNT_ID
  AND HAF.PRODUCT_CODE     = HOD.HOD_SCHEME_CODE;
