--------------------------------------------------------
--  File created - Friday-October-18-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View HV_POS_AMT
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "RIGEL"."HV_POS_AMT" ("WEEK_OF_YEAR", "MONTH_LONG", "MONTH_LONG_DESC", "QUARTER", "HALF_OF_YEAR_ID", "YEAR_ID", "TXN_DT", "MONTHLY_POS", "CURRENT_POS", "TOTAL_INTEREST_OS_BASE_AMOUNT", "APPLICATION_NO", "ACCOUNT_ID", "SCHEME_CODE", "AMOUNT_APPROVED", "PRODUCT_CODE", "PRODUCT_DESC1", "ACTIVE", "SOURCE_OFFICE_ID", "GEO_ID", "BUSINESS_LINE", "BUSINESS_SUBLINE", "FACILITY", "PRODUCT", "AGE_AT_TIME_OF_APP", "AGE_BRACKET", "NET_INCOME", "NET_INCOME_BRACKET", "AGENCY_CODE", "AGENCY_NAME1", "AGENCY_TYPE_DESC1") AS 
  SELECT 
time1.WEEK_OF_YEAR,
time1.MONTH_LONG,
time1.MONTH_LONG_DESC,
time1.QUARTER,
time1.HALF_OF_YEAR_ID,
time1.YEAR_ID,
HAS.TXN_DT,
HAS.TOTAL_PRIN_OS_BASE_AMOUNT MONTHLY_POS,
--(select max(TO_DATE(HAS1.TXN_DT,'dd-mm-yy')) from HI_ACCOUNT_SNAPSHOT HAS1) MAX_DATE
DECODE(HAS.TXN_DT,TO_DATE('01-08-13','dd-mm-yy'),HAS.TOTAL_PRIN_OS_BASE_AMOUNT, 0) CURRENT_POS,
HAS.TOTAL_INTEREST_OS_BASE_AMOUNT,
HAS.APPLICATION_NO,
HAS.ACCOUNT_ID,
HAF.SCHEME_CODE,
HAF.AMOUNT_APPROVED,
HAF.PRODUCT_CODE,
HAF.PRODUCT_DESC1,
HAS.active,
--haS.activation_dt,
--haS.deactivation_dt,
HAD.SOURCE_OFFICE_ID,
BRANCH.GEO_ID,
HOD.HOD_PRODUCT_DESC1 Business_Line,
HOD.HOD_SUBPRODUCT_DESC1 Business_SubLine,
HOD.HOD_FACILITY_DESC1 facility,
HOD.HOD_SCHEME_DESC1 product,
had.age_at_time_of_app,
(CASE
WHEN had.age_at_time_of_app = 0 THEN 'AGE DATA NOT AVAILABLE'
WHEN had.age_at_time_of_app BETWEEN 18 AND 25 THEN '18-25'
WHEN had.age_at_time_of_app BETWEEN 26 AND 35 THEN '26-35'
WHEN had.age_at_time_of_app BETWEEN 36 AND 50 THEN '36-50'
WHEN had.age_at_time_of_app BETWEEN 51 AND 60 THEN '51-60'
WHEN had.age_at_time_of_app > 60 THEN 'MORE THAN 60'
ELSE 'UNSPECIFIED'
END) AGE_BRACKET,
had.NET_INCOME,
(CASE
WHEN had.NET_INCOME = 0 THEN 'INCOME DATA NOT AVAILABLE'
WHEN had.NET_INCOME BETWEEN 1 AND 999999 THEN 'BELOW 10 LACS'
WHEN had.NET_INCOME BETWEEN 1000000 AND 3000000 THEN '10-30 LACS'
WHEN had.NET_INCOME BETWEEN 3000001 AND 5000000 THEN '31-50 LACS'
WHEN had.NET_INCOME > 5000001 THEN 'ABOVE 50 LACS'
END) NET_INCOME_BRACKET,
AGENCY.AGENCY_CODE,
AGENCY.AGENCY_NAME1,
AGENCY_TYPE_DESC1
FROM HI_APPLICATION_FACILITIES HAF,
TIME_CAL_DIM TIME1,
HI_APPLICATION_DEMOGRAPHICS HAD,
HI_ACCOUNT_SNAPSHOT HAS,
UM_GEOGRAPHY BRANCH,
HI_APPLICATION_AGENCY HAC,
UM_AGENCY AGENCY,
HDM_OFFERING_DIM HOD
WHERE BRANCH.GEO_CODE= TO_CHAR(HAD.SOURCE_OFFICE_ID)
AND HAS.application_no = HAC.application_no 
AND haf.application_no = had.application_no
AND TIME1.DAY_ID (+) = HAS.TXN_DT
AND TIME1.ORG_ID (+) = HAS.org_id
AND AGENCY.AGENCY_CODE = HAC.AGENCY_CODE
AND haf.org_id =777
AND HAF.ACCOUNT_ID = HAS.ACCOUNT_ID
AND HAF.PRODUCT_CODE = HOD.HOD_SCHEME_CODE
AND HAS.ACCOUNT_ID = HAF.ACCOUNT_ID
AND HAS.org_id =777;
