--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HI_ACCOUNT_PREV
--------------------------------------------------------

  CREATE TABLE HI_ACCOUNT_PREV 
   (	AMC_CODE VARCHAR2(100 BYTE), 
	SCHEME VARCHAR2(100 BYTE), 
	LEVEL_1 VARCHAR2(100 BYTE), 
	LEVEL_2 VARCHAR2(100 BYTE), 
	LEVEL_3 VARCHAR2(100 BYTE), 
	LEVEL_4 VARCHAR2(100 BYTE), 
	LEVEL_5 VARCHAR2(100 BYTE), 
	CURRENCY VARCHAR2(100 BYTE), 
	RECTYPE VARCHAR2(1 BYTE), 
	CURRNO NUMBER(5,0), 
	ACCOUNT VARCHAR2(100 BYTE), 
	PRT_LEVEL NUMBER(1,0), 
	OP_BAL_CR NUMBER(21,5), 
	OP_BAL_DR NUMBER(21,5), 
	FCY_OP_BAL_CR NUMBER(21,5), 
	FCY_OP_BAL_DR NUMBER(21,5), 
	BALANCE_CR NUMBER(21,5), 
	BALANCE_DR NUMBER(21,5), 
	FCY_BALANCE_CR NUMBER(21,5), 
	FCY_BALANCE_DR NUMBER(21,5), 
	FWD_BAL_CR NUMBER(21,5), 
	FWD_BAL_DR NUMBER(21,5), 
	FCY_FWD_BAL_CR NUMBER(21,5), 
	FCY_FWD_BAL_DR NUMBER(21,5), 
	AMOUNT_REVAL NUMBER(21,5), 
	NAME VARCHAR2(100 BYTE), 
	CTRL_ATYPE VARCHAR2(1 BYTE), 
	IE_BS_TYPE VARCHAR2(1 BYTE), 
	TRNS_IE_BAL_YN VARCHAR2(1 BYTE), 
	POST_Y_N VARCHAR2(1 BYTE), 
	LEVELS NUMBER(1,0), 
	GPOST_Y_N VARCHAR2(1 BYTE), 
	L2NAME VARCHAR2(100 BYTE), 
	SECURITY_Y_N VARCHAR2(1 BYTE), 
	FCY_CUR_OP_BAL NUMBER(18,3), 
	CUR_OP_BAL NUMBER(18,3), 
	PERMITTED_Y_N VARCHAR2(1 BYTE), 
	TAXABLE_Y_N VARCHAR2(1 BYTE), 
	CCYREVAL_Y_N VARCHAR2(1 BYTE), 
	INTERFACE_AC VARCHAR2(100 BYTE), 
	STATUS VARCHAR2(4 BYTE), 
	INP_DT_TM VARCHAR2(16 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHI_TBS ;


