--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HI_ACCENT_CURR
--------------------------------------------------------

  CREATE TABLE HI_ACCENT_CURR 
   (	AMC_CODE VARCHAR2(12 BYTE), 
	DEAL_ID VARCHAR2(19 BYTE), 
	SCHEME VARCHAR2(12 BYTE), 
	LEVEL_1 VARCHAR2(6 BYTE), 
	LEVEL_2 VARCHAR2(14 BYTE), 
	LEVEL_3 VARCHAR2(14 BYTE), 
	LEVEL_4 VARCHAR2(14 BYTE), 
	LEVEL_5 VARCHAR2(14 BYTE), 
	VALUE_DATE DATE, 
	AMOUNT NUMBER(18,3), 
	CURRENCY VARCHAR2(3 BYTE), 
	EXCH_RATE NUMBER(18,10), 
	FCY_AMOUNT NUMBER(18,3), 
	CHQ_DATE DATE, 
	BOOK_DATE DATE, 
	TRAN_TYPE VARCHAR2(6 BYTE), 
	NARRATION VARCHAR2(125 BYTE), 
	APP_REFER VARCHAR2(17 BYTE), 
	CHQ_NUMBER VARCHAR2(15 BYTE), 
	REV_FLG VARCHAR2(4 BYTE), 
	STATUS VARCHAR2(4 BYTE), 
	SECURITY VARCHAR2(35 BYTE), 
	BROKER_CPARTY VARCHAR2(12 BYTE), 
	PUR_DATE DATE, 
	PAYREC_REFER VARCHAR2(17 BYTE), 
	SYSGEN_Y_N VARCHAR2(1 BYTE), 
	DESC1 VARCHAR2(500 BYTE), 
	DESC2 VARCHAR2(500 BYTE), 
	DESC3 VARCHAR2(500 BYTE), 
	FF_N1 NUMBER(21,5), 
	FF_N2 NUMBER(21,5), 
	FF_N3 NUMBER(21,5), 
	FF_N4 NUMBER(21,5), 
	FF_N5 NUMBER(21,5), 
	FF_VC1 VARCHAR2(500 BYTE), 
	FF_VC2 VARCHAR2(500 BYTE), 
	FF_VC3 VARCHAR2(500 BYTE), 
	FF_VC4 VARCHAR2(500 BYTE), 
	FF_VC5 VARCHAR2(500 BYTE), 
	FF_D1 DATE, 
	FF_D2 DATE, 
	FF_D3 DATE, 
	CR_ID VARCHAR2(50 BYTE), 
	CR_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	UPD_ID VARCHAR2(50 BYTE), 
	UPD_DT TIMESTAMP (6), 
	ACTIVE VARCHAR2(2 BYTE) DEFAULT 'Y', 
	ACTIVATION_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	DEACTIVATION_DT TIMESTAMP (6) DEFAULT '31-DEC-4099 12:00:00 AM'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHI_TBS ;
--------------------------------------------------------
--  DDL for Index CT_ACCENT
--------------------------------------------------------

  CREATE INDEX CT_ACCENT ON HI_ACCENT_CURR (DEAL_ID, SCHEME, LEVEL_1) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHINDX_TBS ;
--------------------------------------------------------
--  Constraints for Table HI_ACCENT_CURR
--------------------------------------------------------

  ALTER TABLE HI_ACCENT_CURR MODIFY (AMC_CODE NOT NULL ENABLE);
 
  ALTER TABLE HI_ACCENT_CURR MODIFY (DEAL_ID NOT NULL ENABLE);
 
  ALTER TABLE HI_ACCENT_CURR MODIFY (CR_ID NOT NULL ENABLE);
 
  ALTER TABLE HI_ACCENT_CURR MODIFY (CR_DT NOT NULL ENABLE);
 
  ALTER TABLE HI_ACCENT_CURR MODIFY (ACTIVE NOT NULL ENABLE);
 
  ALTER TABLE HI_ACCENT_CURR MODIFY (ACTIVATION_DT NOT NULL ENABLE);
 
  ALTER TABLE HI_ACCENT_CURR MODIFY (DEACTIVATION_DT NOT NULL ENABLE);

