--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HI_FRONTEND_POSITION
--------------------------------------------------------

  CREATE TABLE HI_FRONTEND_POSITION 
   (	INSURANCE VARCHAR2(100 BYTE), 
	PORTFOLIO_BASIS VARCHAR2(100 BYTE), 
	AS_ON_DATE DATE, 
	CURRENCY VARCHAR2(100 BYTE), 
	ASSET_CLASS VARCHAR2(100 BYTE), 
	INSTRUMENT VARCHAR2(100 BYTE), 
	HOLDING_QUANTITY NUMBER(25,5), 
	MATURITY_MONTHS NUMBER(25,5), 
	YIELD NUMBER(25,5), 
	DURATION NUMBER(25,5), 
	MODIFIED_DURATION NUMBER(25,5), 
	MARKET_VALUE NUMBER(25,5), 
	INSTRUMENT_RATING VARCHAR2(100 BYTE), 
	COMPANY_RATING VARCHAR2(100 BYTE), 
	MATURITY_DATE DATE, 
	PUT_DATE DATE, 
	CALL_DATE DATE, 
	FACE_VALUE NUMBER(25,5), 
	TOTAL_FACE_VALUE NUMBER(25,5), 
	FREQUENCY VARCHAR2(100 BYTE), 
	EXTERNAL_CODE VARCHAR2(100 BYTE), 
	MARKET_PRICE_DATE DATE, 
	MARKET_PRICE NUMBER(25,5), 
	VALUATION_DATE DATE, 
	VALUATION_BASIS VARCHAR2(100 BYTE), 
	COMPANY_NAME VARCHAR2(100 BYTE), 
	PERCENTAGE_OF_NAV NUMBER(25,5), 
	INTEREST_BASIS VARCHAR2(100 BYTE), 
	INDUSTRY VARCHAR2(100 BYTE), 
	SOURCE VARCHAR2(100 BYTE), 
	ISIN_CODE VARCHAR2(100 BYTE), 
	RATING_AGENCY VARCHAR2(100 BYTE), 
	DESC1 VARCHAR2(500 BYTE), 
	DESC2 VARCHAR2(500 BYTE), 
	DESC3 VARCHAR2(500 BYTE), 
	FF_N1 NUMBER(16,2), 
	FF_N2 NUMBER(16,2), 
	FF_N3 NUMBER(16,2), 
	FF_N4 NUMBER(16,2), 
	FF_N5 NUMBER(16,2), 
	FF_VC1 VARCHAR2(500 BYTE), 
	FF_VC2 VARCHAR2(500 BYTE), 
	FF_VC3 VARCHAR2(500 BYTE), 
	FF_VC4 VARCHAR2(500 BYTE), 
	FF_VC5 VARCHAR2(500 BYTE), 
	FF_D1 DATE, 
	FF_D2 DATE, 
	FF_D3 DATE, 
	CR_ID VARCHAR2(50 BYTE), 
	CR_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	UPD_ID VARCHAR2(50 BYTE), 
	UPD_DT TIMESTAMP (6), 
	ACTIVE VARCHAR2(2 BYTE) DEFAULT 'Y', 
	ACTIVATION_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	DEACTIVATION_DT TIMESTAMP (6) DEFAULT '31-DEC-4099 12:00:00 AM'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 57344 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HM_TBS ;
--------------------------------------------------------
--  DDL for Index CT_UK_HFE_POS
--------------------------------------------------------

  CREATE INDEX CT_UK_HFE_POS ON HI_FRONTEND_POSITION (INSURANCE, PORTFOLIO_BASIS, AS_ON_DATE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHINDX_TBS ;
--------------------------------------------------------
--  Constraints for Table HI_FRONTEND_POSITION
--------------------------------------------------------

  ALTER TABLE HI_FRONTEND_POSITION MODIFY (CR_ID NOT NULL ENABLE);
 
  ALTER TABLE HI_FRONTEND_POSITION MODIFY (CR_DT NOT NULL ENABLE);
 
  ALTER TABLE HI_FRONTEND_POSITION MODIFY (ACTIVE NOT NULL ENABLE);
 
  ALTER TABLE HI_FRONTEND_POSITION MODIFY (ACTIVATION_DT NOT NULL ENABLE);
 
  ALTER TABLE HI_FRONTEND_POSITION MODIFY (DEACTIVATION_DT NOT NULL ENABLE);

