--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HI_INDXFUTURE_PREV
--------------------------------------------------------

  CREATE TABLE HI_INDXFUTURE_PREV 
   (	INDXFUTURE VARCHAR2(100 BYTE), 
	RECTYPE VARCHAR2(1 BYTE), 
	CURRNO NUMBER(3,0), 
	NAME VARCHAR2(500 BYTE), 
	ASSET_TYPE VARCHAR2(100 BYTE), 
	STOCK_INDEX VARCHAR2(1 BYTE), 
	BASE_INDEX VARCHAR2(100 BYTE), 
	MULTI_COEFF NUMBER(21,5), 
	SETTLEMENT_MODE VARCHAR2(1 BYTE), 
	INI_MGN NUMBER(21,5), 
	START_DATE DATE, 
	MAT_DATE DATE, 
	UNDERLYING_CODE VARCHAR2(100 BYTE), 
	CONTRACT_CODE VARCHAR2(100 BYTE), 
	COUNTRY VARCHAR2(100 BYTE), 
	CURRENCY VARCHAR2(100 BYTE), 
	INITIAL_MARGIN NUMBER(21,5), 
	MINIMUM_MARGIN NUMBER(21,5), 
	STK_EXCH VARCHAR2(3 BYTE), 
	TICKER VARCHAR2(100 BYTE), 
	LOT_SIZE NUMBER(21,5), 
	UNITS_DEC NUMBER(1,0), 
	RATE_DEC NUMBER(1,0), 
	DERIVATIVE_TYPE VARCHAR2(1 BYTE) DEFAULT 'F', 
	OPTION_TYPE VARCHAR2(1 BYTE) DEFAULT 'N', 
	CALL_PUT VARCHAR2(1 BYTE) DEFAULT 'C', 
	STK_SEC_ID VARCHAR2(100 BYTE), 
	LATEST_INDX NUMBER(21,5), 
	LATEST_INDX_DATE DATE, 
	SYSGEN_Y_N VARCHAR2(1 BYTE), 
	STATUS VARCHAR2(4 BYTE), 
	INP_DT_TM VARCHAR2(16 BYTE), 
	FF_N1 NUMBER(21,5), 
	FF_N2 NUMBER(21,5), 
	FF_N3 NUMBER(21,5), 
	FF_N4 NUMBER(21,5), 
	FF_N5 NUMBER(21,5), 
	FF_VC1 VARCHAR2(500 BYTE), 
	FF_VC2 VARCHAR2(500 BYTE), 
	FF_VC3 VARCHAR2(500 BYTE), 
	FF_VC4 VARCHAR2(500 BYTE), 
	FF_VC5 VARCHAR2(500 BYTE), 
	FF_D1 DATE, 
	FF_D2 DATE, 
	FF_D3 DATE, 
	FF_D4 DATE, 
	FF_D5 DATE, 
	CR_ID VARCHAR2(50 BYTE) DEFAULT 'HAMC', 
	CR_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	UPD_ID VARCHAR2(50 BYTE), 
	UPD_DT TIMESTAMP (6), 
	PROCESSED_DT DATE, 
	PROCESSED_STATUS VARCHAR2(2 BYTE) DEFAULT 'U', 
	ACTIVE VARCHAR2(2 BYTE) DEFAULT 'Y', 
	ACTIVATION_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	DEACTIVATION_DT TIMESTAMP (6) DEFAULT '31-DEC-4099 12:00:00 AM'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHI_TBS ;
--------------------------------------------------------
--  DDL for Index CT_HI_IFUTURE_PREV
--------------------------------------------------------

  CREATE UNIQUE INDEX CT_HI_IFUTURE_PREV ON HI_INDXFUTURE_PREV (INDXFUTURE, RECTYPE, CURRNO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHI_TBS ;
--------------------------------------------------------
--  Constraints for Table HI_INDXFUTURE_PREV
--------------------------------------------------------

  ALTER TABLE HI_INDXFUTURE_PREV MODIFY (INDXFUTURE NOT NULL ENABLE);
 
  ALTER TABLE HI_INDXFUTURE_PREV MODIFY (RECTYPE NOT NULL ENABLE);
 
  ALTER TABLE HI_INDXFUTURE_PREV MODIFY (CURRNO NOT NULL ENABLE);
 
  ALTER TABLE HI_INDXFUTURE_PREV MODIFY (STOCK_INDEX NOT NULL ENABLE);
 
  ALTER TABLE HI_INDXFUTURE_PREV MODIFY (COUNTRY NOT NULL ENABLE);
 
  ALTER TABLE HI_INDXFUTURE_PREV MODIFY (CURRENCY NOT NULL ENABLE);

