--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HI_INTERSCHEME_PREV
--------------------------------------------------------

  CREATE TABLE HI_INTERSCHEME_PREV 
   (	AMC_CODE VARCHAR2(12 BYTE), 
	DEAL_ID VARCHAR2(17 BYTE), 
	RECTYPE VARCHAR2(1 BYTE), 
	CURRNO NUMBER(5,0), 
	SCHEME VARCHAR2(12 BYTE), 
	SCHEME_N VARCHAR2(12 BYTE), 
	INVEST_TYPE VARCHAR2(6 BYTE), 
	INVEST_TYPE_N VARCHAR2(6 BYTE), 
	CUSTODIAN VARCHAR2(12 BYTE), 
	SECURITY VARCHAR2(14 BYTE), 
	VALUE_DATE DATE, 
	TRAN_TYPE VARCHAR2(6 BYTE), 
	TRAN_TYPE_N VARCHAR2(6 BYTE), 
	UNITS NUMBER(20,4), 
	RATE NUMBER(16,8), 
	YTM NUMBER(14,8) DEFAULT 0, 
	DEL_DATE DATE, 
	FCY_GROSS_INT NUMBER(14,3), 
	GROSS_INT NUMBER(14,3), 
	GROSS_INT_N NUMBER(14,3), 
	NOOFDAYS NUMBER(5,0), 
	NETT_VAL NUMBER(18,3), 
	FCY_ACQU_COST_P NUMBER(18,3), 
	ACQU_COST_P NUMBER(18,3), 
	FCY_ACQU_COST_S NUMBER(18,3), 
	ACQU_COST_S NUMBER(18,3), 
	REMARKS_SELL VARCHAR2(50 BYTE), 
	REMARKS VARCHAR2(50 BYTE), 
	DEAL_SLIP_NO VARCHAR2(14 BYTE), 
	FCY_PRFT_LOSS NUMBER(18,3), 
	FCY_ACCR_INT_P NUMBER(14,3), 
	ACCR_INT_P NUMBER(14,3), 
	FCY_ACCR_INT_S NUMBER(14,3), 
	ACCR_INT_S NUMBER(14,3), 
	FCY_PREMDISC_AMT NUMBER(14,3), 
	PREMDISC_AMT NUMBER(14,3), 
	FCY_PREMDISC_ACCR NUMBER(14,3), 
	PREMDISC_ACCR NUMBER(14,3), 
	FCY_PREMDISC_ACCR_N NUMBER(14,3) DEFAULT 0, 
	PREMDISC_ACCR_N NUMBER(14,3), 
	SECURITY_N VARCHAR2(14 BYTE), 
	ASSET_TYPE VARCHAR2(6 BYTE), 
	YTM_RATE VARCHAR2(1 BYTE), 
	NEW_SHARES NUMBER(20,4), 
	NPP_DIVIDEND NUMBER(14,3), 
	FROM_TO_MMPOOL VARCHAR2(1 BYTE), 
	PHYSICAL_SGL VARCHAR2(1 BYTE), 
	STAMP NUMBER(14,3), 
	ACCOUNT VARCHAR2(30 BYTE), 
	ACCOUNT_N VARCHAR2(30 BYTE), 
	CUSTODIAN_N VARCHAR2(12 BYTE), 
	CUST_REFER VARCHAR2(14 BYTE), 
	CUST_REFER_N VARCHAR2(14 BYTE), 
	CUSTCHRG NUMBER(14,3), 
	CUSTCHRG_N NUMBER(14,3), 
	CURRENCY VARCHAR2(3 BYTE), 
	EXCH_RATE NUMBER(18,10), 
	FCY_NETT_VAL NUMBER(14,3), 
	FCY_CUSTCHRG NUMBER(14,3), 
	FCY_CUSTCHRG_N NUMBER(14,3), 
	TARIFF_CCY_FROM VARCHAR2(3 BYTE), 
	TARIFF_EXCH_RATE_FROM NUMBER(18,10), 
	TARIFF_CCY_TO VARCHAR2(3 BYTE), 
	TARIFF_EXCH_RATE_TO NUMBER(18,10), 
	FCY_STAMP NUMBER(14,3), 
	INT_ACCRUED NUMBER(16,3), 
	FCY_INT_ACCRUED NUMBER(16,3), 
	ADV_INT NUMBER(18,3) DEFAULT 0, 
	FCY_ADV_INT NUMBER(18,3) DEFAULT 0, 
	RIGHTS_COST NUMBER(18,3) DEFAULT 0, 
	FCY_RIGHTS_COST NUMBER(14,3) DEFAULT 0, 
	TRANS_COST_P NUMBER(18,3), 
	TRANS_COST_S NUMBER(18,3), 
	EXCH_RATE_N NUMBER(18,10), 
	PRFT_LOSS NUMBER(18,3), 
	FCY_INT_TAX NUMBER(14,3) DEFAULT 0, 
	INT_TAX NUMBER(14,3) DEFAULT 0, 
	FCY_INT_TAX_N NUMBER(14,3) DEFAULT 0, 
	INT_TAX_N NUMBER(14,3) DEFAULT 0, 
	FCY_GROSS_INT_TAX NUMBER(14,3) DEFAULT 0, 
	GROSS_INT_TAX NUMBER(14,3) DEFAULT 0, 
	FCY_GROSS_INT_TAX_N NUMBER(14,3) DEFAULT 0, 
	GROSS_INT_TAX_N NUMBER(14,3) DEFAULT 0, 
	PRFT_LOSS_N NUMBER(18,3), 
	NETT_VAL_N NUMBER(18,3), 
	STAMP_N NUMBER(14,3), 
	INT_ACCRUED_N NUMBER(16,3), 
	CURR_YIELD NUMBER(16,8) DEFAULT 0, 
	FCY_INJ_COST_N NUMBER(18,3) DEFAULT 0, 
	INJ_COST_N NUMBER(18,3) DEFAULT 0, 
	FCY_INJ_COST NUMBER(18,3) DEFAULT 0, 
	INJ_COST NUMBER(18,3) DEFAULT 0, 
	FCY_INJ_PRFTLOSS NUMBER(18,3) DEFAULT 0, 
	INJ_PRFTLOSS NUMBER(18,3) DEFAULT 0, 
	FCY_INT_RECBLE NUMBER(18,3), 
	INT_RECBLE NUMBER(18,3), 
	FCY_INT_RECBLE_N NUMBER(18,3), 
	INT_RECBLE_N NUMBER(18,3), 
	PUR_VALUE_REVAL NUMBER(18,3), 
	ACCR_INT_REVAL NUMBER(18,3), 
	PREMDISC_AMT_REVAL NUMBER(18,3), 
	LST_ENTRY NUMBER(2,0), 
	LST_ENTRY_N NUMBER(2,0), 
	APP_REFER VARCHAR2(17 BYTE), 
	APP_REFER_N VARCHAR2(17 BYTE), 
	ADV_INT_N NUMBER(14,3), 
	FCY_PURCH_INT NUMBER(14,3), 
	PURCH_INT NUMBER(14,3), 
	PURCH_INT_N NUMBER(14,3), 
	FCY_UNREL_AMT NUMBER(14,3) DEFAULT 0, 
	UNREL_AMT NUMBER(14,3) DEFAULT 0, 
	BOOK_DATE DATE, 
	TRF_TYPE VARCHAR2(1 BYTE) DEFAULT 'M', 
	MKT_PRICE NUMBER(18,6) DEFAULT 0, 
	COST_AOD NUMBER(24,10) DEFAULT 0, 
	STATUS VARCHAR2(4 BYTE), 
	INPUTTER VARCHAR2(9 BYTE), 
	INP_DT_TM VARCHAR2(16 BYTE), 
	AUTHORISER VARCHAR2(9 BYTE), 
	FF_N1 NUMBER(16,2), 
	FF_N2 NUMBER(16,2), 
	FF_N3 NUMBER(16,2), 
	FF_N4 NUMBER(16,2), 
	FF_N5 NUMBER(16,2), 
	FF_VC1 VARCHAR2(500 BYTE), 
	FF_VC2 VARCHAR2(500 BYTE), 
	FF_VC3 VARCHAR2(500 BYTE), 
	FF_VC4 VARCHAR2(500 BYTE), 
	FF_VC5 VARCHAR2(500 BYTE), 
	FF_D1 DATE, 
	FF_D2 DATE, 
	FF_D3 DATE, 
	FF_D4 DATE, 
	FF_D5 DATE, 
	CR_ID VARCHAR2(50 BYTE) DEFAULT 'ADMIN', 
	CR_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	UPD_ID VARCHAR2(50 BYTE), 
	UPD_DT TIMESTAMP (6), 
	PROCESSED_DT DATE, 
	PROCESSED_STATUS VARCHAR2(2 BYTE) DEFAULT 'U', 
	ACTIVE VARCHAR2(2 BYTE) DEFAULT 'Y', 
	ACTIVATION_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	DEACTIVATION_DT TIMESTAMP (6) DEFAULT '31-DEC-4099 12:00:00 AM'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHI_TBS ;
--------------------------------------------------------
--  Constraints for Table HI_INTERSCHEME_PREV
--------------------------------------------------------

  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (AMC_CODE NOT NULL ENABLE);
 
  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (DEAL_ID NOT NULL ENABLE);
 
  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (RECTYPE NOT NULL ENABLE);
 
  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (CURRNO NOT NULL ENABLE);
 
  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (SCHEME NOT NULL ENABLE);
 
  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (SCHEME_N NOT NULL ENABLE);
 
  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (INVEST_TYPE NOT NULL ENABLE);
 
  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (INVEST_TYPE_N NOT NULL ENABLE);
 
  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (CUSTODIAN NOT NULL ENABLE);
 
  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (SECURITY NOT NULL ENABLE);
 
  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (VALUE_DATE NOT NULL ENABLE);
 
  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (TRAN_TYPE NOT NULL ENABLE);
 
  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (TRAN_TYPE_N NOT NULL ENABLE);
 
  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (UNITS NOT NULL ENABLE);
 
  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (RATE NOT NULL ENABLE);
 
  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (GROSS_INT NOT NULL ENABLE);
 
  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (GROSS_INT_N NOT NULL ENABLE);
 
  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (NOOFDAYS NOT NULL ENABLE);
 
  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (NETT_VAL NOT NULL ENABLE);
 
  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (ACQU_COST_P NOT NULL ENABLE);
 
  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (ACQU_COST_S NOT NULL ENABLE);
 
  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (ASSET_TYPE NOT NULL ENABLE);
 
  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (CURRENCY NOT NULL ENABLE);
 
  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (NETT_VAL_N NOT NULL ENABLE);
 
  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (INPUTTER NOT NULL ENABLE);
 
  ALTER TABLE HI_INTERSCHEME_PREV MODIFY (INP_DT_TM NOT NULL ENABLE);

