--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HI_NET_INCOME_LIVE
--------------------------------------------------------

  CREATE TABLE HI_NET_INCOME_LIVE 
   (	AMC_CODE VARCHAR2(50 BYTE), 
	SCHEME VARCHAR2(100 BYTE), 
	ACCOUNT_CODE VARCHAR2(100 BYTE), 
	LEVEL_2 VARCHAR2(100 BYTE), 
	VALUE_DATE DATE, 
	NET_INCOME NUMBER(21,5), 
	CURRENCY VARCHAR2(3 BYTE), 
	EXCH_RATE NUMBER(18,10), 
	FCY_AMOUNT NUMBER(21,5), 
	BOOK_DATE DATE, 
	TRAN_TYPE VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHI_TBS ;


