--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HI_REPO_DEAL_PREV
--------------------------------------------------------

  CREATE TABLE HI_REPO_DEAL_PREV 
   (	AMC_CODE VARCHAR2(100 BYTE), 
	DEAL_ID VARCHAR2(100 BYTE), 
	RECTYPE VARCHAR2(1 BYTE), 
	CURRNO NUMBER(5,0), 
	APP_REFER VARCHAR2(100 BYTE), 
	CURRENCY VARCHAR2(3 BYTE), 
	EXCH_RATE NUMBER(21,10), 
	SCHEME VARCHAR2(100 BYTE), 
	ASSET_TYPE VARCHAR2(100 BYTE), 
	SECURITY VARCHAR2(100 BYTE), 
	INVEST_TYPE VARCHAR2(100 BYTE), 
	CUSTODIAN VARCHAR2(100 BYTE), 
	CUSTODIAN_N VARCHAR2(100 BYTE), 
	CPARTY_ID VARCHAR2(100 BYTE), 
	DEAL_STAT VARCHAR2(100 BYTE), 
	VALUE_DATE DATE, 
	MAT_DATE DATE, 
	TRAN_TYPE VARCHAR2(10 BYTE), 
	DEAL_TYPE VARCHAR2(1 BYTE), 
	DEALER VARCHAR2(100 BYTE), 
	DEAL_SLIP_NO VARCHAR2(100 BYTE), 
	UNITS NUMBER(21,5), 
	HAIRCUT_RATE NUMBER(21,8), 
	RATE NUMBER(21,8), 
	FCY_GROSS_INT NUMBER(21,5), 
	GROSS_INT NUMBER(21,5), 
	INT_TAX NUMBER(21,5), 
	FCY_INT_TAX NUMBER(21,5), 
	FCY_INT_RECBLE NUMBER(21,5), 
	INT_RECBLE NUMBER(21,5), 
	BROKER VARCHAR2(100 BYTE), 
	BROKER_CCY VARCHAR2(100 BYTE), 
	BRK_EXCH_RATE NUMBER(21,10), 
	FCY_BRK_COMMN NUMBER(21,5) DEFAULT 0, 
	NETT_VAL NUMBER(21,5), 
	FCY_NETT_VAL NUMBER(21,5), 
	FCY_AMT_RECVD NUMBER(21,5), 
	AMT_RECVD NUMBER(21,5), 
	REPO_RATE NUMBER(21,5), 
	NOOFDAYS NUMBER(5,0), 
	TERM NUMBER(5,0), 
	FCY_ACCR_INT NUMBER(21,5), 
	ACCR_INT NUMBER(21,5), 
	BOOK_DATE DATE, 
	ACCOUNT VARCHAR2(100 BYTE), 
	INSTR_TYPE VARCHAR2(1 BYTE) DEFAULT 'C', 
	CHQ_NUMBER VARCHAR2(100 BYTE), 
	CHQ_DATE DATE, 
	REMARKS VARCHAR2(500 BYTE), 
	ZONE VARCHAR2(100 BYTE), 
	FCY_INT_RECVD NUMBER(21,5) DEFAULT 0, 
	REPO_ASSET_TYPE VARCHAR2(100 BYTE), 
	CUM_INT VARCHAR2(1 BYTE) DEFAULT 'N', 
	TARIFF_CCY VARCHAR2(100 BYTE), 
	TARIFF_EXCH_RATE NUMBER(21,10), 
	FCY_CUSTCHRG NUMBER(21,5) DEFAULT 0, 
	CUSTCHRG NUMBER(21,5) DEFAULT 0, 
	TRADE_DATE DATE, 
	APP_REFER1 VARCHAR2(100 BYTE), 
	INT_DAY VARCHAR2(1 BYTE), 
	INT_TYPE VARCHAR2(1 BYTE) DEFAULT 'F', 
	INTEREST_KEY VARCHAR2(100 BYTE), 
	MARGIN NUMBER(21,6) DEFAULT 0, 
	FLOOR NUMBER(21,6) DEFAULT 0, 
	CAP NUMBER(21,6) DEFAULT 0, 
	RESET_FREQ VARCHAR2(100 BYTE), 
	CMPD_Y_N VARCHAR2(1 BYTE) DEFAULT 'N', 
	CMPD_FREQ VARCHAR2(100 BYTE), 
	COMP_TYPE VARCHAR2(1 BYTE), 
	TAX_RATE NUMBER(21,5) DEFAULT 0, 
	ACCR_INT_REVAL NUMBER(21,5) DEFAULT 0, 
	AMOUNT_REVAL NUMBER(21,5) DEFAULT 0, 
	FCY_CLEARING_FEE NUMBER(21,5) DEFAULT 0, 
	FCY_CLEARING_FEE_MAT NUMBER(21,5) DEFAULT 0, 
	CLEARING_FEE NUMBER(21,5) DEFAULT 0, 
	CLEARING_FEE_MAT NUMBER(21,5) DEFAULT 0, 
	ALLOCATE_YN VARCHAR2(1 BYTE) DEFAULT 'N', 
	SYSGEN_Y_N VARCHAR2(1 BYTE) DEFAULT 'N', 
	LST_ENTRY NUMBER(5,0), 
	STATUS VARCHAR2(4 BYTE), 
	INP_DT_TM VARCHAR2(16 BYTE), 
	FF_N1 NUMBER(16,2), 
	FF_N2 NUMBER(16,2), 
	FF_N3 NUMBER(16,2), 
	FF_N4 NUMBER(16,2), 
	FF_N5 NUMBER(16,2), 
	FF_VC1 VARCHAR2(500 BYTE), 
	FF_VC2 VARCHAR2(500 BYTE), 
	FF_VC3 VARCHAR2(500 BYTE), 
	FF_VC4 VARCHAR2(500 BYTE), 
	FF_VC5 VARCHAR2(500 BYTE), 
	FF_D1 DATE, 
	FF_D2 DATE, 
	FF_D3 DATE, 
	CR_ID VARCHAR2(50 BYTE), 
	CR_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	UPD_ID VARCHAR2(50 BYTE), 
	UPD_DT TIMESTAMP (6), 
	ACTIVE VARCHAR2(2 BYTE) DEFAULT 'Y', 
	ACTIVATION_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	DEACTIVATION_DT TIMESTAMP (6) DEFAULT '31-DEC-4099 12:00:00 AM'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 57344 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHI_TBS ;
--------------------------------------------------------
--  DDL for Index CT_UK_HIREPO_DEAL_PREV
--------------------------------------------------------

  CREATE INDEX CT_UK_HIREPO_DEAL_PREV ON HI_REPO_DEAL_PREV (AMC_CODE, SCHEME, INVEST_TYPE, CUSTODIAN, SECURITY, CPARTY_ID, VALUE_DATE, MAT_DATE, RECTYPE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHINDX_TBS ;
--------------------------------------------------------
--  Constraints for Table HI_REPO_DEAL_PREV
--------------------------------------------------------

  ALTER TABLE HI_REPO_DEAL_PREV MODIFY (AMC_CODE NOT NULL ENABLE);
 
  ALTER TABLE HI_REPO_DEAL_PREV MODIFY (DEAL_ID NOT NULL ENABLE);
 
  ALTER TABLE HI_REPO_DEAL_PREV MODIFY (RECTYPE NOT NULL ENABLE);
 
  ALTER TABLE HI_REPO_DEAL_PREV MODIFY (CURRNO NOT NULL ENABLE);
 
  ALTER TABLE HI_REPO_DEAL_PREV MODIFY (CURRENCY NOT NULL ENABLE);
 
  ALTER TABLE HI_REPO_DEAL_PREV MODIFY (EXCH_RATE NOT NULL ENABLE);
 
  ALTER TABLE HI_REPO_DEAL_PREV MODIFY (TARIFF_CCY NOT NULL ENABLE);
 
  ALTER TABLE HI_REPO_DEAL_PREV MODIFY (TARIFF_EXCH_RATE NOT NULL ENABLE);
 
  ALTER TABLE HI_REPO_DEAL_PREV MODIFY (CR_ID NOT NULL ENABLE);
 
  ALTER TABLE HI_REPO_DEAL_PREV MODIFY (CR_DT NOT NULL ENABLE);
 
  ALTER TABLE HI_REPO_DEAL_PREV MODIFY (ACTIVE NOT NULL ENABLE);
 
  ALTER TABLE HI_REPO_DEAL_PREV MODIFY (ACTIVATION_DT NOT NULL ENABLE);
 
  ALTER TABLE HI_REPO_DEAL_PREV MODIFY (DEACTIVATION_DT NOT NULL ENABLE);

