--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HI_REPSAL_CURR
--------------------------------------------------------

  CREATE TABLE HI_REPSAL_CURR 
   (	AMC_CODE VARCHAR2(100 BYTE), 
	DEAL_ID VARCHAR2(100 BYTE), 
	RECTYPE VARCHAR2(1 BYTE), 
	CURRNO NUMBER(5,0), 
	SCHEME VARCHAR2(100 BYTE), 
	SCHCLASS VARCHAR2(100 BYTE), 
	SCH_AMC VARCHAR2(1 BYTE), 
	CENTRE VARCHAR2(100 BYTE), 
	TRAN_TYPE VARCHAR2(100 BYTE), 
	UNITS NUMBER(21,5), 
	AMOUNT NUMBER(21,5), 
	FCY_AMOUNT NUMBER(21,5), 
	LOADAMOUNT NUMBER(21,5), 
	ACQU_COST NUMBER(21,5), 
	VALUE_DATE DATE, 
	RATE NUMBER(21,8), 
	ACCOUNT VARCHAR2(100 BYTE), 
	PRFT_LOSS NUMBER(21,5), 
	DIVEQU_AMT NUMBER(21,5), 
	EXCH_RATE NUMBER(21,10), 
	CURRENCY VARCHAR2(100 BYTE), 
	CQ_ID VARCHAR2(100 BYTE), 
	REMARKS VARCHAR2(500 BYTE), 
	BANK_CHARGES NUMBER(21,5), 
	APP_REFER VARCHAR2(100 BYTE), 
	TDS_AMOUNT NUMBER(21,5), 
	STT_AMOUNT NUMBER(21,5), 
	REDEMPTION_FEE NUMBER(21,5), 
	ACC_CURRENCY VARCHAR2(100 BYTE), 
	ACC_EXCH_RATE NUMBER(21,10), 
	FCY_ACC_AMOUNT NUMBER(21,5), 
	ACC_AMOUNT NUMBER(21,5), 
	TRADE_DATE DATE, 
	PAYMENT_DATE DATE, 
	UNITS_OUTS NUMBER(21,5), 
	DIV_GROSS_RATE NUMBER(21,10) DEFAULT 0, 
	DIV_NET_RATE NUMBER(21,10) DEFAULT 0, 
	BONUS_ADD_UNITS NUMBER(21,5) DEFAULT 0, 
	BONUS_CURR_UNITS NUMBER(21,5) DEFAULT 0, 
	INSTR_TYPE VARCHAR2(1 BYTE) DEFAULT 'C', 
	CHQ_NUMBER VARCHAR2(100 BYTE), 
	CHQ_DATE DATE, 
	BOOK_DATE DATE, 
	LST_ENTRY NUMBER(5,0), 
	SYSGEN_Y_N VARCHAR2(1 BYTE), 
	STATUS VARCHAR2(4 BYTE), 
	INP_DT_TM VARCHAR2(16 BYTE), 
	DESC1 VARCHAR2(500 BYTE), 
	DESC2 VARCHAR2(500 BYTE), 
	DESC3 VARCHAR2(500 BYTE), 
	FF_N1 NUMBER(21,5), 
	FF_N2 NUMBER(21,5), 
	FF_N3 NUMBER(21,5), 
	FF_N4 NUMBER(21,5), 
	FF_N5 NUMBER(21,5), 
	FF_VC1 VARCHAR2(500 BYTE), 
	FF_VC2 VARCHAR2(500 BYTE), 
	FF_VC3 VARCHAR2(500 BYTE), 
	FF_VC4 VARCHAR2(500 BYTE), 
	FF_VC5 VARCHAR2(500 BYTE), 
	FF_D1 DATE, 
	FF_D2 DATE, 
	FF_D3 DATE, 
	FF_D4 DATE, 
	FF_D5 DATE, 
	CR_ID VARCHAR2(50 BYTE) DEFAULT 'HAMC', 
	CR_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	UPD_ID VARCHAR2(50 BYTE), 
	UPD_DT TIMESTAMP (6), 
	ACTIVE VARCHAR2(2 BYTE) DEFAULT 'Y', 
	ACTIVATION_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	DEACTIVATION_DT TIMESTAMP (6) DEFAULT '31-DEC-4099 12:00:00 AM'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHI_TBS ;
--------------------------------------------------------
--  DDL for Index CT_HI_REPSAL_CURR
--------------------------------------------------------

  CREATE INDEX CT_HI_REPSAL_CURR ON HI_REPSAL_CURR (AMC_CODE, SCHEME, SCHCLASS, SCH_AMC, TRAN_TYPE, VALUE_DATE, RECTYPE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHINDX_TBS ;
--------------------------------------------------------
--  Constraints for Table HI_REPSAL_CURR
--------------------------------------------------------

  ALTER TABLE HI_REPSAL_CURR MODIFY (AMC_CODE NOT NULL ENABLE);
 
  ALTER TABLE HI_REPSAL_CURR MODIFY (DEAL_ID NOT NULL ENABLE);
 
  ALTER TABLE HI_REPSAL_CURR MODIFY (RECTYPE NOT NULL ENABLE);
 
  ALTER TABLE HI_REPSAL_CURR MODIFY (CURRNO NOT NULL ENABLE);
 
  ALTER TABLE HI_REPSAL_CURR MODIFY (SCHEME NOT NULL ENABLE);
 
  ALTER TABLE HI_REPSAL_CURR MODIFY (TRAN_TYPE NOT NULL ENABLE);
 
  ALTER TABLE HI_REPSAL_CURR MODIFY (UNITS NOT NULL ENABLE);
 
  ALTER TABLE HI_REPSAL_CURR MODIFY (AMOUNT NOT NULL ENABLE);
 
  ALTER TABLE HI_REPSAL_CURR MODIFY (LOADAMOUNT NOT NULL ENABLE);
 
  ALTER TABLE HI_REPSAL_CURR MODIFY (INP_DT_TM NOT NULL ENABLE);
 
  ALTER TABLE HI_REPSAL_CURR MODIFY (CR_ID NOT NULL ENABLE);
 
  ALTER TABLE HI_REPSAL_CURR MODIFY (CR_DT NOT NULL ENABLE);
 
  ALTER TABLE HI_REPSAL_CURR MODIFY (ACTIVE NOT NULL ENABLE);
 
  ALTER TABLE HI_REPSAL_CURR MODIFY (ACTIVATION_DT NOT NULL ENABLE);
 
  ALTER TABLE HI_REPSAL_CURR MODIFY (DEACTIVATION_DT NOT NULL ENABLE);

