--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HM_ACCOUNT
--------------------------------------------------------

  CREATE TABLE HM_ACCOUNT 
   (	AMC_CODE VARCHAR2(100 BYTE), 
	SCHEME VARCHAR2(100 BYTE), 
	LEVEL_1 VARCHAR2(100 BYTE), 
	LEVEL_2 VARCHAR2(100 BYTE), 
	LEVEL_3 VARCHAR2(100 BYTE), 
	NAME VARCHAR2(100 BYTE), 
	CTRL_ATYPE VARCHAR2(1 BYTE), 
	IE_BS_TYPE VARCHAR2(1 BYTE), 
	STATUS VARCHAR2(4 BYTE), 
	INP_DT_TM VARCHAR2(16 BYTE), 
	DESC1 VARCHAR2(500 BYTE), 
	DESC2 VARCHAR2(500 BYTE), 
	DESC3 VARCHAR2(500 BYTE), 
	FF_N1 NUMBER(16,2), 
	FF_N2 NUMBER(16,2), 
	FF_N3 NUMBER(16,2), 
	FF_VC1 VARCHAR2(500 BYTE), 
	FF_VC2 VARCHAR2(500 BYTE), 
	FF_VC3 VARCHAR2(500 BYTE), 
	FF_VC4 VARCHAR2(500 BYTE), 
	FF_VC5 VARCHAR2(500 BYTE), 
	FF_D1 DATE, 
	FF_D2 DATE, 
	FF_D3 DATE, 
	CR_ID VARCHAR2(50 BYTE), 
	CR_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	UPD_ID VARCHAR2(50 BYTE), 
	UPD_DT TIMESTAMP (6), 
	ACTIVE VARCHAR2(2 BYTE) DEFAULT 'Y', 
	ACTIVATION_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	DEACTIVATION_DT TIMESTAMP (6) DEFAULT '31-DEC-4099 12:00:00 AM'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 57344 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HM_TBS ;
--------------------------------------------------------
--  DDL for Index CT_PK_HA
--------------------------------------------------------

  CREATE INDEX CT_PK_HA ON HM_ACCOUNT (LEVEL_1, SCHEME, LEVEL_2) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHINDX_TBS ;
--------------------------------------------------------
--  Constraints for Table HM_ACCOUNT
--------------------------------------------------------

  ALTER TABLE HM_ACCOUNT MODIFY (CR_ID NOT NULL ENABLE);
 
  ALTER TABLE HM_ACCOUNT MODIFY (CR_DT NOT NULL ENABLE);
 
  ALTER TABLE HM_ACCOUNT MODIFY (ACTIVE NOT NULL ENABLE);
 
  ALTER TABLE HM_ACCOUNT MODIFY (ACTIVATION_DT NOT NULL ENABLE);
 
  ALTER TABLE HM_ACCOUNT MODIFY (DEACTIVATION_DT NOT NULL ENABLE);

