--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HM_DEAL
--------------------------------------------------------

  CREATE TABLE HM_DEAL 
   (	AMC_CODE VARCHAR2(100 BYTE), 
	DEAL_ID VARCHAR2(100 BYTE), 
	RECTYPE VARCHAR2(1 BYTE), 
	CURRNO NUMBER(5,0), 
	SCHEME VARCHAR2(100 BYTE), 
	SECURITY VARCHAR2(100 BYTE), 
	INVEST_TYPE VARCHAR2(100 BYTE), 
	CUSTODIAN VARCHAR2(500 BYTE), 
	CUSTODIAN_N VARCHAR2(12 BYTE), 
	TRAN_TYPE VARCHAR2(6 BYTE), 
	VALUE_DATE DATE, 
	BOOK_DATE DATE, 
	UNITS NUMBER(20,4), 
	RATE NUMBER(24,10), 
	ASSET_TYPE VARCHAR2(6 BYTE), 
	GROSS_INT NUMBER(18,3), 
	FCY_INT_TAX NUMBER(14,3), 
	INT_TAX NUMBER(14,3) DEFAULT 0, 
	FEES NUMBER(18,6), 
	NET_RATE NUMBER(24,10), 
	BRK_COMMN NUMBER(18,3), 
	FCY_BRK_COMMN NUMBER(18,3), 
	NETT_VAL NUMBER(18,3), 
	ACQU_COST NUMBER(18,3), 
	REPO_RATE NUMBER(24,10), 
	NOOFDAYS NUMBER(5,0), 
	ACCR_INT NUMBER(18,3), 
	TRADE_DATE DATE, 
	APP_REFER VARCHAR2(17 BYTE), 
	CUST_REFER VARCHAR2(16 BYTE), 
	BROKER VARCHAR2(12 BYTE), 
	BROKER_REF VARCHAR2(16 BYTE), 
	CPARTY_ID VARCHAR2(12 BYTE), 
	DEALER VARCHAR2(9 BYTE), 
	STK_EXCH VARCHAR2(3 BYTE), 
	CUM_INT VARCHAR2(1 BYTE), 
	ACCOUNT VARCHAR2(30 BYTE), 
	STAMP NUMBER(14,3), 
	REMARKS VARCHAR2(50 BYTE), 
	DEL_TYPE VARCHAR2(3 BYTE), 
	EX_BEN VARCHAR2(4 BYTE), 
	CUSTCHRG NUMBER(14,3), 
	NET_TRADE VARCHAR2(1 BYTE), 
	PROCESS_TYPE VARCHAR2(1 BYTE), 
	CUM_BEN VARCHAR2(4 BYTE), 
	PRFT_LOSS NUMBER(18,3), 
	FCY_INT_AMT NUMBER(18,3) DEFAULT 0, 
	INT_AMT NUMBER(14,3), 
	DEL_DATE DATE, 
	STOCK_DEL_DATE DATE, 
	TDS NUMBER(14,3), 
	ZONE VARCHAR2(6 BYTE), 
	SERVICE_TAX NUMBER(14,3), 
	DIPDIS_SENT VARCHAR2(1 BYTE), 
	DIPDIS_REV_SENT VARCHAR2(1 BYTE), 
	PRICE_CHK_YN VARCHAR2(1 BYTE), 
	SELLER_PAYS_STAMP VARCHAR2(1 BYTE), 
	REVERSED_DEAL_ID VARCHAR2(17 BYTE), 
	PRINT_DIPDIS_YN VARCHAR2(1 BYTE), 
	PRINT_DELORD_YN VARCHAR2(1 BYTE), 
	SECURITY_N VARCHAR2(14 BYTE), 
	FCY_PREMDISC_AMT NUMBER(14,3), 
	FCY_PREMDISC_ACCR NUMBER(14,3), 
	YTM NUMBER(20,10) DEFAULT 0, 
	PHYSICAL_SGL VARCHAR2(1 BYTE), 
	ALLOCATE_YN VARCHAR2(1 BYTE), 
	DEAL_SLIP_NO VARCHAR2(14 BYTE), 
	SYSGEN_Y_N VARCHAR2(1 BYTE), 
	SERVICE_TAX_FEES NUMBER(10,6), 
	PRIME_SEC VARCHAR2(1 BYTE), 
	ALLOC_DEAL_ID VARCHAR2(17 BYTE), 
	BEN_UNITS NUMBER(20,4), 
	BEN_SECURITY VARCHAR2(14 BYTE), 
	INSTR_TYPE VARCHAR2(1 BYTE) DEFAULT 'C', 
	CHQ_NUMBER VARCHAR2(15 BYTE), 
	CHQ_DATE DATE, 
	NEW_SHARES NUMBER(20,4), 
	SEGMENT VARCHAR2(3 BYTE), 
	FCY_GROSS_INT NUMBER(18,3), 
	FCY_CUSTCHRG NUMBER(14,3), 
	FCY_STAMP NUMBER(14,3), 
	FCY_NETT_VAL NUMBER(18,3), 
	FCY_ACQU_COST NUMBER(18,3), 
	FCY_ACCR_INT NUMBER(18,3), 
	CURRENCY VARCHAR2(3 BYTE), 
	ACC_CURRENCY VARCHAR2(3 BYTE), 
	TARIFF_CCY VARCHAR2(3 BYTE), 
	EXCH_RATE NUMBER(18,10), 
	SET_EXCH_RATE NUMBER(18,10), 
	ACC_EXCH_RATE NUMBER(18,10), 
	TARIFF_EXCH_RATE NUMBER(18,10), 
	FCY_PRFT_LOSS NUMBER(18,3), 
	INT_ACCRUED NUMBER(14,3) DEFAULT 0, 
	FCY_INT_ACCRUED NUMBER(14,3) DEFAULT 0, 
	CLEARING_FEE NUMBER(14,3) DEFAULT 0, 
	FCY_CLEARING_FEE NUMBER(14,3) DEFAULT 0, 
	SETTLEMENT_FEE NUMBER(14,3) DEFAULT 0, 
	TRANSACTION_LEVY NUMBER(14,3) DEFAULT 0, 
	ACQU_COST_ORG NUMBER(18,3) DEFAULT 0, 
	FCY_ACQU_COST_ORG NUMBER(18,3) DEFAULT 0, 
	TRANS_COST NUMBER(18,3) DEFAULT 0, 
	ACC_AMOUNT NUMBER(18,3) DEFAULT 0, 
	FCY_ACC_AMOUNT NUMBER(18,3) DEFAULT 0, 
	CURR_YIELD NUMBER(16,8) DEFAULT 0, 
	PREMDISC_AMT NUMBER(14,3) DEFAULT 0, 
	PREMDISC_ACCR NUMBER(14,3) DEFAULT 0, 
	FCY_GROSS_INT_TAX NUMBER(14,3) DEFAULT 0, 
	GROSS_INT_TAX NUMBER(14,3) DEFAULT 0, 
	UNITS_UTILISED NUMBER(20,4) DEFAULT 0, 
	FCY_ACQU_COST_UTIL NUMBER(18,3) DEFAULT 0, 
	ACQU_COST_UTIL NUMBER(18,3) DEFAULT 0, 
	SELF_UTILISED NUMBER(20,4) DEFAULT 0, 
	FCY_INJ_COST NUMBER(18,3) DEFAULT 0, 
	INJ_COST NUMBER(18,3) DEFAULT 0, 
	FCY_INJ_PRFTLOSS NUMBER(18,3) DEFAULT 0, 
	INJ_PRFTLOSS NUMBER(18,3) DEFAULT 0, 
	FCY_INT_RECBLE NUMBER(18,3), 
	INT_RECBLE NUMBER(18,3), 
	ADV_INT NUMBER(14,3) DEFAULT 0, 
	FCY_ADV_INT NUMBER(18,3) DEFAULT 0, 
	RIGHTS_COST NUMBER(18,3) DEFAULT 0, 
	FCY_RIGHTS_COST NUMBER(14,3) DEFAULT 0, 
	PUR_VALUE_REVAL NUMBER(18,3), 
	ACCR_INT_REVAL NUMBER(18,3), 
	PREMDISC_AMT_REVAL NUMBER(18,3), 
	LST_ENTRY NUMBER(2,0), 
	FCY_PURCH_INT NUMBER(18,3), 
	PURCH_INT NUMBER(18,3), 
	STP_STATUS VARCHAR2(1 BYTE) DEFAULT 'N', 
	PUR_YIELD NUMBER(16,10), 
	TRANS_CHRG NUMBER(14,3) DEFAULT 0, 
	PLACEMENT_FEE NUMBER(14,3) DEFAULT 0, 
	ARRANGER_FEE NUMBER(14,3) DEFAULT 0, 
	ENTRY_EXIT_FEE NUMBER(14,3) DEFAULT 0, 
	PERFORMANCE_FEE NUMBER(14,3) DEFAULT 0, 
	MGMT_FEE NUMBER(14,3) DEFAULT 0, 
	FCY_TRANS_CHRG NUMBER(14,3) DEFAULT 0, 
	FCY_PLACEMENT_FEE NUMBER(14,3) DEFAULT 0, 
	FCY_ARRANGER_FEE NUMBER(14,3) DEFAULT 0, 
	FCY_ENTRY_EXIT_FEE NUMBER(14,3) DEFAULT 0, 
	FCY_PERFORMANCE_FEE NUMBER(14,3) DEFAULT 0, 
	FCY_MGMT_FEE NUMBER(14,3) DEFAULT 0, 
	FCY_SETTLEMENT_FEE NUMBER(14,3) DEFAULT 0, 
	FCY_TRANSACTION_LEVY NUMBER(14,3) DEFAULT 0, 
	ADVISORY_FEE_CCY VARCHAR2(3 BYTE), 
	FCY_ADVISORY_FEE NUMBER(18,3) DEFAULT 0, 
	ADVISORY_FEE NUMBER(18,3) DEFAULT 0, 
	ADVISORY_FEE_TRADE NUMBER(18,3) DEFAULT 0, 
	ADVISORY_FEE_EXCH_RATE NUMBER(20,10) DEFAULT 0, 
	ADVISORY_FEE_EXCH_RATE_N NUMBER(20,10) DEFAULT 0, 
	AOD_RECBLE NUMBER(16,3), 
	FCY_AOD_RECBLE NUMBER(16,3), 
	GROSS_VAL NUMBER(16,3), 
	FCY_GROSS_VAL NUMBER(16,3), 
	FCY_SERVICE_TAX NUMBER(14,3), 
	FCY_UNREL_AMT NUMBER(16,3), 
	UNREL_AMT NUMBER(16,3), 
	FCY_INJ_COSTUTIL NUMBER(18,3) DEFAULT 0, 
	INJ_COSTUTIL NUMBER(18,3) DEFAULT 0, 
	STATUS VARCHAR2(4 BYTE), 
	INPUTTER VARCHAR2(9 BYTE), 
	INP_DT_TM VARCHAR2(16 BYTE), 
	DESC1 VARCHAR2(500 BYTE), 
	DESC2 VARCHAR2(500 BYTE), 
	DESC3 VARCHAR2(500 BYTE), 
	FF_N1 NUMBER(16,2), 
	FF_N2 NUMBER(16,2), 
	FF_N3 NUMBER(16,2), 
	FF_VC1 VARCHAR2(500 BYTE), 
	FF_VC2 VARCHAR2(500 BYTE), 
	FF_VC3 VARCHAR2(500 BYTE), 
	FF_VC4 VARCHAR2(500 BYTE), 
	FF_VC5 VARCHAR2(500 BYTE), 
	FF_D1 DATE, 
	FF_D2 DATE, 
	FF_D3 DATE, 
	CR_ID VARCHAR2(50 BYTE), 
	CR_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	UPD_ID VARCHAR2(50 BYTE), 
	UPD_DT TIMESTAMP (6), 
	ACTIVE VARCHAR2(2 BYTE) DEFAULT 'Y', 
	ACTIVATION_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	DEACTIVATION_DT TIMESTAMP (6) DEFAULT '31-DEC-4099 12:00:00 AM'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 57344 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HM_TBS ;
--------------------------------------------------------
--  DDL for Index CT_UK_HDEAL
--------------------------------------------------------

  CREATE UNIQUE INDEX CT_UK_HDEAL ON HM_DEAL (DEAL_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHINDX_TBS ;
--------------------------------------------------------
--  Constraints for Table HM_DEAL
--------------------------------------------------------

  ALTER TABLE HM_DEAL MODIFY (AMC_CODE NOT NULL ENABLE);
 
  ALTER TABLE HM_DEAL MODIFY (DEAL_ID NOT NULL ENABLE);
 
  ALTER TABLE HM_DEAL MODIFY (RECTYPE NOT NULL ENABLE);
 
  ALTER TABLE HM_DEAL MODIFY (CURRNO NOT NULL ENABLE);
 
  ALTER TABLE HM_DEAL MODIFY (SCHEME NOT NULL ENABLE);
 
  ALTER TABLE HM_DEAL MODIFY (SECURITY NOT NULL ENABLE);
 
  ALTER TABLE HM_DEAL MODIFY (INVEST_TYPE NOT NULL ENABLE);
 
  ALTER TABLE HM_DEAL MODIFY (TRAN_TYPE NOT NULL ENABLE);
 
  ALTER TABLE HM_DEAL MODIFY (ASSET_TYPE NOT NULL ENABLE);
 
  ALTER TABLE HM_DEAL MODIFY (ZONE NOT NULL ENABLE);
 
  ALTER TABLE HM_DEAL MODIFY (INPUTTER NOT NULL ENABLE);
 
  ALTER TABLE HM_DEAL MODIFY (INP_DT_TM NOT NULL ENABLE);
 
  ALTER TABLE HM_DEAL MODIFY (CR_ID NOT NULL ENABLE);
 
  ALTER TABLE HM_DEAL MODIFY (CR_DT NOT NULL ENABLE);
 
  ALTER TABLE HM_DEAL MODIFY (ACTIVE NOT NULL ENABLE);
 
  ALTER TABLE HM_DEAL MODIFY (ACTIVATION_DT NOT NULL ENABLE);
 
  ALTER TABLE HM_DEAL MODIFY (DEACTIVATION_DT NOT NULL ENABLE);

