--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HM_SCHCLASS
--------------------------------------------------------

  CREATE TABLE HM_SCHCLASS 
   (	AMC_CODE VARCHAR2(100 BYTE), 
	SCHEME VARCHAR2(100 BYTE), 
	SRL_NO NUMBER(3,0), 
	RECTYPE VARCHAR2(1 BYTE), 
	CURRNO NUMBER(5,0), 
	SCHCLASS VARCHAR2(100 BYTE), 
	NAME VARCHAR2(500 BYTE), 
	FACE_VALUE NUMBER(18,3), 
	EXP_LIMIT VARCHAR2(100 BYTE), 
	UNITS_OUTS NUMBER(20,4), 
	UNITS_OUTSAMC NUMBER(20,4), 
	UNITS_OUTSOMF NUMBER(20,4), 
	MGMT_FEES VARCHAR2(100 BYTE), 
	TRUST_FEES VARCHAR2(100 BYTE), 
	ACC_FEES VARCHAR2(100 BYTE), 
	PEXP_FEES VARCHAR2(100 BYTE), 
	OTH1_FEES VARCHAR2(100 BYTE), 
	OTH2_FEES VARCHAR2(100 BYTE), 
	APPEXP_PER VARCHAR2(100 BYTE), 
	ACTIVE_Y_N VARCHAR2(1 BYTE) DEFAULT 'Y', 
	STATUS VARCHAR2(4 BYTE), 
	INP_DT_TM VARCHAR2(16 BYTE), 
	DESC1 VARCHAR2(500 BYTE), 
	DESC2 VARCHAR2(500 BYTE), 
	DESC3 VARCHAR2(500 BYTE), 
	FF_N1 NUMBER(16,2), 
	FF_N2 NUMBER(16,2), 
	FF_N3 NUMBER(16,2), 
	FF_VC1 VARCHAR2(500 BYTE), 
	FF_VC2 VARCHAR2(500 BYTE), 
	FF_VC3 VARCHAR2(500 BYTE), 
	FF_VC4 VARCHAR2(500 BYTE), 
	FF_VC5 VARCHAR2(500 BYTE), 
	FF_D1 DATE, 
	FF_D2 DATE, 
	FF_D3 DATE, 
	CR_ID VARCHAR2(50 BYTE), 
	CR_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	UPD_ID VARCHAR2(50 BYTE), 
	UPD_DT TIMESTAMP (6), 
	ACTIVE VARCHAR2(2 BYTE) DEFAULT 'Y', 
	ACTIVATION_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	DEACTIVATION_DT TIMESTAMP (6) DEFAULT '31-DEC-4099 12:00:00 AM'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 57344 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HM_TBS ;
 

   COMMENT ON COLUMN HM_SCHCLASS.FF_VC1 IS 'Grouping-NAV computation';
 
   COMMENT ON COLUMN HM_SCHCLASS.FF_VC2 IS 'amfi code';
--------------------------------------------------------
--  DDL for Index CT_UK_HSCH_CLASS
--------------------------------------------------------

  CREATE UNIQUE INDEX CT_UK_HSCH_CLASS ON HM_SCHCLASS (SCHEME, SCHCLASS) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HINDX_TBS ;
--------------------------------------------------------
--  Constraints for Table HM_SCHCLASS
--------------------------------------------------------

  ALTER TABLE HM_SCHCLASS MODIFY (AMC_CODE NOT NULL ENABLE);
 
  ALTER TABLE HM_SCHCLASS MODIFY (SCHEME NOT NULL ENABLE);
 
  ALTER TABLE HM_SCHCLASS MODIFY (SRL_NO NOT NULL ENABLE);
 
  ALTER TABLE HM_SCHCLASS MODIFY (RECTYPE NOT NULL ENABLE);
 
  ALTER TABLE HM_SCHCLASS MODIFY (CURRNO NOT NULL ENABLE);
 
  ALTER TABLE HM_SCHCLASS MODIFY (INP_DT_TM NOT NULL ENABLE);
 
  ALTER TABLE HM_SCHCLASS MODIFY (CR_ID NOT NULL ENABLE);
 
  ALTER TABLE HM_SCHCLASS MODIFY (CR_DT NOT NULL ENABLE);
 
  ALTER TABLE HM_SCHCLASS MODIFY (ACTIVE NOT NULL ENABLE);
 
  ALTER TABLE HM_SCHCLASS MODIFY (ACTIVATION_DT NOT NULL ENABLE);
 
  ALTER TABLE HM_SCHCLASS MODIFY (DEACTIVATION_DT NOT NULL ENABLE);

