--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HM_SECURITY
--------------------------------------------------------

  CREATE TABLE HM_SECURITY 
   (	SECURITY VARCHAR2(100 BYTE), 
	RECTYPE VARCHAR2(1 BYTE), 
	CURRNO NUMBER(5,0), 
	FACE_VALUE NUMBER(18,3), 
	FACE_VALIN NUMBER(18,3), 
	INTEREST NUMBER(20,6), 
	TAX_PER NUMBER(10,6), 
	MKT_PRICE NUMBER(18,6), 
	MKT_LOT NUMBER(14,2), 
	MAX_PRICE NUMBER(18,6), 
	MIN_PRICE NUMBER(18,6), 
	PRV_INT_DT DATE, 
	NXT_INT_DT DATE, 
	MAT_DATE DATE, 
	ALLOT_DATE DATE, 
	NAME VARCHAR2(75 BYTE), 
	MNEMONIC VARCHAR2(14 BYTE), 
	ISSUER VARCHAR2(100 BYTE), 
	INDUSTRY VARCHAR2(100 BYTE), 
	ASSET_TYPE VARCHAR2(100 BYTE), 
	STK_GROUP VARCHAR2(2 BYTE), 
	DISCOUNTED VARCHAR2(1 BYTE), 
	INT_DAY VARCHAR2(1 BYTE), 
	INT_FRQ VARCHAR2(8 BYTE), 
	LISTED_Y_N VARCHAR2(1 BYTE), 
	ASSET_GROUP VARCHAR2(2 BYTE), 
	ACCRINT_Y_N VARCHAR2(1 BYTE), 
	LOAN_CODE_NO VARCHAR2(17 BYTE), 
	IPO_INTEREST NUMBER(20,6), 
	SEC_CREATE_INT NUMBER(10,6), 
	SECURED_YN VARCHAR2(1 BYTE), 
	BULLET_RED_YN VARCHAR2(1 BYTE), 
	RED_METHOD VARCHAR2(1 BYTE), 
	WRITTEN_OFF_AMOUNT NUMBER(18,3), 
	PREMIUM NUMBER(14,3), 
	MKTPRICE_DAYS NUMBER(5,0), 
	VALUATION_TYPE VARCHAR2(1 BYTE), 
	CAP NUMBER(10,6), 
	CURRENCY VARCHAR2(3 BYTE), 
	FLOOR NUMBER(10,6), 
	INTEREST_KEY VARCHAR2(10 BYTE), 
	INT_TYPE VARCHAR2(1 BYTE), 
	ISIN_CODE VARCHAR2(15 BYTE), 
	CUSIP_NO VARCHAR2(15 BYTE), 
	CEDEL_NO VARCHAR2(15 BYTE), 
	EUROCLEAR_NO VARCHAR2(15 BYTE), 
	COMP_TYPE VARCHAR2(1 BYTE), 
	MARGIN NUMBER(10,6), 
	STK_EXCH VARCHAR2(3 BYTE), 
	RESET_FREQ VARCHAR2(8 BYTE), 
	PREV_PRV_INT_DT DATE, 
	CMPD_Y_N VARCHAR2(1 BYTE) DEFAULT 'N', 
	CMPD_FREQ VARCHAR2(8 BYTE), 
	NOOF_COUPONS NUMBER(5,0), 
	TICKER VARCHAR2(30 BYTE), 
	STK_SEC_ID VARCHAR2(20 BYTE), 
	ACTIVATE_Y_N VARCHAR2(1 BYTE), 
	ACCRAOD_Y_N VARCHAR2(1 BYTE), 
	SECTOR VARCHAR2(6 BYTE), 
	APP_AMOUNT NUMBER(12,4) DEFAULT 0, 
	VOTING_Y_N VARCHAR2(1 BYTE) DEFAULT 'N', 
	RATING VARCHAR2(100 BYTE), 
	THINLY_Y_N VARCHAR2(1 BYTE) DEFAULT 'N', 
	BENCHMARK VARCHAR2(12 BYTE), 
	EFFECTIVE_DATE DATE, 
	RATING_AGENCY VARCHAR2(100 BYTE), 
	STATUS VARCHAR2(4 BYTE), 
	INP_DT_TM VARCHAR2(16 BYTE), 
	DESC1 VARCHAR2(500 BYTE), 
	DESC2 VARCHAR2(500 BYTE), 
	DESC3 VARCHAR2(500 BYTE), 
	FF_N1 NUMBER(16,2), 
	FF_N2 NUMBER(16,2), 
	FF_N3 NUMBER(16,2), 
	FF_VC1 VARCHAR2(500 BYTE), 
	FF_VC2 VARCHAR2(500 BYTE), 
	FF_VC3 VARCHAR2(500 BYTE), 
	FF_VC4 VARCHAR2(500 BYTE), 
	FF_VC5 VARCHAR2(500 BYTE), 
	FF_D1 DATE, 
	FF_D2 DATE, 
	FF_D3 DATE, 
	CR_ID VARCHAR2(50 BYTE), 
	CR_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	UPD_ID VARCHAR2(50 BYTE), 
	UPD_DT TIMESTAMP (6), 
	ACTIVE VARCHAR2(2 BYTE) DEFAULT 'Y', 
	ACTIVATION_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	DEACTIVATION_DT TIMESTAMP (6) DEFAULT '31-DEC-4099 12:00:00 AM'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 57344 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HM_TBS ;
 

   COMMENT ON COLUMN HM_SECURITY.FF_D1 IS 'FIRST_INT_DATE';
--------------------------------------------------------
--  DDL for Index CT_UK_HSECURITY
--------------------------------------------------------

  CREATE UNIQUE INDEX CT_UK_HSECURITY ON HM_SECURITY (SECURITY) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHINDX_TBS ;
--------------------------------------------------------
--  Constraints for Table HM_SECURITY
--------------------------------------------------------

  ALTER TABLE HM_SECURITY MODIFY (SECURITY NOT NULL ENABLE);
 
  ALTER TABLE HM_SECURITY MODIFY (RECTYPE NOT NULL ENABLE);
 
  ALTER TABLE HM_SECURITY MODIFY (CURRNO NOT NULL ENABLE);
 
  ALTER TABLE HM_SECURITY MODIFY (ASSET_TYPE NOT NULL ENABLE);
 
  ALTER TABLE HM_SECURITY MODIFY (CURRENCY NOT NULL ENABLE);
 
  ALTER TABLE HM_SECURITY MODIFY (INP_DT_TM NOT NULL ENABLE);
 
  ALTER TABLE HM_SECURITY MODIFY (CR_ID NOT NULL ENABLE);
 
  ALTER TABLE HM_SECURITY MODIFY (CR_DT NOT NULL ENABLE);
 
  ALTER TABLE HM_SECURITY MODIFY (ACTIVE NOT NULL ENABLE);
 
  ALTER TABLE HM_SECURITY MODIFY (ACTIVATION_DT NOT NULL ENABLE);
 
  ALTER TABLE HM_SECURITY MODIFY (DEACTIVATION_DT NOT NULL ENABLE);

