--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HPER_NAV_MISSED
--------------------------------------------------------

  CREATE TABLE HPER_NAV_MISSED 
   (	SCHEME VARCHAR2(50 BYTE), 
	PLAN VARCHAR2(50 BYTE), 
	MISSED_VALUE NUMBER(21,8), 
	INPUT_DATE DATE, 
	UPLOAD_DT DATE DEFAULT SYSDATE, 
	VALUE_DATE DATE, 
	STATUS VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHI_TBS ;


