--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HPER_CAMS
--------------------------------------------------------

  CREATE TABLE HPER_CAMS 
   (	UPLOAD_DT DATE, 
	HDFC_AMC_CODE VARCHAR2(50 BYTE), 
	CAMS_CODE VARCHAR2(100 BYTE), 
	SCHEME VARCHAR2(100 BYTE), 
	CLOSING_BALANCE NUMBER(21,5), 
	OTHERS NUMBER(21,5), 
	C_PAYOUT NUMBER(21,5), 
	C_REINVEST NUMBER(21,5), 
	IND_HUF NUMBER(21,5), 
	R_PAYOUT NUMBER(21,5), 
	R_REINVEST NUMBER(21,5), 
	C_BLANK NUMBER(21,5), 
	R_BLANK NUMBER(21,5), 
	VALUE_DATE DATE, 
	STATUS VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHI_TBS ;


