--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HPER_BSE
--------------------------------------------------------

  CREATE TABLE HPER_BSE 
   (	SC_CODE NUMBER(12,0), 
	SC_NAME VARCHAR2(4000 BYTE), 
	SC_GROUP VARCHAR2(100 BYTE), 
	SC_TYPE VARCHAR2(100 BYTE), 
	OPEN NUMBER(21,5), 
	HIGH NUMBER(21,5), 
	LOW NUMBER(21,5), 
	CLOSE NUMBER(21,5), 
	LAST NUMBER(21,5), 
	PREVCLOSE NUMBER(21,5), 
	NO_TRADES NUMBER(21,5), 
	NO_OF_SHRS NUMBER(21,5), 
	NET_TURNOV NUMBER(21,5), 
	TDCLOINDI VARCHAR2(100 BYTE), 
	UPD_DT DATE, 
	VALUE_DATE DATE, 
	STATUS VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHI_TBS ;


