--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HPER_MCY
--------------------------------------------------------

  CREATE TABLE HPER_MCY 
   (	MCY_DATE DATE, 
	FANDO VARCHAR2(500 BYTE), 
	P VARCHAR2(500 BYTE), 
	CM_CODE VARCHAR2(500 BYTE), 
	MKT_TYPE VARCHAR2(500 BYTE), 
	CP_CODE VARCHAR2(500 BYTE), 
	ACC_TYPE VARCHAR2(500 BYTE), 
	CLIENT_ACC_CODE NUMBER(21,5), 
	INSTR_TYPE VARCHAR2(500 BYTE), 
	SYMBOL VARCHAR2(500 BYTE), 
	EXPIRY DATE, 
	STRIKE_PRICE NUMBER(21,5), 
	OPTION_TYPE VARCHAR2(500 BYTE), 
	CA_LEVEL NUMBER(21,5), 
	BF_LONG_QTY NUMBER(21,5), 
	BF_LONG_VALUE NUMBER(21,5), 
	BF_SHORT_QTY NUMBER(21,5), 
	BF_SHORT_VALUE NUMBER(21,5), 
	OP_PUR_QTY NUMBER(21,5), 
	OP_PUR_VALUE NUMBER(21,5), 
	OP_SALE_QTY NUMBER(21,5), 
	OP_SALE_VALUE NUMBER(21,5), 
	PRE_LONG_QTY_BEF_EXERCISE NUMBER(21,5), 
	PRE_LONG_VAL_BEF_EXERCISE NUMBER(21,5), 
	PRE_SHORT_QTY_BEF_ASS NUMBER(21,5), 
	PRE_SHORT_VAL_BEF_ASS NUMBER(21,5), 
	EXE_QTY NUMBER(21,5), 
	ASS_QTY NUMBER(21,5), 
	POST_LONG_QTY_BEF_EXE NUMBER(21,5), 
	POST_LONG_VAL_BEF_EXE NUMBER(21,5), 
	POST_SHORT_QTY_BEF_ASS NUMBER(21,5), 
	POST_SHORT_VAL_BEF_ASS NUMBER(21,5), 
	SETTL_PRICE NUMBER(21,5), 
	NET_PRM NUMBER(21,5), 
	MTM NUMBER(21,5), 
	FINAL_SETLL NUMBER(21,5), 
	EXERCISE_VALUE NUMBER(21,5), 
	UPD_DT DATE, 
	VALUE_DATE DATE, 
	STATUS VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHI_TBS ;


