--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HREP_SECURITY_DETAIL_CURR
--------------------------------------------------------

  CREATE TABLE HREP_SECURITY_DETAIL_CURR 
   (	SEC_DET_ID NUMBER(12,0), 
	ASSET_CATEGORY VARCHAR2(100 BYTE), 
	ASSET_CLASS VARCHAR2(100 BYTE), 
	ASSET_GROUP VARCHAR2(100 BYTE), 
	ASSET_GROUP_NAME VARCHAR2(500 BYTE), 
	ASSET_GROUP_SORT_ORDER NUMBER(5,0), 
	ASSET_NAME VARCHAR2(500 BYTE), 
	BUSINESS_DATE DATE, 
	COUNTRY VARCHAR2(100 BYTE), 
	COUNTRY_NAME VARCHAR2(100 BYTE), 
	COUPON_RATE NUMBER(21,6), 
	CURRENCY VARCHAR2(100 BYTE), 
	CURRENCY_NAME1 VARCHAR2(500 BYTE), 
	DATA_SOURCE VARCHAR2(100 BYTE), 
	FACE_VALUE NUMBER(21,5), 
	INDUSTRY VARCHAR2(100 BYTE), 
	INDUSTRY_NAME VARCHAR2(500 BYTE), 
	IRDA_CODE VARCHAR2(100 BYTE), 
	IRDA_CATEGORY VARCHAR2(100 BYTE), 
	ISIN_CODE VARCHAR2(100 BYTE), 
	ISSUER VARCHAR2(500 BYTE), 
	ISSUER_NAME VARCHAR2(500 BYTE), 
	ISSUER_TYPE VARCHAR2(100 BYTE), 
	IS_ASSET_CLASS_LIQUID_ASSET VARCHAR2(2 BYTE), 
	IS_ASSET_CLASS_TRADABLE VARCHAR2(2 BYTE), 
	IS_FIXED_INCOME VARCHAR2(2 BYTE), 
	IS_ISSUER_RELATED VARCHAR2(2 BYTE), 
	IS_SECURITY_LISTED VARCHAR2(2 BYTE), 
	IS_SECURITY_THINLY_TRADED VARCHAR2(2 BYTE), 
	IS_SECURITY_VOTING_RIGHTS VARCHAR2(2 BYTE), 
	MARKET_LOT NUMBER(21,5), 
	MATURITY_DATE DATE, 
	MGMTGROUP_NAME VARCHAR2(500 BYTE), 
	MGMT_GROUP VARCHAR2(100 BYTE), 
	RATING_SOURCE VARCHAR2(100 BYTE), 
	RATING_NAM VARCHAR2(100 BYTE), 
	RATING_RANK VARCHAR2(50 BYTE), 
	MCR_ASSET_TYPE VARCHAR2(500 BYTE), 
	MCR_SUB_ASSET_TYPE VARCHAR2(500 BYTE), 
	SECTOR_ALT VARCHAR2(500 BYTE), 
	SECTOR VARCHAR2(100 BYTE), 
	SECTOR_NAME VARCHAR2(100 BYTE), 
	SECTOR_CATEGORY VARCHAR2(50 BYTE), 
	SECURITY VARCHAR2(100 BYTE), 
	SECURITY_NAME VARCHAR2(500 BYTE), 
	SECURITY_RATING VARCHAR2(100 BYTE), 
	TIME_STAMP TIMESTAMP (6) WITH TIME ZONE, 
	FF_N1 NUMBER(21,5), 
	FF_N2 NUMBER(21,5), 
	FF_N3 NUMBER(21,5), 
	FF_N4 NUMBER(21,5), 
	FF_N5 NUMBER(21,5), 
	FF_VC1 VARCHAR2(500 BYTE), 
	FF_VC2 VARCHAR2(500 BYTE), 
	FF_VC3 VARCHAR2(500 BYTE), 
	FF_VC4 VARCHAR2(500 BYTE), 
	FF_VC5 VARCHAR2(500 BYTE), 
	FF_D1 DATE, 
	FF_D2 DATE, 
	FF_D3 DATE, 
	FF_D4 DATE, 
	FF_D5 DATE, 
	CR_ID VARCHAR2(50 BYTE) DEFAULT 'HAMC', 
	CR_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	UPD_ID VARCHAR2(50 BYTE), 
	UPD_DT TIMESTAMP (6), 
	PROCESSED_DT DATE, 
	PROCESSED_STATUS VARCHAR2(2 BYTE) DEFAULT 'U', 
	ACTIVE VARCHAR2(2 BYTE) DEFAULT 'Y', 
	ACTIVATION_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	DEACTIVATION_DT TIMESTAMP (6) DEFAULT '31-DEC-4099 12:00:00 AM'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHS_TBS ;
--------------------------------------------------------
--  DDL for Index CT_SEC_DET_CURR_INDX1
--------------------------------------------------------

  CREATE INDEX CT_SEC_DET_CURR_INDX1 ON HREP_SECURITY_DETAIL_CURR (SEC_DET_ID, ASSET_CATEGORY, ASSET_CLASS, ASSET_GROUP) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHINDX_TBS ;
--------------------------------------------------------
--  DDL for Index CT_SEC_DET_CURR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX CT_SEC_DET_CURR_PK ON HREP_SECURITY_DETAIL_CURR (SEC_DET_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHINDX_TBS ;
--------------------------------------------------------
--  Constraints for Table HREP_SECURITY_DETAIL_CURR
--------------------------------------------------------

  ALTER TABLE HREP_SECURITY_DETAIL_CURR ADD CONSTRAINT CT_SEC_DET_CURR_PK PRIMARY KEY (SEC_DET_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHINDX_TBS  ENABLE;
 
  ALTER TABLE HREP_SECURITY_DETAIL_CURR MODIFY (SEC_DET_ID NOT NULL ENABLE);
 
  ALTER TABLE HREP_SECURITY_DETAIL_CURR MODIFY (ASSET_CLASS NOT NULL ENABLE);
 
  ALTER TABLE HREP_SECURITY_DETAIL_CURR MODIFY (COUNTRY NOT NULL ENABLE);
 
  ALTER TABLE HREP_SECURITY_DETAIL_CURR MODIFY (SECURITY NOT NULL ENABLE);

