--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HREP_SECURITY_TRANSACTION_CURR
--------------------------------------------------------

  CREATE TABLE HREP_SECURITY_TRANSACTION_CURR 
   (	SEC_TXN_ID NUMBER(12,0), 
	ACQU_COST_PCY NUMBER(18,3), 
	ACQU_COST_TCY NUMBER(18,3), 
	ASSET_CLASS VARCHAR2(100 BYTE), 
	ASSET_GROUP VARCHAR2(100 BYTE), 
	ASSET_NAME VARCHAR2(500 BYTE), 
	BRK_AMOUNT_PCY NUMBER(18,3), 
	BRK_AMOUNT_TCY NUMBER(18,3), 
	BROKER VARCHAR2(100 BYTE), 
	BROKER_GROUP VARCHAR2(100 BYTE), 
	BROKER_GROUP_NAME VARCHAR2(500 BYTE), 
	BROKER_NAME VARCHAR2(500 BYTE), 
	BUSINESS_DATE DATE, 
	COMPANY VARCHAR2(100 BYTE), 
	COUNTERPARTY VARCHAR2(100 BYTE), 
	COUNTERPARTY_NAME VARCHAR2(500 BYTE), 
	COUPON_RATE NUMBER(20,6), 
	CPARTY_GROUP VARCHAR2(100 BYTE), 
	CPARTY_GROUP_NAME VARCHAR2(500 BYTE), 
	CURRENCY VARCHAR2(100 BYTE), 
	DATA_SOURCE VARCHAR2(100 BYTE), 
	DIVISION VARCHAR2(100 BYTE), 
	ENTRY_DATE DATE, 
	GROSS_AMT_PCY NUMBER(16,3), 
	GROSS_AMT_TCY NUMBER(16,3), 
	GROSS_AOD_PCY NUMBER(14,3), 
	GROSS_AOD_TCY NUMBER(14,3), 
	GROSS_INT_PCY NUMBER(18,3), 
	GROSS_INT_TCY NUMBER(18,3), 
	INFLOW_OUTFLOW VARCHAR2(100 BYTE), 
	IS_BROKER_RELATED VARCHAR2(3 BYTE), 
	IS_CPARTY_RELATED VARCHAR2(3 BYTE), 
	IS_FIXED_INCOME VARCHAR2(100 BYTE), 
	IS_SYSGEN VARCHAR2(3 BYTE), 
	IS_SYS_BROKER VARCHAR2(3 BYTE), 
	IS_TRANSFER VARCHAR2(3 BYTE), 
	IS_TRF_PORTFOLIO_RELATED VARCHAR2(3 BYTE), 
	MATURITY_DATE DATE, 
	MODULE_REF VARCHAR2(100 BYTE), 
	NET_AMOUNT_PCY NUMBER(18,3), 
	NET_AMOUNT_TCY NUMBER(18,3), 
	PORTFOLIO VARCHAR2(100 BYTE), 
	PORTFOLIO_CCY VARCHAR2(100 BYTE), 
	PORTFOLIO_NAME VARCHAR2(500 BYTE), 
	PRICE NUMBER(24,10), 
	PURCHASE_YIELD NUMBER(16,10), 
	QUANTITY NUMBER(20,4), 
	REAL_GL_PCY NUMBER(18,3), 
	REAL_GL_TCY NUMBER(18,3), 
	REMARKS VARCHAR2(100 BYTE), 
	SECURITY VARCHAR2(100 BYTE), 
	SECURITY_NAME VARCHAR2(500 BYTE), 
	SERVICE_TAX_PCY NUMBER(14,3), 
	SERVICE_TAX_TCY NUMBER(14,3), 
	SETL_DATE DATE, 
	TIME_STAMP TIMESTAMP (6) WITH TIME ZONE, 
	TRADE_FEE_PCY NUMBER, 
	TRADE_FEE_TCY NUMBER, 
	TRANS_BASE_REF VARCHAR2(100 BYTE), 
	TRANS_CODE VARCHAR2(100 BYTE), 
	TRANS_DATE DATE, 
	TRANS_ID VARCHAR2(100 BYTE), 
	TRANS_NAME VARCHAR2(500 BYTE), 
	TRANS_REF VARCHAR2(100 BYTE), 
	TRANS_SRL_NO NUMBER, 
	TRF_PORTFOLIO VARCHAR2(100 BYTE), 
	TRF_PORTFOLIO_NAME VARCHAR2(500 BYTE), 
	FF_N1 NUMBER(16,2), 
	FF_N2 NUMBER(16,2), 
	FF_N3 NUMBER(16,2), 
	FF_N4 NUMBER(16,2), 
	FF_N5 NUMBER(16,2), 
	FF_VC1 VARCHAR2(500 BYTE), 
	FF_VC2 VARCHAR2(500 BYTE), 
	FF_VC3 VARCHAR2(500 BYTE), 
	FF_VC4 VARCHAR2(500 BYTE), 
	FF_VC5 VARCHAR2(500 BYTE), 
	FF_D1 DATE, 
	FF_D2 DATE, 
	FF_D3 DATE, 
	FF_D4 DATE, 
	FF_D5 DATE, 
	CR_ID VARCHAR2(50 BYTE) DEFAULT 'ADMIN', 
	CR_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	UPD_ID VARCHAR2(50 BYTE), 
	UPD_DT TIMESTAMP (6), 
	PROCESSED_DT DATE, 
	PROCESSED_STATUS VARCHAR2(2 BYTE) DEFAULT 'U', 
	ACTIVE VARCHAR2(2 BYTE) DEFAULT 'Y', 
	ACTIVATION_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	DEACTIVATION_DT TIMESTAMP (6) DEFAULT '31-DEC-4099 12:00:00 AM', 
	CURRENCY_NAME1 VARCHAR2(500 BYTE), 
	CURRENCY_NAME2 VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHS_TBS ;
--------------------------------------------------------
--  DDL for Index CT_SEC_TNX__PK
--------------------------------------------------------

  CREATE UNIQUE INDEX CT_SEC_TNX__PK ON HREP_SECURITY_TRANSACTION_CURR (SEC_TXN_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHI_TBS ;
--------------------------------------------------------
--  DDL for Index CT_SEC_TXN_CURR_INDX1
--------------------------------------------------------

  CREATE INDEX CT_SEC_TXN_CURR_INDX1 ON HREP_SECURITY_TRANSACTION_CURR (SEC_TXN_ID, ASSET_CLASS, ASSET_GROUP, ASSET_NAME) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHI_TBS ;
--------------------------------------------------------
--  Constraints for Table HREP_SECURITY_TRANSACTION_CURR
--------------------------------------------------------

  ALTER TABLE HREP_SECURITY_TRANSACTION_CURR ADD CONSTRAINT CT_SEC_TNX__PK PRIMARY KEY (SEC_TXN_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHI_TBS  ENABLE;
 
  ALTER TABLE HREP_SECURITY_TRANSACTION_CURR MODIFY (SEC_TXN_ID NOT NULL ENABLE);

