--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HREP_PORTFOLIO_SUMMARY
--------------------------------------------------------

  CREATE TABLE HREP_PORTFOLIO_SUMMARY 
   (	HPS_ID NUMBER(12,0), 
	COMPANY VARCHAR2(100 BYTE), 
	DIVISION VARCHAR2(100 BYTE), 
	PORTFOLIO VARCHAR2(200 BYTE), 
	PORTFOLIO_NAME VARCHAR2(200 BYTE), 
	CURRENCY VARCHAR2(100 BYTE), 
	TRANS_DATE DATE, 
	MONTH_ID VARCHAR2(17 BYTE), 
	YEAR_MONTH_ID NUMBER, 
	MONTH_TIME_SPAN NUMBER, 
	MONTH_END_DATE DATE, 
	QUARTER_ID VARCHAR2(7 BYTE), 
	QUARTER VARCHAR2(2 BYTE), 
	QUARTER_END_DATE DATE, 
	FISC_NUM_IND_QUARTER CHAR(4 BYTE), 
	YEAR_ID VARCHAR2(4 BYTE), 
	NAV_TYPE VARCHAR2(100 BYTE), 
	PORTFOLIO_PLAN VARCHAR2(100 BYTE), 
	PORTFOLIO_CLASS VARCHAR2(100 BYTE), 
	PORTFOLIO_CLASS_NAME VARCHAR2(200 BYTE), 
	PORTFOLIO_TYPE VARCHAR2(100 BYTE), 
	PORTFOLIO_CATEGORY VARCHAR2(100 BYTE), 
	PORTFOLIO_CATEGORY_NAME VARCHAR2(100 BYTE), 
	MTD_AVG_NET_ASSETS NUMBER(21,5), 
	YTD_AVG_NET_ASSETS NUMBER(21,5), 
	NET_ASSET_VALUE NUMBER(21,5), 
	CAPITAL NUMBER(21,5), 
	INCOME NUMBER(21,5), 
	EXPENSE NUMBER(21,5), 
	UNREL_GAIN_LOSS NUMBER(21,5), 
	NET_ASSETS_INC_EXP NUMBER(21,5), 
	UNITS_OUTS NUMBER(21,5), 
	NAV_PER_UNIT NUMBER(24,8), 
	NAV_RATIO NUMBER(21,5), 
	EXP_LIMIT_AMT NUMBER(21,5), 
	MGMT_FEES NUMBER(21,5), 
	YTD_AVG_NAV NUMBER(21,5), 
	MTD_AVG_NAV NUMBER(21,5), 
	BUY_NAV_VALUE NUMBER(21,5), 
	SELL_NAV_VALUE NUMBER(21,5), 
	MAP_PORTFOLIO VARCHAR2(200 BYTE), 
	MAP_PORTFOLIO_CLASS VARCHAR2(200 BYTE), 
	BUSINESS_DATE DATE, 
	DATA_SOURCE VARCHAR2(100 BYTE), 
	TIME_STAMP TIMESTAMP (6) WITH TIME ZONE, 
	FF_N1 NUMBER(16,2), 
	FF_N2 NUMBER(16,2), 
	FF_N3 NUMBER(16,2), 
	FF_N4 NUMBER(16,2), 
	FF_N5 NUMBER(16,2), 
	FF_VC1 VARCHAR2(500 BYTE), 
	FF_VC2 VARCHAR2(500 BYTE), 
	FF_VC3 VARCHAR2(500 BYTE), 
	FF_VC4 VARCHAR2(500 BYTE), 
	FF_VC5 VARCHAR2(500 BYTE), 
	FF_D1 DATE, 
	FF_D2 DATE, 
	FF_D3 DATE, 
	FF_D4 DATE, 
	FF_D5 DATE, 
	CR_ID VARCHAR2(50 BYTE) DEFAULT 'ADMIN', 
	CR_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	UPD_ID VARCHAR2(50 BYTE), 
	UPD_DT TIMESTAMP (6), 
	PROCESSED_DT DATE, 
	PROCESSED_STATUS VARCHAR2(2 BYTE) DEFAULT 'U', 
	ACTIVE VARCHAR2(2 BYTE) DEFAULT 'Y', 
	ACTIVATION_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	DEACTIVATION_DT TIMESTAMP (6) DEFAULT '31-DEC-4099 12:00:00 AM'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHS_TBS ;
--------------------------------------------------------
--  DDL for Index CT_PORT_SUM_INDX02
--------------------------------------------------------

  CREATE INDEX CT_PORT_SUM_INDX02 ON HREP_PORTFOLIO_SUMMARY (HPS_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHINDX_TBS ;
--------------------------------------------------------
--  DDL for Index CT_PORT_SUM_INDX01
--------------------------------------------------------

  CREATE INDEX CT_PORT_SUM_INDX01 ON HREP_PORTFOLIO_SUMMARY (PORTFOLIO, PORTFOLIO_NAME, TRANS_DATE, PORTFOLIO_PLAN) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHINDX_TBS ;


