--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HREP_LIQUIDITY_PREV
--------------------------------------------------------

  CREATE TABLE HREP_LIQUIDITY_PREV 
   (	COMPANY VARCHAR2(100 BYTE), 
	PORTFOLIO VARCHAR2(100 BYTE), 
	PORTFOLIO_NAME VARCHAR2(500 BYTE), 
	TRANS_DATE DATE, 
	PORTFOLIO_CATEGORY VARCHAR2(100 BYTE), 
	PORTFOLIO_CATEGORY_NAME VARCHAR2(100 BYTE), 
	RELATED_PARTY VARCHAR2(100 BYTE), 
	RELATED_PARY_NAME VARCHAR2(500 BYTE), 
	RELATED_PARTY_TYPE VARCHAR2(100 BYTE), 
	SECTOR_CATEGORY VARCHAR2(200 BYTE), 
	ASSET_GROUP VARCHAR2(100 BYTE), 
	ASSET_GROUP_NAME VARCHAR2(500 BYTE), 
	ASSET_CLASS VARCHAR2(100 BYTE), 
	ASSET_NAME VARCHAR2(500 BYTE), 
	SECURITY VARCHAR2(100 BYTE), 
	SECURITY_NAME VARCHAR2(500 BYTE), 
	MATURITY_DAYS NUMBER(5,0), 
	LIQUIDITY NUMBER(21,5), 
	IS_FIXED_INCOME VARCHAR2(3 BYTE), 
	DESC1 VARCHAR2(500 BYTE), 
	DESC2 VARCHAR2(500 BYTE), 
	DESC3 VARCHAR2(500 BYTE), 
	FF_N1 NUMBER(16,2), 
	FF_N2 NUMBER(16,2), 
	FF_N3 NUMBER(16,2), 
	FF_N4 NUMBER(16,2), 
	FF_N5 NUMBER(16,2), 
	FF_VC1 VARCHAR2(500 BYTE), 
	FF_VC2 VARCHAR2(500 BYTE), 
	FF_VC3 VARCHAR2(500 BYTE), 
	FF_VC4 VARCHAR2(500 BYTE), 
	FF_VC5 VARCHAR2(500 BYTE), 
	FF_D1 DATE, 
	FF_D2 DATE, 
	FF_D3 DATE, 
	FF_D4 DATE, 
	FF_D5 DATE, 
	CR_ID VARCHAR2(50 BYTE) DEFAULT 'HAMC', 
	CR_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	UPD_ID VARCHAR2(50 BYTE), 
	UPD_DT TIMESTAMP (6), 
	ACTIVE VARCHAR2(2 BYTE) DEFAULT 'Y', 
	ACTIVATION_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	DEACTIVATION_DT TIMESTAMP (6) DEFAULT '31-DEC-4099 12:00:00 AM'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHI_TBS ;
--------------------------------------------------------
--  Constraints for Table HREP_LIQUIDITY_PREV
--------------------------------------------------------

  ALTER TABLE HREP_LIQUIDITY_PREV MODIFY (CR_ID NOT NULL ENABLE);
 
  ALTER TABLE HREP_LIQUIDITY_PREV MODIFY (CR_DT NOT NULL ENABLE);
 
  ALTER TABLE HREP_LIQUIDITY_PREV MODIFY (ACTIVE NOT NULL ENABLE);
 
  ALTER TABLE HREP_LIQUIDITY_PREV MODIFY (ACTIVATION_DT NOT NULL ENABLE);
 
  ALTER TABLE HREP_LIQUIDITY_PREV MODIFY (DEACTIVATION_DT NOT NULL ENABLE);

