--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HSYS_JOB_ERROR
--------------------------------------------------------

  CREATE TABLE HSYS_JOB_ERROR 
   (	ORG_ID VARCHAR2(100 BYTE), 
	UJE_ID NUMBER(8,0), 
	USSJD_ID NUMBER(8,0), 
	SRC_SYS_ID NUMBER(8,0), 
	ERR_CODE VARCHAR2(50 BYTE), 
	ERR_CONTEXT VARCHAR2(4000 BYTE), 
	ERR_TYPE VARCHAR2(4000 BYTE), 
	ERR_DESC VARCHAR2(4000 BYTE), 
	ERR_DT TIMESTAMP (6), 
	FF_N1 NUMBER(16,2), 
	FF_N2 NUMBER(16,2), 
	FF_N3 NUMBER(16,2), 
	FF_VC1 VARCHAR2(500 BYTE), 
	FF_VC2 VARCHAR2(500 BYTE), 
	FF_VC3 VARCHAR2(500 BYTE), 
	FF_VC4 VARCHAR2(500 BYTE), 
	FF_VC5 VARCHAR2(500 BYTE), 
	FF_D1 DATE, 
	FF_D2 DATE, 
	FF_D3 DATE, 
	CR_ID VARCHAR2(50 BYTE), 
	CR_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	UPD_ID VARCHAR2(50 BYTE), 
	UPD_DT TIMESTAMP (6), 
	ACTIVE VARCHAR2(2 BYTE) DEFAULT 'Y', 
	ACTIVATION_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	DEACTIVATION_DT TIMESTAMP (6) DEFAULT '31-DEC-4099 12:00:00 AM'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHI_TBS ;
--------------------------------------------------------
--  DDL for Index CT_PK_UJE
--------------------------------------------------------

  CREATE UNIQUE INDEX CT_PK_UJE ON HSYS_JOB_ERROR (UJE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHINDX_TBS ;
--------------------------------------------------------
--  Constraints for Table HSYS_JOB_ERROR
--------------------------------------------------------

  ALTER TABLE HSYS_JOB_ERROR ADD CONSTRAINT ACTIVE_UJE_CHK CHECK (ACTIVE IN ('Y', 'N')) ENABLE;
 
  ALTER TABLE HSYS_JOB_ERROR ADD CONSTRAINT CT_PK_UJE PRIMARY KEY (UJE_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHINDX_TBS  ENABLE;
 
  ALTER TABLE HSYS_JOB_ERROR MODIFY (ORG_ID NOT NULL ENABLE);
 
  ALTER TABLE HSYS_JOB_ERROR MODIFY (UJE_ID NOT NULL ENABLE);
 
  ALTER TABLE HSYS_JOB_ERROR MODIFY (USSJD_ID NOT NULL ENABLE);
 
  ALTER TABLE HSYS_JOB_ERROR MODIFY (SRC_SYS_ID NOT NULL ENABLE);
 
  ALTER TABLE HSYS_JOB_ERROR MODIFY (ERR_CODE NOT NULL ENABLE);
 
  ALTER TABLE HSYS_JOB_ERROR MODIFY (ERR_CONTEXT NOT NULL ENABLE);
 
  ALTER TABLE HSYS_JOB_ERROR MODIFY (ERR_TYPE NOT NULL ENABLE);
 
  ALTER TABLE HSYS_JOB_ERROR MODIFY (ERR_DESC NOT NULL ENABLE);
 
  ALTER TABLE HSYS_JOB_ERROR MODIFY (ERR_DT NOT NULL ENABLE);
 
  ALTER TABLE HSYS_JOB_ERROR MODIFY (CR_ID NOT NULL ENABLE);
 
  ALTER TABLE HSYS_JOB_ERROR MODIFY (CR_DT NOT NULL ENABLE);
 
  ALTER TABLE HSYS_JOB_ERROR MODIFY (ACTIVE NOT NULL ENABLE);
 
  ALTER TABLE HSYS_JOB_ERROR MODIFY (ACTIVATION_DT NOT NULL ENABLE);
 
  ALTER TABLE HSYS_JOB_ERROR MODIFY (DEACTIVATION_DT NOT NULL ENABLE);

