--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HSYS_SRC_SYNCH_JOB_DTL
--------------------------------------------------------

  CREATE TABLE HSYS_SRC_SYNCH_JOB_DTL 
   (	ORG_ID VARCHAR2(100 BYTE), 
	USSJD_ID NUMBER(8,0), 
	SRC_SYS_ID NUMBER(8,0), 
	USS_ID NUMBER(8,0), 
	UJ_ID NUMBER(8,0), 
	SYNCH_ST_DT TIMESTAMP (6), 
	SYNCH_END_DT TIMESTAMP (6), 
	DURATION_SECONDS NUMBER(8,0), 
	IS_LATEST VARCHAR2(1 BYTE), 
	SYNCH_STATUS NUMBER(3,0), 
	SYNCH_REMARK VARCHAR2(4000 BYTE), 
	SYNCH_REMARK2 VARCHAR2(4000 BYTE), 
	FF_N1 NUMBER(16,2), 
	FF_N2 NUMBER(16,2), 
	FF_N3 NUMBER(16,2), 
	FF_VC1 VARCHAR2(500 BYTE), 
	FF_VC2 VARCHAR2(500 BYTE), 
	FF_VC3 VARCHAR2(500 BYTE), 
	FF_VC4 VARCHAR2(500 BYTE), 
	FF_VC5 VARCHAR2(500 BYTE), 
	FF_D1 DATE, 
	FF_D2 DATE, 
	FF_D3 DATE, 
	CR_ID VARCHAR2(50 BYTE), 
	CR_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	UPD_ID VARCHAR2(50 BYTE), 
	UPD_DT TIMESTAMP (6), 
	ACTIVE VARCHAR2(2 BYTE) DEFAULT 'Y', 
	ACTIVATION_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	DEACTIVATION_DT TIMESTAMP (6) DEFAULT '31-DEC-4099 12:00:00 AM'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHI_TBS ;
--------------------------------------------------------
--  DDL for Index CT_PK_USSJD
--------------------------------------------------------

  CREATE UNIQUE INDEX CT_PK_USSJD ON HSYS_SRC_SYNCH_JOB_DTL (USSJD_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHINDX_TBS ;
--------------------------------------------------------
--  Constraints for Table HSYS_SRC_SYNCH_JOB_DTL
--------------------------------------------------------

  ALTER TABLE HSYS_SRC_SYNCH_JOB_DTL ADD CONSTRAINT ACTIVE_USSJD_CHK CHECK (ACTIVE IN ('Y', 'N')) ENABLE;
 
  ALTER TABLE HSYS_SRC_SYNCH_JOB_DTL ADD CONSTRAINT CT_PK_USSJD PRIMARY KEY (USSJD_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHINDX_TBS  ENABLE;
 
  ALTER TABLE HSYS_SRC_SYNCH_JOB_DTL ADD CONSTRAINT IS_LATEST_USSJD_CHK CHECK (ACTIVE IN ('Y', 'N')) ENABLE;
 
  ALTER TABLE HSYS_SRC_SYNCH_JOB_DTL MODIFY (ORG_ID NOT NULL ENABLE);
 
  ALTER TABLE HSYS_SRC_SYNCH_JOB_DTL MODIFY (USSJD_ID NOT NULL ENABLE);
 
  ALTER TABLE HSYS_SRC_SYNCH_JOB_DTL MODIFY (SRC_SYS_ID NOT NULL ENABLE);
 
  ALTER TABLE HSYS_SRC_SYNCH_JOB_DTL MODIFY (SYNCH_ST_DT NOT NULL ENABLE);
 
  ALTER TABLE HSYS_SRC_SYNCH_JOB_DTL MODIFY (IS_LATEST NOT NULL ENABLE);
 
  ALTER TABLE HSYS_SRC_SYNCH_JOB_DTL MODIFY (SYNCH_STATUS NOT NULL ENABLE);
 
  ALTER TABLE HSYS_SRC_SYNCH_JOB_DTL MODIFY (CR_ID NOT NULL ENABLE);
 
  ALTER TABLE HSYS_SRC_SYNCH_JOB_DTL MODIFY (CR_DT NOT NULL ENABLE);
 
  ALTER TABLE HSYS_SRC_SYNCH_JOB_DTL MODIFY (ACTIVE NOT NULL ENABLE);
 
  ALTER TABLE HSYS_SRC_SYNCH_JOB_DTL MODIFY (ACTIVATION_DT NOT NULL ENABLE);
 
  ALTER TABLE HSYS_SRC_SYNCH_JOB_DTL MODIFY (DEACTIVATION_DT NOT NULL ENABLE);

