--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HUPD_MCY_UPLOAD
--------------------------------------------------------

  CREATE TABLE HUPD_MCY_UPLOAD 
   (	MCY_ID NUMBER(12,0), 
	MCY_DATE DATE, 
	FANDO VARCHAR2(50 BYTE), 
	P VARCHAR2(50 BYTE), 
	CM_CODE VARCHAR2(500 BYTE), 
	MKT_TYPE VARCHAR2(50 BYTE), 
	CP_CODE VARCHAR2(500 BYTE), 
	ACC_TYPE VARCHAR2(500 BYTE), 
	CLIENT_ACC_CODE NUMBER(16,2), 
	INSTR_TYPE VARCHAR2(500 BYTE), 
	SYMBOL VARCHAR2(500 BYTE), 
	EXPIRY DATE, 
	STRIKE_PRICE NUMBER(16,2), 
	OPTION_TYPE VARCHAR2(50 BYTE), 
	CA_LEVEL NUMBER(16,2), 
	BF_LONG_QTY NUMBER(16,2), 
	BF_LONG_VALUE NUMBER(16,2), 
	BF_SHORT_QTY NUMBER(16,2), 
	BF_SHORT_VALUE NUMBER(16,2), 
	OP_PUR_QTY NUMBER(16,2), 
	OP_PUR_VALUE NUMBER(16,2), 
	OP_SALE_QTY NUMBER(16,2), 
	OP_SALE_VALUE NUMBER(16,2), 
	PRE_LONG_QTY_BEF_EXERCISE NUMBER(16,2), 
	PRE_LONG_VAL_BEF_EXERCISE NUMBER(16,2), 
	PRE_SHORT_QTY_BEF_ASS NUMBER(16,2), 
	PRE_SHORT_VAL_BEF_ASS NUMBER(16,2), 
	EXE_QTY NUMBER(16,2), 
	ASS_QTY NUMBER(16,2), 
	POST_LONG_QTY_BEF_EXE NUMBER(16,2), 
	POST_LONG_VAL_BEF_EXE NUMBER(16,2), 
	POST_SHORT_QTY_BEF_ASS NUMBER(16,2), 
	POST_SHORT_VAL_BEF_ASS NUMBER(16,2), 
	SETTL_PRICE NUMBER(16,2), 
	NET_PRM NUMBER(16,2), 
	MTM NUMBER(16,2), 
	FINAL_SETLL NUMBER(16,2), 
	EXERCISE_VALUE NUMBER(16,2), 
	UPLOAD_DATE DATE, 
	FF_N1 NUMBER(16,2), 
	FF_N2 NUMBER(16,2), 
	FF_N3 NUMBER(16,2), 
	FF_N4 NUMBER(16,2), 
	FF_N5 NUMBER(16,2), 
	FF_VC1 VARCHAR2(500 BYTE), 
	FF_VC2 VARCHAR2(500 BYTE), 
	FF_VC3 VARCHAR2(500 BYTE), 
	FF_VC4 VARCHAR2(500 BYTE), 
	FF_VC5 VARCHAR2(500 BYTE), 
	FF_D1 DATE, 
	FF_D2 DATE, 
	FF_D3 DATE, 
	FF_D4 DATE, 
	FF_D5 DATE, 
	CR_ID VARCHAR2(50 BYTE) DEFAULT 'ADMIN', 
	CR_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	UPD_ID VARCHAR2(50 BYTE), 
	UPD_DT TIMESTAMP (6), 
	PROCESSED_DT DATE, 
	PROCESSED_STATUS VARCHAR2(2 BYTE) DEFAULT 'U', 
	ACTIVE VARCHAR2(2 BYTE) DEFAULT 'Y', 
	ACTIVATION_DT TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	DEACTIVATION_DT TIMESTAMP (6) DEFAULT '31-DEC-4099 12:00:00 AM'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHI_TBS ;


