CREATE TABLE SYSPARAM 
(
  AMC_CODE VARCHAR2(12 BYTE) NOT NULL 
, RECTYPE VARCHAR2(1 BYTE) NOT NULL 
, CURRNO NUMBER(5, 0) NOT NULL 
, STAMP NUMBER(10, 6) 
, BROKERAGE_CAP NUMBER(10, 6) 
, MKT_TOLER NUMBER(10, 6) 
, SHRT_GNPRD NUMBER(5, 0) 
, CFLOW_PRD NUMBER(3, 0) 
, LETTER_REF NUMBER(5, 0) 
, PREV_DATE DATE 
, CUR_DATE DATE 
, NEXT_DATE DATE 
, YEAR_END DATE 
, COMPANY VARCHAR2(45 BYTE) 
, ADDRESS_1 VARCHAR2(35 BYTE) 
, ADDRESS_2 VARCHAR2(35 BYTE) 
, ADDRESS_3 VARCHAR2(35 BYTE) 
, FND_CONAME VARCHAR2(45 BYTE) 
, FUND_NAME VARCHAR2(35 BYTE) 
, SCHEME_OVR VARCHAR2(12 BYTE) 
, SCHEME_AMC VARCHAR2(12 BYTE) 
, SCHEME_TRU VARCHAR2(12 BYTE) 
, GLOBAL_SCHEME VARCHAR2(12 BYTE) 
, BATCH VARCHAR2(1 BYTE) 
, DATA_DIR VARCHAR2(40 BYTE) 
, WEEKEND_1 VARCHAR2(3 BYTE) 
, WEEKEND_2 VARCHAR2(3 BYTE) 
, CUSTODIAN VARCHAR2(12 BYTE) 
, STK_EXCH VARCHAR2(3 BYTE) 
, PRINTER_ID VARCHAR2(8 BYTE) 
, AMTFMT VARCHAR2(1 BYTE) 
, IDLESECS NUMBER(5, 0) 
, MF_VERSION VARCHAR2(20 BYTE) 
, CAPEXPENSE_YN VARCHAR2(1 BYTE) 
, PRINT_ZEROYN VARCHAR2(1 BYTE) 
, PRINT_VOUCHER VARCHAR2(1 BYTE) 
, MKTPRICE_OHLC VARCHAR2(1 BYTE) 
, BRK_SERV_CHG NUMBER(10, 6) 
, WEEKLY_LIM_RESET_DAY VARCHAR2(3 BYTE) 
, STOCK_SEGMENT VARCHAR2(1 BYTE) 
, DIPDIS_INAU VARCHAR2(1 BYTE) 
, DIPDIS_PMAPP VARCHAR2(1 BYTE) 
, REVBKDT VARCHAR2(1 BYTE) 
, ZONE VARCHAR2(6 BYTE) NOT NULL 
, PENALTY_INT NUMBER(10, 6) 
, SQOFF_PENALTY_INT NUMBER(10, 6) 
, SGL_ACCT_NO VARCHAR2(10 BYTE) 
, RBI_CA_NO VARCHAR2(15 BYTE) 
, PDC_BANK_LIST_NOTICE NUMBER(1, 0) 
, HIGH_VALUE_AMT NUMBER(18, 3) 
, BROKER VARCHAR2(12 BYTE) 
, DEALER VARCHAR2(9 BYTE) 
, MKTPRICE_DAYS NUMBER(5, 0) 
, CUSTODIAN2 VARCHAR2(12 BYTE) 
, ENTRIES_IN_PAYINSLIP NUMBER(2, 0) 
, TDS_PER NUMBER(10, 6) 
, BNK_CHRG_PER NUMBER(10, 6) 
, REMIT_BNK_ACCOUNT VARCHAR2(25 BYTE) 
, LIQ_ACCOUNT VARCHAR2(6 BYTE) 
, MASK VARCHAR2(30 BYTE) 
, INVEST_ACCOUNT VARCHAR2(6 BYTE) 
, RECEIPTS_CTRL_AC VARCHAR2(6 BYTE) 
, CLOSED_YEAR_END DATE 
, EOD_ABORTED_USER_ID VARCHAR2(9 BYTE) 
, NO_DIV_PERIOD NUMBER(5, 0) 
, NO_TRADE_PERIOD NUMBER(5, 0) 
, ADQ_SAFE_GRADE VARCHAR2(2 BYTE) 
, EXCESS_PAYMENT_ACCOUNT VARCHAR2(6 BYTE) 
, IST_DIPDIS_YN VARCHAR2(1 BYTE) 
, HD_BROKERAGE_CAP NUMBER(10, 6) 
, CUSTODIAN_N VARCHAR2(12 BYTE) 
, MMPOOL_INCOME_ACCOUNT VARCHAR2(6 BYTE) 
, SECRATING_PERIOD NUMBER(5, 0) 
, DEL_TYPE VARCHAR2(3 BYTE) 
, DISCINC_AC VARCHAR2(6 BYTE) 
, START_DATE DATE 
, PCD_ASSETYPE VARCHAR2(6 BYTE) 
, OTHINC_AC VARCHAR2(6 BYTE) 
, BRKBEN_YN VARCHAR2(1 BYTE) 
, DIPDIS_BEN_YN VARCHAR2(1 BYTE) 
, REPO_WITHINT_YN VARCHAR2(1 BYTE) 
, REPO_AUTOSETL_YN VARCHAR2(1 BYTE) 
, SCHACCESS_YN VARCHAR2(1 BYTE) 
, INTACC_SETTLE_YN VARCHAR2(1 BYTE) 
, YTM_VALUATION_YN VARCHAR2(1 BYTE) 
, COUNTRY VARCHAR2(2 BYTE) 
, AMC_NUMBER VARCHAR2(2 BYTE) 
, CURRENCY VARCHAR2(3 BYTE) 
, EXCH_DIFF_COST_YN VARCHAR2(1 BYTE) DEFAULT 'N' 
, MULTICO_ACCT_YN VARCHAR2(1 BYTE) DEFAULT 'N' 
, TRANS_BACKDATE VARCHAR2(1 BYTE) 
, BACKUP_Y_N VARCHAR2(1 BYTE) 
, BONUS_BLOCK_DAYS NUMBER(3, 0) 
, REPSAL_SETLDAYS NUMBER(2, 0) 
, SWIFT VARCHAR2(12 BYTE) 
, TEL_NO VARCHAR2(20 BYTE) 
, FAX_NO VARCHAR2(20 BYTE) 
, EMAIL_ID VARCHAR2(35 BYTE) 
, INPAUTH_Y_N VARCHAR2(1 BYTE) 
, NOOF_USERS NUMBER(5, 0) 
, TOLERANCE NUMBER(7, 4) 
, HOLIDAY VARCHAR2(6 BYTE) 
, SEGMENT VARCHAR2(3 BYTE) 
, MIN_PASS_LENGTH NUMBER(2, 0) 
, LOGON_ATTEMPTS NUMBER(2, 0) 
, USER_INACTIVE_DAYS NUMBER(2, 0) 
, MONTHEND_NAV_YN VARCHAR2(1 BYTE) 
, DEPOINT_VALDATE VARCHAR2(1 BYTE) 
, STAMP_PAY_Y_N VARCHAR2(1 BYTE) DEFAULT 'N' 
, CLUBBING_MANUAL_Y_N VARCHAR2(1 BYTE) DEFAULT 'N' 
, POLLING_START_YN VARCHAR2(1 BYTE) DEFAULT 'N' 
, POLLING_FREQUENCY NUMBER(5, 0) DEFAULT 0 
, MAX_PWD_CHECK NUMBER(3, 0) DEFAULT 1 
, MAX_PASS_LENGTH NUMBER(2, 0) DEFAULT 4 
, PWD_CHRTYPE VARCHAR2(1 BYTE) DEFAULT 'P' 
, PWD_DIFFCHR NUMBER(2, 0) DEFAULT 1 
, PWD_STARTCHR VARCHAR2(1 BYTE) DEFAULT 'P' 
, INVEST_TYPE VARCHAR2(6 BYTE) 
, RATING_PERIOD NUMBER(5, 0) 
, RATING_1 VARCHAR2(12 BYTE) 
, RATING_2 VARCHAR2(12 BYTE) 
, RATING_SRC VARCHAR2(10 BYTE) 
, BPS_DURGRATE NUMBER(5, 2) 
, DURATION NUMBER(2, 0) 
, BPS_DURLESS NUMBER(5, 2) 
, RES_MAT_DAYS NUMBER(5, 0) 
, STP_YN VARCHAR2(1 BYTE) DEFAULT 'N' 
, YE_NEXTDAY_YN VARCHAR2(1 BYTE) DEFAULT 'N' 
, ENABLE_MCY_YN VARCHAR2(1 BYTE) DEFAULT 'N' 
, SCH_EOD_YN VARCHAR2(1 BYTE) DEFAULT 'N' 
, MULTI_EOD_YN VARCHAR2(1 BYTE) DEFAULT 'N' 
, EXCHRATE_TYPE VARCHAR2(1 BYTE) DEFAULT 'B' 
, NI_PERCENT NUMBER(5, 2) DEFAULT '0' 
, STATUS VARCHAR2(4 BYTE) 
, INPUTTER VARCHAR2(9 BYTE) NOT NULL 
, INP_DT_TM VARCHAR2(16 BYTE) NOT NULL 
, AUTHORISER VARCHAR2(9 BYTE) 
) 
LOGGING 
TABLESPACE HM_TBS 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE UNIQUE INDEX PK_SYSPARAM ON SYSPARAM (AMC_CODE ASC, RECTYPE ASC, CURRNO ASC) 
LOGGING 
TABLESPACE HHI_TBS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;
