--------------------------------------------------------
--  File created - Wednesday-May-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table UAM_SECURITY1
--------------------------------------------------------

  CREATE TABLE UAM_SECURITY1 
   (	SECURITY1_ID NUMBER(8,0), 
	SECURITY1_NAME VARCHAR2(4000 BYTE), 
	SECURITY1_CODE VARCHAR2(50 BYTE), 
	USER_ID VARCHAR2(40 CHAR), 
	CR_ID VARCHAR2(50 BYTE) DEFAULT 'Administrator', 
	UPD_ID VARCHAR2(50 BYTE), 
	CR_DT DATE DEFAULT sysdate, 
	UPD_DT DATE, 
	ACTIVE VARCHAR2(2 CHAR) DEFAULT 'Y', 
	ACTIVATION_DT DATE DEFAULT SYSDATE, 
	DEACTIVATION_DT DATE DEFAULT '31-DEC-4099'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HM_TBS ;
--------------------------------------------------------
--  DDL for Index UAM_SEC_CODE_IDX
--------------------------------------------------------

  CREATE INDEX UAM_SEC_CODE_IDX ON UAM_SECURITY1 (SECURITY1_CODE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHINDX_TBS ;
--------------------------------------------------------
--  DDL for Index UAM_SECURITY1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX UAM_SECURITY1_PK ON UAM_SECURITY1 (SECURITY1_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHINDX_TBS ;
--------------------------------------------------------
--  DDL for Index UAM_SECURITY1_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX UAM_SECURITY1_UK1 ON UAM_SECURITY1 (SECURITY1_CODE, USER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHINDX_TBS ;
--------------------------------------------------------
--  DDL for Index UAM_SEC_USRID_IDX
--------------------------------------------------------

  CREATE INDEX UAM_SEC_USRID_IDX ON UAM_SECURITY1 (USER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHINDX_TBS ;
--------------------------------------------------------
--  Constraints for Table UAM_SECURITY1
--------------------------------------------------------

  ALTER TABLE UAM_SECURITY1 MODIFY (SECURITY1_ID NOT NULL ENABLE);
 
  ALTER TABLE UAM_SECURITY1 ADD CONSTRAINT UAM_SECURITY1_PK PRIMARY KEY (SECURITY1_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHINDX_TBS  ENABLE;
 
  ALTER TABLE UAM_SECURITY1 ADD CONSTRAINT UAM_SECURITY1_UK1 UNIQUE (SECURITY1_CODE, USER_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE HHINDX_TBS  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UAM_SECURITY1
--------------------------------------------------------

  ALTER TABLE UAM_SECURITY1 ADD CONSTRAINT FK_UAM_SECURITY1_UID FOREIGN KEY (USER_ID)
	  REFERENCES UM_USER (USER_ID) ENABLE;
