/*
Created By : Ram
Date : 17/07/2013
Reason: Tables script for creating the tables in the new scheme.
*/
-- DROP TABLES
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE HSI_STUDENT_INFO CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE HI_CUSTOMER_DEMOGRAPHICS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE HI_PROSPECT_DEMOGRAPHICS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE UC_SRC_SYS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE UM_MAPPING_OTHERS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE UM_GEOGRAPHY CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- Table name : UM_GEOGRAPHY

CREATE TABLE "UM_GEOGRAPHY"
  (
    "ORG_ID"          NUMBER(8,0) NOT NULL ENABLE,
    "GEO_ID"          NUMBER(8,0) NOT NULL ENABLE,
    "GEO_DESC1"       VARCHAR2(4000 BYTE) NOT NULL ENABLE,
    "GEO_SHORT_DESC1" VARCHAR2(100 BYTE) NOT NULL ENABLE,
    "GEO_DESC2"       VARCHAR2(4000 BYTE),
    "GEO_SHORT_DESC2" VARCHAR2(100 BYTE),
    "LEVEL_ID"        NUMBER(12,0) NOT NULL ENABLE,
    "LEVEL_PRED_ID"   NUMBER(12,0),
    "SRC_SYS_ID"      NUMBER(8,0) NOT NULL ENABLE,
    "GEO_CODE"        VARCHAR2(50) NOT NULL ENABLE,
    "SRC_DESC1"       VARCHAR2(4000 BYTE) NOT NULL ENABLE,
    "SRC_DESC2"       VARCHAR2(4000 BYTE),
    "CR_ID"           VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "CR_DT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
    "UPD_ID" VARCHAR2(50 BYTE),
    "UPD_DT" TIMESTAMP,
    "ACTIVE" VARCHAR2(2 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "ACTIVATION_DT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
    "DEACTIVATION_DT" TIMESTAMP DEFAULT '31-DEC-4099 12:00:00 AM' NOT NULL ENABLE,
    CONSTRAINT CT_PK_GEO PRIMARY KEY (GEO_ID),
    CONSTRAINT CT_FK_GEO_LVL FOREIGN KEY (LEVEL_ID) REFERENCES UM_LEVEL(LEVEL_ID),
    CONSTRAINT CT_FK_GEO_ORG FOREIGN KEY (ORG_ID) REFERENCES UM_ORGANIZATION(ORG_ID),
    CONSTRAINT CT_CHK_GEO_ACTIVE CHECK (ACTIVE IN ('Y', 'N')))
	TABLESPACE HUM_TBS STORAGE ( INITIAL 50K);
ALTER TABLE UM_ADDRESS ADD CONSTRAINT CT_FK_ADDR_GEOID FOREIGN KEY (GEO_ID) REFERENCES UM_GEOGRAPHY(GEO_ID);

-- Table name : UM_MAPPING_OTHERS
CREATE TABLE "UM_MAPPING_OTHERS"
  (
    "ORG_ID"            NUMBER(8,0) NOT NULL ENABLE,
    "OTH_ID"            NUMBER(12,0) NOT NULL ENABLE,
    "SRC_SYS_ID"        NUMBER(8,0) NOT NULL ENABLE,
    "SRC_CODE"          VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "SRC_DESC1"         VARCHAR2(4000 BYTE) NOT NULL ENABLE,
    "SRC_DESC2"         VARCHAR2(4000 BYTE),
    "LEVEL_CATEGORY_ID" NUMBER(12,0) NOT NULL ENABLE,
    "LEVEL_ID"          NUMBER(12,0) NOT NULL ENABLE,
    "TARGET_DESC1"      VARCHAR2(4000 BYTE) NOT NULL ENABLE,
    "TARGET_DESC2"      VARCHAR2(4000 BYTE),
    "CR_ID"             VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "CR_DT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
    "UPD_ID" VARCHAR2(50 BYTE),
    "UPD_DT" TIMESTAMP,
    "ACTIVE" VARCHAR2(2 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "ACTIVATION_DT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
    "DEACTIVATION_DT" TIMESTAMP DEFAULT '31-DEC-4099 12:00:00 AM' NOT NULL ENABLE,
    CONSTRAINT CT_PK_MAPOTH PRIMARY KEY (OTH_ID),
    CONSTRAINT CT_FK_MAPOTH_LVL FOREIGN KEY (LEVEL_ID) REFERENCES UM_LEVEL(LEVEL_ID),
    CONSTRAINT CT_FK_MAPOTH_ORG FOREIGN KEY (ORG_ID) REFERENCES UM_ORGANIZATION(ORG_ID),
    CONSTRAINT CT_CHK_MAPOTH_ACTIVE CHECK (ACTIVE IN ('Y', 'N')))
	TABLESPACE HUM_TBS STORAGE ( INITIAL 50K);
	
-- Table name : UC_SRC_SYS  
  CREATE TABLE "UC_SRC_SYS"
  (
    "ORG_ID"        NUMBER(8,0) NOT NULL ENABLE,
    "SRC_SYS_ID"    NUMBER(8,0) NOT NULL ENABLE,
    "SRC_SYS_NAME"  VARCHAR2(100 BYTE) NOT NULL ENABLE,
    "SRC_SYS_DESC1" VARCHAR2(4000 BYTE) NOT NULL ENABLE,
    "SRC_SYS_DESC2" VARCHAR2(4000 BYTE),
    "MODULE_ID"     NUMBER(8,0) NOT NULL ENABLE,
    "MODULE_DESC1"  VARCHAR2(4000 BYTE) NOT NULL ENABLE,
    "MODULE_DESC2"  VARCHAR2(4000 BYTE),
    "SRC_ORG_CODE"  NUMBER(8,0),
    "ACTIVE"        VARCHAR2(2 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    CONSTRAINT CT_PK_SRC PRIMARY KEY (SRC_SYS_ID),
    CONSTRAINT CT_FK_SRC_ORG FOREIGN KEY (ORG_ID) REFERENCES UM_ORGANIZATION(ORG_ID),
    CONSTRAINT CT_CHK_SRC_ACTIVE CHECK (ACTIVE IN ('Y', 'N')))
	TABLESPACE HUM_TBS STORAGE ( INITIAL 50K);
ALTER TABLE UM_MAPPING_OTHERS ADD CONSTRAINT CT_FK_MAPOTH_SRCID FOREIGN KEY (SRC_SYS_ID) REFERENCES UC_SRC_SYS(SRC_SYS_ID);
ALTER TABLE UM_WORKFLOW_STAGES ADD CONSTRAINT CT_FK_WRK_SRCID FOREIGN KEY (SRC_SYS_ID) REFERENCES UC_SRC_SYS(SRC_SYS_ID);

-- Table name : HI_PROSPECT_DEMOGRAPHICS
CREATE TABLE "HI_PROSPECT_DEMOGRAPHICS"
  (
    "ORG_ID"                        NUMBER(8,0) NOT NULL ENABLE,
    "HPD_ID"                        NUMBER(8,0) NOT NULL ENABLE,
    "SRC_SYS_ID"                    NUMBER(8,0) NOT NULL ENABLE,
    "CIF_ID"                        VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "UID"                           VARCHAR2(50 BYTE),
    "CIF_NAME1"                     VARCHAR2(4000 BYTE) NOT NULL ENABLE,
    "CIF_NAME2"                     VARCHAR2(4000 BYTE),
    "EMPLOYMENT_TYPE_CODE"          VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "NET_INCOME"                    NUMBER(16,2),
    "NET_INCOME_CURRENCY_CODE"      VARCHAR2(50 BYTE),
    "NET_OTHERINCOME"               NUMBER(16,2),
    "NET_OTHERINCOME_CURRENCY_CODE" VARCHAR2(50 BYTE),
    "DOBDOI" DATE,
    "MARITAL_STATUS_CODE"      VARCHAR2(50 BYTE),
    "MARITAL_STATUS_DESC1"     VARCHAR2(4000 BYTE),
    "MARITAL_STATUS_DESC2"     VARCHAR2(4000 BYTE),
    "EDUCATION_CATEGORY_CODE"  VARCHAR2(50 BYTE),
    "EDUCATION_CATEGORY_DESC1" VARCHAR2(4000 BYTE),
    "EDUCATION_CATEGORY_DESC2" VARCHAR2(4000 BYTE),
    "ETHNICITY_CODE"           VARCHAR2(50 BYTE),
    "ETHNICITY_DESC1"          VARCHAR2(4000 BYTE),
    "ETHNICITY_DESC2"          VARCHAR2(4000 BYTE),
    "BUSS_ACTY_CODE"           VARCHAR2(50 BYTE),
    "BUSS_ACTY_DESC1"          VARCHAR2(4000 BYTE),
    "BUSS_ACTY_DESC2"          VARCHAR2(4000 BYTE),
    "SECTOR_CODE"              VARCHAR2(50 BYTE),
    "SECTOR_DESC1"             VARCHAR2(4000 BYTE),
    "SECTOR_DESC2"             VARCHAR2(4000 BYTE),
    "CUST_CATG_CODE"           VARCHAR2(50 BYTE),
    "CUST_CATG_DESC1"          VARCHAR2(4000 BYTE),
    "CUST_CATG_DESC2"          VARCHAR2(4000 BYTE),
    "INDUSTRY_CODE"            VARCHAR2(50 BYTE),
    "INDUSTRY_DESC1"           VARCHAR2(4000 BYTE),
    "INDUSTRY_DESC2"           VARCHAR2(4000 BYTE),
    "AGE_BRACKET_CODE"         VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "AGE_BRACKET_DESC1"        VARCHAR2(4000 BYTE),
    "AGE_BRACKET_DESC2"        VARCHAR2(4000 BYTE),
    "INCOME_BRACKET_CODE"      VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "INCOME_BRACKET_DESC1"     VARCHAR2(4000 BYTE),
    "INCOME_BRACKET_DESC2"     VARCHAR2(4000 BYTE),
    "BLACKLISTED"              VARCHAR2(1 BYTE) NOT NULL ENABLE,
    "BLACKLISTED_DT" DATE ,
    "DESIGNATION"                    VARCHAR2(4000 BYTE),
    "AGE"                            NUMBER(3,0),
    "NOT NULL ENABLE,_OF_DEPENDENTS" NUMBER(2,0),
    "GENDER_CODE"                    VARCHAR2(50 BYTE),
    "INDVCORPFLAG"                   VARCHAR2(4 BYTE),
    "RELATIONSHIP_SINCE" DATE NOT NULL ENABLE,
    "ADDRESS_ID"      NUMBER(8,0),
    "PROSPECT_STATUS" VARCHAR2(50 BYTE) DEFAULT 'ACTIVE',
    "FIRST_CONTACTED_DT" DATE,
    "LAST_CONTACTED_DT" DATE,
    "FF_N1"  NUMBER(16,2),
    "FF_N2"  NUMBER(16,2),
    "FF_N3"  NUMBER(16,2),
    "FF_N4"  NUMBER(16,2),
    "FF_N5"  NUMBER(16,2),
    "FF_VC1" VARCHAR2(500 BYTE),
    "FF_VC2" VARCHAR2(500 BYTE),
    "FF_VC3" VARCHAR2(500 BYTE),
    "FF_VC4" VARCHAR2(500 BYTE),
    "FF_VC5" VARCHAR2(500 BYTE),
    "FF_D1" DATE,
    "FF_D2" DATE,
    "FF_D3" DATE,
    "FF_D4" DATE,
    "FF_D5" DATE,
    "CR_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "CR_DT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
    "UPD_ID" VARCHAR2(50 BYTE),
    "UPD_DT" TIMESTAMP,
    "ACTIVE" VARCHAR2(2 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "ACTIVATION_DT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
    "DEACTIVATION_DT" TIMESTAMP DEFAULT '31-DEC-4099 12:00:00 AM' NOT NULL ENABLE,
    CONSTRAINT CT_PK_HPD_ID PRIMARY KEY (HPD_ID),
    CONSTRAINT CT_FK_HPD_ORG FOREIGN KEY (ORG_ID) REFERENCES UM_ORGANIZATION(ORG_ID),
    CONSTRAINT CT_CHK_HPD_ACTIVE CHECK (ACTIVE IN ('Y', 'N')))
	TABLESPACE HI_TBS STORAGE ( INITIAL 50K);  
COMMENT ON COLUMN "HI_PROSPECT_DEMOGRAPHICS"."SRC_SYS_ID" IS 'LO-Retail, LO-Rural etc';
COMMENT ON COLUMN "HI_PROSPECT_DEMOGRAPHICS"."UID" IS 'Unique Identification Number';
COMMENT ON COLUMN "HI_PROSPECT_DEMOGRAPHICS"."BUSS_ACTY_CODE" IS 'Code sent by Source System';
COMMENT ON COLUMN "HI_PROSPECT_DEMOGRAPHICS"."PROSPECT_STATUS" IS 'Indicates if the customer is still active or closed.';
COMMENT ON COLUMN "HI_PROSPECT_DEMOGRAPHICS"."CIF_ID" IS 'This stores PROSPECT ID as given by the source system';
COMMENT ON COLUMN "HI_PROSPECT_DEMOGRAPHICS"."ETHNICITY_DESC1" IS 'This stores description as given by Hexhibit';
COMMENT ON COLUMN "HI_PROSPECT_DEMOGRAPHICS"."ETHNICITY_DESC2" IS 'This stores description as given by Hexhibit';
COMMENT ON COLUMN "HI_PROSPECT_DEMOGRAPHICS"."MARITAL_STATUS_DESC1" IS 'This stores description as given by Hexhibit';
COMMENT ON COLUMN "HI_PROSPECT_DEMOGRAPHICS"."MARITAL_STATUS_DESC2" IS 'This stores description as given by Hexhibit';
COMMENT ON COLUMN "HI_PROSPECT_DEMOGRAPHICS"."EDUCATION_CATEGORY_DESC1" IS 'This stores description as given by Hexhibit';
COMMENT ON COLUMN "HI_PROSPECT_DEMOGRAPHICS"."EDUCATION_CATEGORY_DESC2" IS 'This stores description as given by Hexhibit';

-- Table name : HI_CUSTOMER_DEMOGRAPHICS
 CREATE TABLE "HI_CUSTOMER_DEMOGRAPHICS"
  (
    "ORG_ID"                        NUMBER(8,0) NOT NULL ENABLE,
    "HCD_ID"                        NUMBER(8,0) NOT NULL ENABLE,
    "CIF_ID"                        VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "UID"                           VARCHAR2(50 BYTE),
    "CIF_NAME1"                     VARCHAR2(4000 BYTE) NOT NULL ENABLE,
    "CIF_NAME2"                     VARCHAR2(4000 BYTE),
    "EMPLOYMENT_TYPE_CODE"          VARCHAR2(4000 BYTE) NOT NULL ENABLE,
    "NET_INCOME"                    NUMBER(16,2),
    "NET_INCOME_CURRENCY_CODE"      VARCHAR2(50 BYTE),
    "NET_OTHERINCOME"               NUMBER(16,2),
    "NET_OTHERINCOME_CURRENCY_CODE" VARCHAR2(50 BYTE),
    "DOBDOI" DATE,
    "MARITAL_STATUS_CODE"      VARCHAR2(50 BYTE),
    "MARITAL_STATUS_DESC1"     VARCHAR2(4000 BYTE),
    "MARITAL_STATUS_DESC2"     VARCHAR2(4000 BYTE),
    "EDUCATION_CATEGORY_CODE"  VARCHAR2(50 BYTE),
    "EDUCATION_CATEGORY_DESC1" VARCHAR2(4000 BYTE),
    "EDUCATION_CATEGORY_DESC2" VARCHAR2(4000 BYTE),
    "ETHNICITY_CODE"           VARCHAR2(50 BYTE),
    "ETHNICITY_DESC1"          VARCHAR2(4000 BYTE),
    "ETHNICITY_DESC2"          VARCHAR2(4000 BYTE),
    "BUSS_ACTY_CODE"           VARCHAR2(50 BYTE),
    "BUSS_ACTY_DESC1"          VARCHAR2(4000 BYTE),
    "BUSS_ACTY_DESC2"          VARCHAR2(4000 BYTE),
    "SECTOR_CODE"              VARCHAR2(50 BYTE),
    "SECTOR_DESC1"             VARCHAR2(4000 BYTE),
    "SECTOR_DESC2"             VARCHAR2(4000 BYTE),
    "CUST_CATG_CODE"           VARCHAR2(50 BYTE),
    "CUST_CATG_DESC1"          VARCHAR2(4000 BYTE),
    "CUST_CATG_DESC2"          VARCHAR2(4000 BYTE),
    "AGE_BRACKET_CODE"         VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "AGE_BRACKET_DESC1"        VARCHAR2(4000 BYTE),
    "AGE_BRACKET_DESC2"        VARCHAR2(4000 BYTE),
    "INCOME_BRACKET_CODE"      VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "INCOME_BRACKET_DESC1"     VARCHAR2(4000 BYTE),
    "INCOME_BRACKET_DESC2"     VARCHAR2(4000 BYTE),
    "INDUSTRY_CODE"            VARCHAR2(50 BYTE),
    "INDUSTRY_DESC1"           VARCHAR2(4000 BYTE),
    "INDUSTRY_DESC2"           VARCHAR2(4000 BYTE),
    "BLACKLISTED"              VARCHAR2(1 BYTE) NOT NULL ENABLE,
    "BLACKLISTED_DT" DATE ,
    "DESIGNATION"      VARCHAR2(4000 BYTE),
    "AGE"              NUMBER(3,0),
    "NO_OF_DEPENDENTS" NUMBER(2,0),
    "GENDER"           VARCHAR2(50 BYTE),
    "INDVCORPFLAG"     VARCHAR2(4 BYTE),
    "RELATIONSHIP_SINCE" DATE NOT NULL ENABLE,
    "ADDRESS_ID"              NUMBER(8,0),
    "CUSTOMER_STATUS"         VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "REASON_OF_STATUS_CHANGE" VARCHAR2(4000 BYTE),
    "STATUS_CHANGE_DT" DATE ,
    "FF_N1"  NUMBER(16,2),
    "FF_N2"  NUMBER(16,2),
    "FF_N3"  NUMBER(16,2),
    "FF_N4"  NUMBER(16,2),
    "FF_N5"  NUMBER(16,2),
    "FF_VC1" VARCHAR2(500 BYTE),
    "FF_VC2" VARCHAR2(500 BYTE),
    "FF_VC3" VARCHAR2(500 BYTE),
    "FF_VC4" VARCHAR2(500 BYTE),
    "FF_VC5" VARCHAR2(500 BYTE),
    "FF_D1" DATE,
    "FF_D2" DATE,
    "FF_D3" DATE,
    "FF_D4" DATE,
    "FF_D5" DATE,
    "CR_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "CR_DT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
    "UPD_ID" VARCHAR2(50 BYTE),
    "UPD_DT" TIMESTAMP,
    "ACTIVE" VARCHAR2(2 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "ACTIVATION_DT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
    "DEACTIVATION_DT" TIMESTAMP DEFAULT '31-DEC-4099 12:00:00 AM' NOT NULL ENABLE,
    CONSTRAINT CT_PK_HCD_ID PRIMARY KEY (HCD_ID),
    CONSTRAINT CT_FK_HCD_ORG FOREIGN KEY (ORG_ID) REFERENCES UM_ORGANIZATION(ORG_ID),
    CONSTRAINT CT_CHK_HCD_ACTIVE CHECK (ACTIVE IN ('Y', 'N')))
	TABLESPACE HI_TBS STORAGE ( INITIAL 50K);
COMMENT ON COLUMN "HI_CUSTOMER_DEMOGRAPHICS"."CIF_ID" IS 'This stores CUSTOMER IDENTIFICATION_ID as given by the source system.';
COMMENT ON COLUMN "HI_CUSTOMER_DEMOGRAPHICS"."ETHNICITY_DESC1" IS 'This stores description as given by Hexhibit';
COMMENT ON COLUMN "HI_CUSTOMER_DEMOGRAPHICS"."ETHNICITY_DESC2" IS 'This stores description as given by Hexhibit';
COMMENT ON COLUMN "HI_CUSTOMER_DEMOGRAPHICS"."MARITAL_STATUS_DESC1" IS 'This stores description as given by Hexhibit';
COMMENT ON COLUMN "HI_CUSTOMER_DEMOGRAPHICS"."MARITAL_STATUS_DESC2" IS 'This stores description as given by Hexhibit';
COMMENT ON COLUMN "HI_CUSTOMER_DEMOGRAPHICS"."EDUCATION_CATEGORY_DESC1" IS 'This stores description as given by Hexhibit';
COMMENT ON COLUMN "HI_CUSTOMER_DEMOGRAPHICS"."EDUCATION_CATEGORY_DESC2" IS 'This stores description as given by Hexhibit';
	
-- Table name : HSI_STUDENT_INFO
CREATE TABLE "HSI_STUDENT_INFO"
  (
    "ORG_ID"            NUMBER(8,0) NOT NULL ENABLE,
    "CIF_ID"            VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "HSI_ID"            NUMBER(8,0) NOT NULL ENABLE,
    "SRC_SYS_ID"        NUMBER(8,0) NOT NULL ENABLE,
    "STUDENT_TYPE_CODE" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "LOCAL_EXPAT"       VARCHAR2(50 BYTE),
    "GUARDIAN_NAME"     VARCHAR2(4000 BYTE) ,
    "RESIDENCY_CODE"    VARCHAR2(50 BYTE),
    "CR_ID"             VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "CR_DT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
    "UPD_ID" VARCHAR2(50 BYTE),
    "UPD_DT" TIMESTAMP,
    "ACTIVE" VARCHAR2(2 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "ACTIVATION_DT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
    "DEACTIVATION_DT" TIMESTAMP DEFAULT '31-DEC-4099 12:00:00 AM' NOT NULL ENABLE,
    CONSTRAINT CT_PK_HSI PRIMARY KEY (HSI_ID),
    CONSTRAINT CT_FK_HSI_ORG FOREIGN KEY (ORG_ID) REFERENCES UM_ORGANIZATION(ORG_ID),
    CONSTRAINT CT_CHK_HSI_ACTIVE CHECK (ACTIVE IN ('Y', 'N')))
	TABLESPACE HI_TBS STORAGE ( INITIAL 50K);