/*
Created By : Ram
Date : 16/07/2013
Reason: Tables script for creating the tables in the new scheme.
*/
-- DROP TABLES
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE UM_WORKFLOW_STAGES CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE UM_OFFERING CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE UM_ADDRESS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE UM_ORGANIZATION CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE UM_LEVEL CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- Table name : UM_LEVEL
CREATE TABLE "UM_LEVEL"
  (
    "ORG_ID"            NUMBER(8,0) NOT NULL ENABLE,
    "LEVEL_CATEGORY_ID" NUMBER(12,0) NOT NULL ENABLE,
	"LEVEL_ID"          NUMBER(12,0) NOT NULL ENABLE,
    "LEVEL_DESC1"       VARCHAR2(4000 BYTE) NOT NULL ENABLE,
    "LEVEL_DESC2"       VARCHAR2(4000 BYTE),   
	"LEVEL_SEQ"         NUMBER(5) DEFAULT 0 NOT NULL ENABLE,
    "LEVEL_PRED_ID"     NUMBER(12,0),    
    "CR_ID"             VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "CR_DT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
    "UPD_ID" VARCHAR2(50 BYTE),
    "UPD_DT" TIMESTAMP,
    "ACTIVE" VARCHAR2(2 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "ACTIVATION_DT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
    "DEACTIVATION_DT" TIMESTAMP DEFAULT '31-DEC-4099 12:00:00 AM' NOT NULL ENABLE,
	CONSTRAINT CT_PK_LVL PRIMARY KEY (LEVEL_ID),
	CONSTRAINT CT_CHK_LVL_ACTIVE CHECK (ACTIVE  IN ('Y', 'N')))
	TABLESPACE HUM_TBS STORAGE ( INITIAL 50K);
COMMENT ON COLUMN "UM_LEVEL"."LEVEL_SEQ" IS 'To be used wherever seq within same level is important. E.g. Balance Sheet';
COMMENT ON COLUMN "UM_LEVEL"."DEACTIVATION_DT" IS 'For active records, Hexhibit will stamp the deactivation_Dt with max date (e.g. 31-dec-4099)';
COMMENT ON COLUMN "UM_LEVEL"."LEVEL_DESC1" IS 'This field will contain description of the said level record  In cases where level_Pred_id is null (which means this is the ROOT record for that category) then this field will contain description of the Category itself.';
  
-- Table name : UM_ORGANIZATION
 
CREATE TABLE "UM_ORGANIZATION"
  (
    "ORG_ID"        NUMBER(8,0) NOT NULL ENABLE,
    "ORG_DESC1"     VARCHAR2(4000 BYTE) NOT NULL ENABLE,
    "ORG_DESC2"     VARCHAR2(4000 BYTE),
    "ADDRESS_ID"    NUMBER(8,0) NOT NULL ENABLE,
    "LEVEL_ID"      NUMBER(12,0) NOT NULL ENABLE,
    "LEVEL_PRED_ID" NUMBER(12,0),
    "FF_N1"         NUMBER(16,2),
    "FF_N2"         NUMBER(16,2),
    "FF_N3"         NUMBER(16,2),
    "FF_VC1"        VARCHAR2(500 BYTE),
    "FF_VC2"        VARCHAR2(500 BYTE),
    "FF_VC3"        VARCHAR2(500 BYTE),
    "FF_VC4"        VARCHAR2(500 BYTE),
    "FF_VC5"        VARCHAR2(500 BYTE),
    "FF_D1" DATE,
    "FF_D2" DATE,
    "FF_D3" DATE,
    "CR_ID"             VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "CR_DT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
    "UPD_ID" VARCHAR2(50 BYTE),
    "UPD_DT" TIMESTAMP,
    "ACTIVE" VARCHAR2(2 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "ACTIVATION_DT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
    "DEACTIVATION_DT" TIMESTAMP DEFAULT '31-DEC-4099 12:00:00 AM' NOT NULL ENABLE,
	CONSTRAINT CT_PK_ORG PRIMARY KEY (ORG_ID),
	CONSTRAINT CT_FK_ORG_LVL FOREIGN KEY (LEVEL_ID) REFERENCES UM_LEVEL(LEVEL_ID),
	CONSTRAINT CT_CHK_ORG_ACT CHECK (ACTIVE  IN ('Y', 'N')))
	TABLESPACE HUM_TBS STORAGE ( INITIAL 50K);
COMMENT ON COLUMN "UM_ORGANIZATION"."DEACTIVATION_DT" IS 'For active records, Hexhibit will stamp the deactivation_Dt with max date (e.g. 31-dec-4099)';
COMMENT ON COLUMN "UM_ORGANIZATION"."FF_N1" IS 'Flexi Field - Number type';
COMMENT ON COLUMN "UM_ORGANIZATION"."FF_N2" IS 'Flexi Field - Number type';
COMMENT ON COLUMN "UM_ORGANIZATION"."FF_N3" IS 'Flexi Field - Number type';
COMMENT ON COLUMN "UM_ORGANIZATION"."FF_VC1" IS 'Flexi Field - Char type';
COMMENT ON COLUMN "UM_ORGANIZATION"."FF_VC2" IS 'Flexi Field - Char type';
COMMENT ON COLUMN "UM_ORGANIZATION"."FF_VC3" IS 'Flexi Field - Char type';
COMMENT ON COLUMN "UM_ORGANIZATION"."FF_VC4" IS 'Flexi Field - Char type';
COMMENT ON COLUMN "UM_ORGANIZATION"."FF_VC5" IS 'Flexi Field - Char type';
COMMENT ON COLUMN "UM_ORGANIZATION"."FF_D1" IS 'Flexi Field - Date type';
COMMENT ON COLUMN "UM_ORGANIZATION"."FF_D2" IS 'Flexi Field - Date type';
COMMENT ON COLUMN "UM_ORGANIZATION"."FF_D3" IS 'Flexi Field - Date type';
ALTER TABLE UM_LEVEL ADD CONSTRAINT CT_FK_LVL_ORG FOREIGN KEY (ORG_ID) REFERENCES UM_ORGANIZATION(ORG_ID);
ALTER TABLE UM_ORGANIZATION DROP CONSTRAINT CT_FK_ORG_LVL;
-- Table name : UM_ADDRESS
 
CREATE TABLE "UM_ADDRESS"
  (
    "ADDRESS_ID"        NUMBER(8,0) NOT NULL ENABLE,
    "ADDRESS_1"         VARCHAR2(4000 BYTE) NOT NULL ENABLE,
    "ADDRESS_2"         VARCHAR2(4000 BYTE),
    "ADDRESS_3"         VARCHAR2(4000 BYTE),
	"ADDRESS_4"         VARCHAR2(4000 BYTE),
    "GEO_ID"            NUMBER(8,0) NOT NULL ENABLE,
    "ADDERESS_TYPE"     VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "ORG_ID"            NUMBER(8,0) NOT NULL ENABLE,   
    "CONTACT_NAME"      VARCHAR2(500 BYTE),
    "CONTACT_LANDLINE"  VARCHAR2(500 BYTE),
    "CONACT_FAX"        VARCHAR2(500 BYTE),
    "CONTACT_MOBILE1"   VARCHAR2(500 BYTE),
    "CONTACT_MOBILE2"   VARCHAR2(500 BYTE),
    "CONTACT_EMAIL_ID1" VARCHAR2(500 BYTE),
    "CONTACT_EMAIL_ID2" VARCHAR2(500 BYTE),
    "MAP_ID"            NUMBER(8,0) NOT NULL ENABLE,
    "MAP_TYPE"          VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "FF_N1"             NUMBER(16,2),
    "FF_N2"             NUMBER(16,2),
    "FF_N3"             NUMBER(16,2),
    "FF_VC1"            VARCHAR2(500 BYTE),
    "FF_VC2"            VARCHAR2(500 BYTE),
    "FF_VC3"            VARCHAR2(500 BYTE),
    "FF_VC4"            VARCHAR2(500 BYTE),
    "FF_VC5"            VARCHAR2(500 BYTE),
    "FF_D1" DATE,
    "FF_D2" DATE,
    "FF_D3" DATE,
    "CR_ID"             VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "CR_DT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
    "UPD_ID" VARCHAR2(50 BYTE),
    "UPD_DT" TIMESTAMP,
    "ACTIVE" VARCHAR2(2 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "ACTIVATION_DT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
    "DEACTIVATION_DT" TIMESTAMP DEFAULT '31-DEC-4099 12:00:00 AM' NOT NULL ENABLE,
	CONSTRAINT CT_PK_ADDR PRIMARY KEY (ADDRESS_ID),
	CONSTRAINT CT_FK_ADDR_ORG FOREIGN KEY (ORG_ID) REFERENCES UM_ORGANIZATION(ORG_ID),
    CONSTRAINT CT_CHK_ADDR_ACTIVE CHECK (ACTIVE IN ('Y', 'N')))
	TABLESPACE HUM_TBS STORAGE ( INITIAL 50K);

COMMENT ON COLUMN "UM_ADDRESS"."GEO_ID" IS 'System will figure this out';
COMMENT ON COLUMN "UM_ADDRESS"."ADDERESS_TYPE" IS 'Expected values are Residential / Property / Office / Contact . These will be derived by Hexhibit based on code provided by source system';
COMMENT ON COLUMN "UM_ADDRESS"."MAP_ID" IS 'Agent ID/Customer ID/Prospect ID / Org Id etc';
COMMENT ON COLUMN "UM_ADDRESS"."MAP_TYPE" IS 'Agency/Customer/Prospect/Organization These will be derived by Hexhibit based on code provided by source system.';
COMMENT ON COLUMN "UM_ADDRESS"."DEACTIVATION_DT" IS 'For active records, Hexhibit will stamp the deactivation_Dt with max date (e.g. 31-dec-4099)';
ALTER TABLE UM_ORGANIZATION ADD CONSTRAINT CT_FK_ADDR_ADDRID FOREIGN KEY (ADDRESS_ID) REFERENCES UM_ADDRESS(ADDRESS_ID);
  
-- Table name : UM_OFFERING

CREATE TABLE "UM_OFFERING"
  (
    "ORG_ID"          NUMBER(8,0) NOT NULL ENABLE,
    "OFFERING_ID"     NUMBER(8,0) NOT NULL ENABLE,
    "OFFERING_DESC1"  VARCHAR2(4000 BYTE) NOT NULL ENABLE,
    "OFFERING_DESC2"  VARCHAR2(4000 BYTE),
	"OFFERING_CODE"   VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "SRC_DESC1"       VARCHAR2(4000 BYTE),
    "SRC_DESC2"       VARCHAR2(4000 BYTE),
    "LEVEL_ID"        NUMBER(12,0) NOT NULL ENABLE,
    "LEVEL_PRED_ID"   NUMBER(12,0),   
    "FF_N1"           NUMBER(16,2),
    "FF_N2"           NUMBER(16,2),
    "FF_N3"           NUMBER(16,2),
    "FF_VC1"          VARCHAR2(500 BYTE),
    "FF_VC2"          VARCHAR2(500 BYTE),
    "FF_VC3"          VARCHAR2(500 BYTE),
    "FF_VC4"          VARCHAR2(500 BYTE),
    "FF_VC5"          VARCHAR2(500 BYTE),
    "FF_D1" DATE,
    "FF_D2" DATE,
    "FF_D3" DATE,
	"CR_ID"             VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "CR_DT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
    "UPD_ID" VARCHAR2(50 BYTE),
    "UPD_DT" TIMESTAMP,
    "ACTIVE" VARCHAR2(2 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "ACTIVATION_DT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
    "DEACTIVATION_DT" TIMESTAMP DEFAULT '31-DEC-4099 12:00:00 AM' NOT NULL ENABLE,
    CONSTRAINT CT_PK_OFFR PRIMARY KEY (OFFERING_ID),
	CONSTRAINT CT_FK_OFFR_LVL FOREIGN KEY (LEVEL_ID) REFERENCES UM_LEVEL(LEVEL_ID),
	CONSTRAINT CT_FK_OFFR_ORG FOREIGN KEY (ORG_ID) REFERENCES UM_ORGANIZATION(ORG_ID),
    CONSTRAINT CT_CHK_OFFR_ACTIVE CHECK (ACTIVE IN ('Y', 'N')))
	TABLESPACE HUM_TBS STORAGE ( INITIAL 50K);
COMMENT ON COLUMN "UM_OFFERING"."OFFERING_CODE" IS 'Source System Product Code';
COMMENT ON COLUMN "UM_OFFERING"."DEACTIVATION_DT" IS 'For active records, Hexhibit will stamp the deactivation_Dt with max date (e.g. 31-dec-4099)';

-- Table name : UM_WORKFLOW_STAGES

CREATE TABLE "UM_WORKFLOW_STAGES"
  (
	"ORG_ID"                NUMBER(8,0) NOT NULL ENABLE,
    "WS_ID"                 NUMBER(8,0) NOT NULL ENABLE,
    "SRC_SYS_ID"         	NUMBER(8,0) NOT NULL ENABLE,
    "WORKFLOWSTAGEID"       VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "WORKFLOWID"            VARCHAR2(50 BYTE),
    "SEQNO"                 NUMBER(8,0),
    "LEVEL_ID"              NUMBER(12,0) NOT NULL ENABLE,
    "LEVEL_PRED_ID"         NUMBER(12,0),
    "APPLSTAGE"             VARCHAR2(50 BYTE),
    "STAGE_DESC1"           VARCHAR2(4000 BYTE),
    "STAGE_DESC2"           VARCHAR2(4000 BYTE),
    "SRC_DESC1"             VARCHAR2(4000 BYTE) NOT NULL ENABLE,
    "SRC_DESC2"             VARCHAR2(4000 BYTE),
    "STAGE_CATEGORY_DESC1"  VARCHAR2(4000 BYTE) NOT NULL ENABLE,
    "STAGE_CATEGORY_DESC2"  VARCHAR2(4000 BYTE) NOT NULL ENABLE,
    "WORKFLOW_TYPE"         VARCHAR2(100 BYTE),
    "CATEGORY_SEQNO"        NUMBER(2,0),
    "STD_TAT_MINS"          NUMBER(8,0),
    "ESCALATION_ALERT_MINS" NUMBER(8,0),
    "ACTION_COST"           NUMBER(12,2),
    "First_Last_Ind"        VARCHAR2(50),
	"TIMER_IN_MINS"			NUMBER(8,0),
    "FF_N1"                 NUMBER(16,2),
    "FF_N2"                 NUMBER(16,2),
    "FF_N3"                 NUMBER(16,2),
    "FF_VC1"                VARCHAR2(500 BYTE),
    "FF_VC2"                VARCHAR2(500 BYTE),
    "FF_VC3"                VARCHAR2(500 BYTE),
    "FF_VC4"                VARCHAR2(500 BYTE),
    "FF_VC5"                VARCHAR2(500 BYTE),
    "FF_D1" DATE,
    "FF_D2" DATE,
    "FF_D3" DATE,
	"CR_ID"             VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "CR_DT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
    "UPD_ID" VARCHAR2(50 BYTE),
    "UPD_DT" TIMESTAMP,
    "ACTIVE" VARCHAR2(2 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "ACTIVATION_DT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
    "DEACTIVATION_DT" TIMESTAMP DEFAULT '31-DEC-4099 12:00:00 AM' NOT NULL ENABLE,
    CONSTRAINT CT_PK_WRK PRIMARY KEY (WS_ID),
	CONSTRAINT CT_FK_WRK_ORG FOREIGN KEY (ORG_ID) REFERENCES UM_ORGANIZATION(ORG_ID),
	CONSTRAINT CT_FK_WRK_LVL FOREIGN KEY (LEVEL_ID) REFERENCES UM_LEVEL(LEVEL_ID),
    CONSTRAINT ACTIVE_WRK_CHK CHECK (ACTIVE IN ('Y', 'N'))) 
	TABLESPACE HUM_TBS STORAGE ( INITIAL 50K);
  
COMMENT ON COLUMN "UM_WORKFLOW_STAGES"."SRC_SYS_ID" IS 'LO-Retail, LO-Rural etc';
COMMENT ON COLUMN "UM_WORKFLOW_STAGES"."WORKFLOWSTAGEID" IS 'Source System';
COMMENT ON COLUMN "UM_WORKFLOW_STAGES"."WORKFLOWID" IS 'Source System';
COMMENT ON COLUMN "UM_WORKFLOW_STAGES"."STAGE_CATEGORY_DESC1" IS 'Hexhibit Category : To be picked up from UM_MAPPING';
COMMENT ON COLUMN "UM_WORKFLOW_STAGES"."STAGE_CATEGORY_DESC2" IS 'Hexhibit Category : To be picked up from UM_MAPPING';
COMMENT ON COLUMN "UM_WORKFLOW_STAGES"."WORKFLOW_TYPE" IS 'Hexhibit stamped field (Retail / Corporate)';
COMMENT ON COLUMN "UM_WORKFLOW_STAGES"."CATEGORY_SEQNO" IS 'Hexhibit Category Sequence';
COMMENT ON COLUMN "UM_WORKFLOW_STAGES"."First_Last_Ind" IS 'Will contain either "F" (First stage) or "L" (Last Stage) or null. Note that more than one stage for the same workflow can be First/Last.There could be more than one start points or end points. Wherever this field is empty it indicates that the stage is neither first nor last!';
COMMENT ON COLUMN "UM_WORKFLOW_STAGES"."DEACTIVATION_DT" IS 'For active records, Hexhibit will stamp the deactivation_Dt with max date (e.g. 31-dec-4099)';
COMMENT ON COLUMN "UM_WORKFLOW_STAGES"."TIMER_IN_MINS" IS 'This field ill contain timer for executing system generated event. This is purely optional and does not apply to non system generated stage.';

CREATE SEQUENCE UM_PK_SEQ
  MINVALUE 1
  MAXVALUE 99999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;