
  CREATE OR REPLACE  VIEW HV_CBLO_GSEC_INCOME (VALUE_DATE, SCHEME, ACCOUNT_CODE, PLAN, SECURITY, CBLO_GSEC_AMOUNT) AS 
  SELECT ACCENT.VALUE_DATE, ACCENT.SCHEME, ACCENT.LEVEL_1 ACCOUNT_CODE, ACCENT.LEVEL_2 PLAN, ACCENT.SECURITY,
Sum(ACCENT.AMOUNT) CBLO_GSEC_AMOUNT
FROM   HI_ACCENT_CURR ACCENT 
GROUP BY ACCENT.VALUE_DATE, ACCENT.SCHEME, ACCENT.LEVEL_1, ACCENT.LEVEL_2, ACCENT.SECURITY, ACCENT.TRAN_TYPE
HAVING (ACCENT.VALUE_DATE>'01-Nov-2013') AND 
(ACCENT.LEVEL_1='611500') AND (ACCENT.LEVEL_2='26') 
AND (ACCENT.TRAN_TYPE='INTAOD') OR (ACCENT.VALUE_DATE>'01-Nov-2013')
AND (ACCENT.LEVEL_1='610401') AND (ACCENT.LEVEL_2 in ('12','16')) 
AND (ACCENT.TRAN_TYPE='SCACC')
ORDER BY ACCENT.VALUE_DATE, ACCENT.SCHEME;
 
