
  CREATE OR REPLACE  VIEW HV_FO_BROKERAGE (VALUE_DATE, SCHEME, ACCOUNT_CODE, FO_BROKERAGE) AS 
  select ACCENT.VALUE_DATE, ACCENT.SCHEME, ACCENT.LEVEL_1 ACCOUNT_CODE,  Sum(ACCENT.AMOUNT) FO_BROKERAGE
from HI_ACCENT_CURR ACCENT 
where level_1='810000' 
and value_date in (select cur_date-1 from sysparam where  rectype='L')
GROUP BY ACCENT.VALUE_DATE, ACCENT.SCHEME, ACCENT.LEVEL_1;
 
