
  CREATE OR REPLACE  VIEW HV_NET_INCOME (VALUE_DATE, SCHEME, ACCOUNT_CODE, NET_INCOME) AS 
  SELECT ACCENT.VALUE_DATE, ACCENT.SCHEME, ACCENT.LEVEL_1 ACCOUNT_CODE,  Sum(ACCENT.AMOUNT) NET_INCOME
FROM HI_ACCENT_CURR ACCENT
GROUP BY ACCENT.VALUE_DATE, ACCENT.SCHEME, ACCENT.LEVEL_1
HAVING (ACCENT.VALUE_DATE>(select cur_date -1 from sysparam where rectype='L')) 
AND (ACCENT.LEVEL_1 Like '6%') 
AND (ACCENT.SCHEME Not In ('FIP031','FIP032','FIP051','FIP052','FIP061','FMPIVG','FMPVD','FMPVIG','PRUOLD','FIP10'))
ORDER BY Sum(ACCENT.AMOUNT), ACCENT.SCHEME, ACCENT.LEVEL_1;
 
