
  CREATE OR REPLACE  VIEW HV_NET_UNREALIZED_INCOME (SCHEME, NAV_DATE, TOTAL_NET_UNREALIZED_AMOUNT) AS 
  SELECT SCHNAVBD.SCHEME, SCHNAVBD.NAV_DATE, (Sum(SCHNAVBD.NET_UNREALIZED_AMOUNT) + SUM(ACCENT.ACCENT_AMNT)) TOTAL_NET_UNREALIZED_AMOUNT
FROM (SELECT SCHNAVBD_T1.SCHEME, SCHNAVBD_T1.NAV_DATE,
SUM((SCHNAVBD_T2.NET_UNREALIZED_AMOUNT_T2 - SCHNAVBD_T1.NET_UNREALIZED_AMOUNT_T1)) NET_UNREALIZED_AMOUNT
FROM
(SELECT SCHNAVBD.SCHEME, SCHNAVBD.NAV_DATE, Sum(SCHNAVBD.GAIN_LOSS) NET_UNREALIZED_AMOUNT_T1
FROM HI_SCHNAVBD_CURR SCHNAVBD
WHERE (SCHNAVBD.NAV_DATE > (select cur_date -2 from sysparam where rectype='L')) 
AND (SCHNAVBD.SECURITY Is Not Null)
  AND SCHNAVBD.nav_method='A'
GROUP BY SCHNAVBD.SCHEME, SCHNAVBD.NAV_DATE
ORDER BY SCHNAVBD.SCHEME, SCHNAVBD.NAV_DATE ) SCHNAVBD_T1, 
 ( SELECT SCHNAVBD1.SCHEME, SCHNAVBD1.NAV_DATE, Sum(SCHNAVBD1.GAIN_LOSS) NET_UNREALIZED_AMOUNT_T2
FROM HI_SCHNAVBD_CURR SCHNAVBD1
WHERE (SCHNAVBD1.NAV_DATE > (select cur_date -3 from sysparam where rectype='L')) 
AND (SCHNAVBD1.SECURITY Is Not Null)
  AND SCHNAVBD1.nav_method='A'
GROUP BY SCHNAVBD1.SCHEME, SCHNAVBD1.NAV_DATE
ORDER BY SCHNAVBD1.SCHEME, SCHNAVBD1.NAV_DATE) SCHNAVBD_T2
WHERE SCHNAVBD_T1.SCHEME = SCHNAVBD_T2.SCHEME
GROUP BY 
SCHNAVBD_T1.SCHEME, SCHNAVBD_T1.NAV_DATE) SCHNAVBD,
(SELECT accent.VALUE_DATE, accent.SCHEME, accent.SECURITY, Sum(accent.AMOUNT) ACCENT_AMNT, accent.LEVEL_1
FROM HI_ACCENT_CURR accent
WHERE (accent.VALUE_DATE>'31-Dec-2013') AND (accent.LEVEL_1 In ('611000','611010','611110','611501','810010','810020','810011','611200','610228','610520','611100'))
GROUP BY accent.VALUE_DATE, accent.SCHEME, accent.SECURITY, accent.LEVEL_1
ORDER BY 1) ACCENT
WHERE --ACCENT.VALUE_DATE = SCHNAVBD.NAV_DATE
--AND 
accent.SCHEME  = SCHNAVBD.SCHEME
--AND (SCHNAVBD.NAV_DATE > (select cur_date -1 from sysparam where rectype='L')) 
--AND (SCHNAVBD.SECURITY Is Not Null)
 -- AND SCHNAVBD.nav_method='A'
GROUP BY SCHNAVBD.SCHEME, SCHNAVBD.NAV_DATE
ORDER BY SCHNAVBD.SCHEME, SCHNAVBD.NAV_DATE;
 
