
  CREATE OR REPLACE  VIEW HV_REGULATORY_MF_DEBT (INDUSTRY_NAME, SECURITY, ISIN_CODE, SECURITY_NAME, ASSET_NAME, SECTOR_CATEGORY, ISSUER, ISSUER_NAME, COUPON_RATE, PORTFOLIO, FACE_VALUE, TRANS_DATE, ASSET_CLASS, QTY_LOGICAL, ACQU_COST_TCY, NET_CURRENT_ASSETS, NET_ASSET_VALUE, MARKET_VALUE, MATURITY_DATE, PORTFOLIO_CATEGORY_NAME, FF_VC1, FRONTEND_RATING, MATURITY_DAYS, REGULATORY_STAMPING, SEBI_STAMPING, MCR_ASSET_TYPE, MCR_SUB_ASSET_TYPE, SECTOR_ALT, SCHEMECODE, SEBISCHEMECLASS, SEBI_SCHEME_CATEGORYY, QUANTIS_DATE) AS 
  SELECT -- 1505320
HSEC.INDUSTRY_NAME ,
HSEC.SECURITY ,
HSEC.ISIN_CODE,
HSEC.SECURITY_NAME,
HSEC.ASSET_NAME,
HSEC.SECTOR_CATEGORY,
HSEC.ISSUER,
HSEC.ISSUER_NAME,
HSEC.COUPON_RATE,
HSEC.PORTFOLIO,
HSEC.FACE_VALUE,
HSEC.TRANS_DATE,
HSEC.ASSET_CLASS,
HSEC.QTY_LOGICAL,
HSEC.ACQU_COST_TCY,
HSEC.NET_CURRENT_ASSETS,
HSEC.NET_ASSET_VALUE,
HSEC.MARKET_VALUE,
HSEC.MATURITY_DATE,
HSEC.PORTFOLIO_CATEGORY_NAME,
HSEC.FF_VC1,
--HSEC.SEBI_SCHEME_CLASS,
HSEC.FRONTEND_RATING,
HSEC.MATURITY_DAYS,
HSEC.REGULATORY_STAMPING,
HSEC.SEBI_STAMPING,
--HSEC.SEBI_SCHEME_CATEGORY,
hsec.MCR_ASSET_TYPE,
hsec.MCR_SUB_ASSET_TYPE,
HSEC.SECTOR_ALT,
hsec.SCHEMECODE,
hsec.SEBISCHEMECLASS,
hsec.SEBI_SCHEME_CATEGORYY,
HSEC.QUANTIS_DATE
from HV_REGULATORY_DEBT HSEC
UNION ALL 
-----TO BRING DUMMY ENTRIES
 select 
 NULL INDUSTRY_NAME ,
'DUMMY8' SECURITY ,
NULL ISIN_CODE,
NULL SECURITY_NAME,
NULL ASSET_NAME,
NULL SECTOR_CATEGORY,
NULL ISSUER,
NULL ISSUER_NAME,
NULL COUPON_RATE,
NULL PORTFOLIO,
NULL FACE_VALUE,
 hdim_time_cal.DAY_END_DATE TRANS_DATE,
'02' ASSET_CLASS,
NULL QTY_LOGICAL,
NULL ACQU_COST_TCY,
NULL NET_CURRENT_ASSETS,
NULL NET_ASSET_VALUE,
TO_NUMBER(0) MARKET_VALUE,
NULL MATURITY_DATE,
NULL PORTFOLIO_CATEGORY_NAME,
NULL FF_VC1,
--NULL SEBI_SCHEME_CLASS,
NULL FRONTEND_RATING,
NULL MATURITY_DAYS,
'< 90 DAYS' REGULATORY_STAMPING,
NULL SEBI_STAMPING,
--NULL SEBI_SCHEME_CATEGORY,
'Money Market Instruments (other than corporate bonds)' MCR_ASSET_TYPE,
'Commercial Paper' MCR_SUB_ASSET_TYPE,
salt1.sector SECTOR_ALT,
null SCHEMECODE,
null SEBISCHEMECLASS,
null SEBI_SCHEME_CATEGORYY,
TO_DATE('01-01-2000') quantis_date
from
 hdim_time_cal,
 HM_issuer SALT1
 where hdim_time_cal.QUARTER_END_IND='Y'
 AND SALT1.ISSUERCODE LIKE 'DUMMY%'
 AND hdim_time_cal.DAY_END_DATE <= SYSDATE
 UNION ALL 
-----TO BRING DUMMY ENTRIES
 select 
 NULL INDUSTRY_NAME ,
'DUMMY8' SECURITY ,
NULL ISIN_CODE,
NULL SECURITY_NAME,
NULL ASSET_NAME,
NULL SECTOR_CATEGORY,
NULL ISSUER,
NULL ISSUER_NAME,
NULL COUPON_RATE,
NULL PORTFOLIO,
NULL FACE_VALUE,
 hdim_time_cal.DAY_END_DATE TRANS_DATE,
'02' ASSET_CLASS,
NULL QTY_LOGICAL,
NULL ACQU_COST_TCY,
NULL NET_CURRENT_ASSETS,
NULL NET_ASSET_VALUE,
TO_NUMBER(0) MARKET_VALUE,
NULL MATURITY_DATE,
NULL PORTFOLIO_CATEGORY_NAME,
NULL FF_VC1,
--NULL SEBI_SCHEME_CLASS,
NULL FRONTEND_RATING,
NULL MATURITY_DAYS,
'< 90 DAYS' REGULATORY_STAMPING,
NULL SEBI_STAMPING,
--NULL SEBI_SCHEME_CATEGORY,
'Corporate Debt (including Floating Rate Bonds, NCDs and others)' MCR_ASSET_TYPE,
NULL MCR_SUB_ASSET_TYPE,
salt1.sector SECTOR_ALT,
null SCHEMECODE,
null SEBISCHEMECLASS,
null SEBI_SCHEME_CATEGORYY,
TO_DATE('01-01-2000') quantis_date
from
 hdim_time_cal,
 HM_issuer SALT1
 where hdim_time_cal.QUARTER_END_IND='Y'
 AND SALT1.ISSUERCODE LIKE 'DUMMY%'
 AND hdim_time_cal.DAY_END_DATE <= SYSDATE
 UNION ALL
 select 
 NULL INDUSTRY_NAME ,
'DUMMY8' SECURITY ,
NULL ISIN_CODE,
NULL SECURITY_NAME,
NULL ASSET_NAME,
NULL SECTOR_CATEGORY,
NULL ISSUER,
NULL ISSUER_NAME,
NULL COUPON_RATE,
NULL PORTFOLIO,
NULL FACE_VALUE,
 hdim_time_cal.DAY_END_DATE TRANS_DATE,
'02' ASSET_CLASS,
NULL QTY_LOGICAL,
NULL ACQU_COST_TCY,
NULL NET_CURRENT_ASSETS,
NULL NET_ASSET_VALUE,
TO_NUMBER(0) MARKET_VALUE,
NULL MATURITY_DATE,
NULL PORTFOLIO_CATEGORY_NAME,
NULL FF_VC1,
--NULL SEBI_SCHEME_CLASS,
NULL FRONTEND_RATING,
NULL MATURITY_DAYS,
'< 90 DAYS' REGULATORY_STAMPING,
NULL SEBI_STAMPING,
--NULL SEBI_SCHEME_CATEGORY,
'Securitised Debt' MCR_ASSET_TYPE,
'Single Sell Downs / Single Loan' MCR_SUB_ASSET_TYPE,
salt1.sector SECTOR_ALT,
null SCHEMECODE,
null SEBISCHEMECLASS,
null SEBI_SCHEME_CATEGORYY,
TO_DATE('01-01-2000') quantis_date
from
 hdim_time_cal,
 HM_issuer SALT1
 where hdim_time_cal.QUARTER_END_IND='Y'
 AND SALT1.ISSUERCODE LIKE 'DUMMY%'
 AND hdim_time_cal.DAY_END_DATE <= SYSDATE
 /*WHERE TRANS_DATE='31 DEC 2013'
 AND SECURITY LIKE('DUMMY%')*/;
 
