
  CREATE OR REPLACE  VIEW HV_REGULATORY_MF_EQUITY (INDUSTRY_NAME, SECURITY, ISIN_CODE, SECURITY_NAME, ASSET_NAME, SECTOR_CATEGORY, ISSUER, ISSUER_NAME, COUPON_RATE, PORTFOLIO, FACE_VALUE, TRANS_DATE, ASSET_CLASS, QTY_LOGICAL, ACQU_COST_TCY, NET_CURRENT_ASSETS, NET_ASSET_VALUE, MARKET_VALUE, MATURITY_DATE, PORTFOLIO_CATEGORY_NAME, FF_VC1, FRONTEND_RATING, MATURITY_DAYS, REGULATORY_STAMPING, SEBI_STAMPING, MCR_ASSET_TYPE, MCR_SUB_ASSET_TYPE, SECTOR_ALT, SCHEMECODE, SEBISCHEMECLASS, SEBI_SCHEME_CATEGORYY, IND1, QUANTIS_DATE) AS 
  SELECT  
HSEC.INDUSTRY_NAME ,
HSEC.SECURITY ,
HSEC.ISIN_CODE,
HSEC.SECURITY_NAME,
HSEC.ASSET_NAME,
HSEC.SECTOR_CATEGORY,
HSEC.ISSUER,
HSEC.ISSUER_NAME,
HSEC.COUPON_RATE,
HSEC.PORTFOLIO,
HSEC.FACE_VALUE,
HSEC.TRANS_DATE,
HSEC.ASSET_CLASS,
HSEC.QTY_LOGICAL,
HSEC.ACQU_COST_TCY,
HSEC.NET_CURRENT_ASSETS,
HSEC.NET_ASSET_VALUE,
HSEC.MARKET_VALUE,
HSEC.MATURITY_DATE,
HSEC.PORTFOLIO_CATEGORY_NAME,
HSEC.FF_VC1,
--HSEC.SEBI_SCHEME_CLASS,
HSEC.FRONTEND_RATING,
HSEC.MATURITY_DAYS,
HSEC.REGULATORY_STAMPING,
HSEC.SEBI_STAMPING,
--HSEC.SEBI_SCHEME_CATEGORY,
HSEC.MCR_ASSET_TYPE,
HSEC.MCR_SUB_ASSET_TYPE,
HSEC.SECTOR_ALT,
null SCHEMECODE,
null SEBISCHEMECLASS,
null SEBI_SCHEME_CATEGORYY,
SALT.AMFI Ind1,
NVL(HSEC.QUANTIS_DATE,'01-01-2000') QUANTIS_DATE
from HV_SEBI_REGULATORY_NCA HSEC,hm_issuer SALT
WHERE HSEC.issuer   =SALT.ISSUERCODE
UNION ALL 
-----TO BRING DUMMY ENTRIES
 select 
 salt1.amfi INDUSTRY_NAME ,
NULL SECURITY ,
NULL ISIN_CODE,
NULL SECURITY_NAME,
NULL ASSET_NAME,
NULL SECTOR_CATEGORY,
NULL ISSUER,
NULL ISSUER_NAME,
NULL COUPON_RATE,
NULL PORTFOLIO,
NULL FACE_VALUE,
 hdim_time_cal.DAY_END_DATE TRANS_DATE,
'01' ASSET_CLASS,
NULL QTY_LOGICAL,
NULL ACQU_COST_TCY,
NULL NET_CURRENT_ASSETS,
NULL NET_ASSET_VALUE,
TO_NUMBER(0) MARKET_VALUE,
NULL MATURITY_DATE,
NULL PORTFOLIO_CATEGORY_NAME,
NULL FF_VC1,
--NULL SEBI_SCHEME_CLASS,
NULL FRONTEND_RATING,
NULL MATURITY_DAYS,
NULL REGULATORY_STAMPING,
'Less Than 30 Days' SEBI_STAMPING,
--NULL SEBI_SCHEME_CATEGORY,
NULL MCR_ASSET_TYPE,
'DUMMY' MCR_SUB_ASSET_TYPE,
NULL SECTOR_ALT,
null SCHEMECODE,
NULL SEBISCHEMECLASS,
null SEBI_SCHEME_CATEGORYY,
salt1.amfi ind1,
 TO_DATE('01-01-2000') quantis_date
 from
 hdim_time_cal,
 HM_ISSUER SALT1
where hdim_time_cal.month_END_IND='Y'
 AND SALT1.ISSUERCODE LIKE 'DUMMY%'
 AND hdim_time_cal.DAY_END_DATE <= SYSDATE
 union all
  SELECT NULL INDUSTRY_NAME ,
  NULL SECURITY ,
  NULL ISIN_CODE,
  NULL SECURITY_NAME,
  NULL ASSET_NAME,
  NULL SECTOR_CATEGORY,
  NULL ISSUER,
  NULL ISSUER_NAME,
  NULL COUPON_RATE,
  NULL PORTFOLIO,
  NULL FACE_VALUE,
  hdim_time_cal.DAY_END_DATE TRANS_DATE,
  '01' ASSET_CLASS,
  NULL QTY_LOGICAL,
  NULL ACQU_COST_TCY,
  NULL NET_CURRENT_ASSETS,
  NULL NET_ASSET_VALUE,
  (SALT1.QTY_LOGICAL*MKT.MKT_PRICE) MARKET_VALUE,
  NULL MATURITY_DATE,
  NULL PORTFOLIO_CATEGORY_NAME,
  NULL FF_VC1,
  --NULL SEBI_SCHEME_CLASS,
  NULL FRONTEND_RATING,
  NULL MATURITY_DAYS,
  NULL REGULATORY_STAMPING,
  'Less Than 30 Days' SEBI_STAMPING,
  --NULL SEBI_SCHEME_CATEGORY,
  NULL MCR_ASSET_TYPE,
  'Derivative' MCR_SUB_ASSET_TYPE,
  NULL SECTOR_ALT,
  NULL SCHEMECODE,
  NULL SEBISCHEMECLASS,
  NULL SEBI_SCHEME_CATEGORYY,
  'Derivative' ind1,
  TO_DATE('01-01-2000') quantis_date
FROM hdim_time_cal,
  HREP_SECURITY_HOLDING_CURR SALT1,HI_MKTPRICE_CURR mkt
WHERE hdim_time_cal.month_END_IND='Y' and 
salt1.security=MKT.SECURITY
AND MODULE_REF                   ='FUTURE'
  -- AND SALT1.ISSUERCODE LIKE 'DUMMY%'
AND hdim_time_cal.DAY_END_DATE <= SYSDATE
and MKT.VALUE_DATE='08 jan 2014';
 
