
  CREATE OR REPLACE  VIEW HV_REGULATORY_DEBT (INDUSTRY_NAME, SECURITY, ISIN_CODE, SECURITY_NAME, ASSET_NAME, SECTOR_CATEGORY, ISSUER, ISSUER_NAME, COUPON_RATE, PORTFOLIO, FACE_VALUE, TRANS_DATE, ASSET_CLASS, QTY_LOGICAL, ACQU_COST_TCY, NET_CURRENT_ASSETS, NET_ASSET_VALUE, MARKET_VALUE, MATURITY_DATE, PORTFOLIO_CATEGORY_NAME, FF_VC1, FRONTEND_RATING, MATURITY_DAYS, REGULATORY_STAMPING, SEBI_STAMPING, MCR_ASSET_TYPE, MCR_SUB_ASSET_TYPE, SECTOR_ALT, SCHEMECODE, SEBISCHEMECLASS, SEBI_SCHEME_CATEGORYY, QUANTIS_DATE) AS 
  SELECT -- 1505320
HSEC.INDUSTRY_NAME ,
HSEC.SECURITY ,
HSEC.ISIN_CODE,
HSEC.SECURITY_NAME,
HSEC.ASSET_NAME,
HSEC.SECTOR_CATEGORY,
HSEC.ISSUER,
HSEC.ISSUER_NAME,
HSEC.COUPON_RATE,
HSEC.PORTFOLIO,
HSEC.FACE_VALUE,
HSEC.TRANS_DATE,
HSEC.ASSET_CLASS,
HSEC.QTY_LOGICAL,
HSEC.ACQU_COST_TCY,
HSEC.NET_CURRENT_ASSETS,
HSEC.NET_ASSET_VALUE,
HSEC.MARKET_VALUE,
HSEC.MATURITY_DATE,
HSEC.PORTFOLIO_CATEGORY_NAME,
HSEC.FF_VC1,
--HSEC.SEBI_SCHEME_CLASS,
HSEC.FRONTEND_RATING,
HSEC.MATURITY_DAYS,
HSEC.REGULATORY_STAMPING,
HSEC.SEBI_STAMPING,
--HSEC.SEBI_SCHEME_CATEGORY,
SALT.MCRASSETTYPE MCR_ASSET_TYPE,
SALT.MCRSUBASSETTYPE MCR_SUB_ASSET_TYPE,
HSEC.SECTOR_ALT,
NULL SCHEMECODE,
NULL SEBISCHEMECLASS,
NULL SEBI_SCHEME_CATEGORYY,
nvl(HSEC.QUANTIS_DATE,'01-01-2000') QUANTIS_DATE
from HV_SEBI_REGULATORY_NCA HSEC,HM_SECRATING_MASTER SALT
WHERE HSEC.SECURITY   =SALT.SECURITY_CODE(+)
UNION ALL 
-----TO BRING DUMMY ENTRIES
 select 
 NULL INDUSTRY_NAME ,
SALT1.SECURITY_CODE SECURITY ,
NULL ISIN_CODE,
NULL SECURITY_NAME,
NULL ASSET_NAME,
NULL SECTOR_CATEGORY,
NULL ISSUER,
NULL ISSUER_NAME,
NULL COUPON_RATE,
NULL PORTFOLIO,
NULL FACE_VALUE,
 hdim_time_cal.DAY_END_DATE TRANS_DATE,
'02' ASSET_CLASS,
NULL QTY_LOGICAL,
NULL ACQU_COST_TCY,
NULL NET_CURRENT_ASSETS,
NULL NET_ASSET_VALUE,
TO_NUMBER(0) MARKET_VALUE,
NULL MATURITY_DATE,
NULL PORTFOLIO_CATEGORY_NAME,
NULL FF_VC1,
--NULL SEBI_SCHEME_CLASS,
NULL FRONTEND_RATING,
NULL MATURITY_DAYS,
'< 90 DAYS' REGULATORY_STAMPING,
NULL SEBI_STAMPING,
--NULL SEBI_SCHEME_CATEGORY,
SALT1.MCRASSETTYPE MCR_ASSET_TYPE,
SALT1.MCRSUBASSETTYPE MCR_SUB_ASSET_TYPE,
NULL SECTOR_ALT,
null SCHEMECODE,
null SEBISCHEMECLASS,
null SEBI_SCHEME_CATEGORYY,
TO_DATE('01-01-2000') quantis_date
from
 hdim_time_cal,
 HM_SECRATING_MASTER SALT1
 where hdim_time_cal.QUARTER_END_IND='Y'
 AND SALT1.SECURITY_CODE LIKE 'DUMMY%'
 AND hdim_time_cal.DAY_END_DATE <= SYSDATE;
 
