
  CREATE OR REPLACE  VIEW HV_SEBI_REG_NCA (INDUSTRY_NAME, SECURITY, ISIN_CODE, SECURITY_NAME, ASSET_NAME, SECTOR_CATEGORY, ISSUER, ISSUER_NAME, COUPON_RATE, PORTFOLIO, FACE_VALUE, TRANS_DATE, ASSET_CLASS, QTY_LOGICAL, ACQU_COST_TCY, NET_CURRENT_ASSETS, NET_ASSET_VALUE, MARKET_VALUE, MATURITY_DATE, PORTFOLIO_CATEGORY_NAME, FF_VC1, FRONTEND_RATING, MATURITY_DAYS, REGULATORY_STAMPING, SEBI_STAMPING, MCR_ASSET_TYPE, MCR_SUB_ASSET_TYPE, SECTOR_ALT, SCHEMECODE, SEBISCHEMECLASS, SEBI_SCHEME_CATEGORYY, QUANTIS_DATE) AS 
  SELECT  
HSEC.INDUSTRY_NAME ,
HSEC.SECURITY ,
HSEC.ISIN_CODE,
HSEC.SECURITY_NAME,
HSEC.ASSET_NAME,
HSEC.SECTOR_CATEGORY,
HSEC.ISSUER,
HSEC.ISSUER_NAME,
HSEC.COUPON_RATE,
HSEC.PORTFOLIO,
HSEC.FACE_VALUE,
HSEC.TRANS_DATE,
HSEC.ASSET_CLASS,
HSEC.QTY_LOGICAL,
HSEC.ACQU_COST_TCY,
HSEC.NET_CURRENT_ASSETS,
HSEC.NET_ASSET_VALUE,
HSEC.MARKET_VALUE,
HSEC.MATURITY_DATE,
HSEC.PORTFOLIO_CATEGORY_NAME,
HSEC.FF_VC1,
--HSEC.SEBI_SCHEME_CLASS,
HSEC.FRONTEND_RATING,
HSEC.MATURITY_DAYS,
HSEC.REGULATORY_STAMPING,
HSEC.SEBI_STAMPING,
--HSEC.SEBI_SCHEME_CATEGORY,
HSEC.MCR_ASSET_TYPE,
HSEC.MCR_SUB_ASSET_TYPE,
HSEC.SECTOR_ALT,
SALT.SCHEMECODE SCHEMECODE,
SALT.SEBISCHEMECLASS SEBISCHEMECLASS,
SALT.FF_VC1 SEBI_SCHEME_CATEGORYY,
nvl(HSEC.QUANTIS_DATE,'01-01-2000') QUANTIS_DATE
from HV_SEBI_REGULATORY_NCA HSEC,HM_SCHEME_ALT SALT
WHERE HSEC.PORTFOLIO   =SALT.SCHEMECODE
UNION ALL 
-----TO BRING DUMMY ENTRIES
 select 
 NULL INDUSTRY_NAME ,
NULL SECURITY ,
NULL ISIN_CODE,
NULL SECURITY_NAME,
NULL ASSET_NAME,
NULL SECTOR_CATEGORY,
NULL ISSUER,
NULL ISSUER_NAME,
NULL COUPON_RATE,
NULL PORTFOLIO,
NULL FACE_VALUE,
 hdim_time_cal.DAY_END_DATE TRANS_DATE,
NULL ASSET_CLASS,
NULL QTY_LOGICAL,
NULL ACQU_COST_TCY,
NULL NET_CURRENT_ASSETS,
NULL NET_ASSET_VALUE,
TO_NUMBER(0) MARKET_VALUE,
NULL MATURITY_DATE,
NULL PORTFOLIO_CATEGORY_NAME,
NULL FF_VC1,
--NULL SEBI_SCHEME_CLASS,
NULL FRONTEND_RATING,
NULL MATURITY_DAYS,
NULL REGULATORY_STAMPING,
'Less Than 30 Days' SEBI_STAMPING,
--NULL SEBI_SCHEME_CATEGORY,
NULL MCR_ASSET_TYPE,
NULL MCR_SUB_ASSET_TYPE,
NULL SECTOR_ALT,
SALT1.SCHEMECODE SCHEMECODE,
SALT1.SEBISCHEMECLASS SEBISCHEMECLASS,
SALT1.ff_vc1 SEBI_SCHEME_CATEGORYY,
TO_DATE('01-01-2000') quantis_date
from
 hdim_time_cal,
 HM_SCHEME_ALT SALT1
 where hdim_time_cal.QUARTER_END_IND='Y'
 AND SALT1.SCHEMECODE LIKE 'DUMMY%'
 AND hdim_time_cal.DAY_END_DATE <= SYSDATE;
 
