
  CREATE OR REPLACE  VIEW HV_TOTAL_MTM (NSE_CODE, SCHEME, INDXFUTURE, UNITS, AVG_PRICE, MARKET_VALUE, LIABILITY_COST, MTM_PRICE, EXPIRY_DATE, CODE_EXPIRY, SCH_INDX, MAT_DATE, MKT_PRICE, VALUE_DATE, MTM_PREV, SECURITY) AS 
  SELECT SUBSTR (SECURITY.STK_SEC_ID,3) NSE_CODE,
    FUTUREPOSITIONS.SCHEME,
    FUTUREPOSITIONS.INDXFUTURE,
    FUTUREPOSITIONS.UNITS,
    FUTUREPOSITIONS.AVG_PRICE,
    FUTUREPOSITIONS.MARKET_VALUE,
    FUTUREPOSITIONS.LIABILITY_COST,
   -- ((FUTUREPOSITIONS.MARKET_VALUE+FUTUREPOSITIONS.LIABILITY_COST)/UNITS)MTM_PRICE,
   DECODE(UNITS,0,0,(FUTUREPOSITIONS.MARKET_VALUE+FUTUREPOSITIONS.LIABILITY_COST) / UNITS)MTM_PRICE,
    (INDXFUTURE.MAT_DATE) EXPIRY_DATE,
    (SUBSTR (SECURITY.STK_SEC_ID,3)
    ||''
    || TO_CHAR((INDXFUTURE.MAT_DATE - TO_DATE('01-JAN-1900'))+2))CODE_EXPIRY,
    (FUTUREPOSITIONS.SCHEME
    ||''
    ||FUTUREPOSITIONS.INDXFUTURE)SCH_INDX,
    INDXFUTURE.MAT_DATE ,
    MKTPRICE.MKT_PRICE,
    MKTPRICE.VALUE_DATE,
    LAG(MKTPRICE.MKT_PRICE, 1, 0) OVER (ORDER BY MKTPRICE.SECURITY, MKTPRICE.VALUE_DATE) AS MTM_PREV,
    MKTPRICE.SECURITY
  FROM HI_FUTUREPOSITIONS_CURR FUTUREPOSITIONS,
    HI_MKTPRICE_CURR MKTPRICE,
    HI_INDXFUTURE_CURR INDXFUTURE,
    HM_SECURITY SECURITY
  WHERE SECURITY.SECURITY        = INDXFUTURE.UNDERLYING_CODE
  AND SECURITY.RECTYPE           = 'L'
  AND FUTUREPOSITIONS.INDXFUTURE = INDXFUTURE.INDXFUTURE
  AND FUTUREPOSITIONS.SCHEME     ='HDFCAR'
  AND FUTUREPOSITIONS.INDXFUTURE = MKTPRICE.SECURITY
  AND INDXFUTURE.RECTYPE         = 'L'
  --AND INDXFUTURE.MAT_DATE        > '01 JAN 2013' Removed to get the all the matured values 
    --AND MKTPRICE.VALUE_DATE = '23 Oct 2013' commented to test the output
  ORDER BY MKTPRICE.SECURITY,
    MKTPRICE.VALUE_DATE;
 
