
  CREATE OR REPLACE  VIEW HVM_ISSUER (ISSUER, RECTYPE, CURRNO, EQUITY_CAP, TOTAL_DEBT, MKTCAP_LK, YEAR_END_START, YEAR_END, NAME, MNEMONIC, INDUSTRY, MGMT_GROUP, NETWORTH_NEGATIVE_YN, ADDRESS_1, ADDRESS_2, ADDRESS_3, CONTACT, TEL_NO, FAX_NO, RADDRESS_1, RADDRESS_2, RADDRESS_3, STATE, EQU_LAST_DIV_DT, EQU_DIV_RATE, BIFR_REF_DATE, BIFR_REF, PREVIOUS_NAME, SECTOR, PHYSICAL_FILE, PINCODE, RPINCODE, COUNTRY, CURRENCY, PAR_VALUE_YN, EMAIL_ID, ACTIVATE_Y_N, RELATED_YN, PREFER_CAP, RESERVES, ISSUER_TYPE, AIFI_Y_N, STATUS, INPUTTER, INP_DT_TM, AUTHORISER, PKID, ISSUERCODE, ISSUERNAME, RATINGAGENCY, RATING, TYPE, TRUSTNAME, OBLIGORORIGINATOR, ORIGINATORSELLER, AMFI, SPONSOR) AS 
  SELECT issuer,
  RECTYPE,
  currno,
  EQUITY_CAP,
  total_debt,
  mktcap_lk,
  YEAR_END_START,
  year_end,
  name,
  mnemonic,
  industry,
  mgmt_group,
  networth_negative_yn,
  address_1,
  address_2,
  address_3,
  CONTACT,
  tel_no,
  fax_no,
  raddress_1,
  RADDRESS_2,
  raddress_3,
  state,
  equ_last_div_dt,
  equ_div_rate,
  BIFR_REF_DATE,
  bifr_ref,
  previous_name,
  i.sector,
  physical_file,
  pincode,
  RPINCODE,
  country,
  currency,
  PAR_VALUE_YN,
  email_id,
  ACTIVATE_Y_N,
  related_yn,
  prefer_cap,
  reserves,
  ISSUER_TYPE,
  aifi_y_n,
  status,
  INPUTTER,
  inp_dt_tm,
  authoriser,
  pkid,
  ISSUERCODE,
  issuername,
  RATINGAGENCY,
  rating,
  type,
  trustname,
  obligororiginator,
  ORIGINATORSELLER,
  AMFI,
  SPONSOR
FROM issuer i,
  isuer_reflex is_ref
WHERE i.issuer = is_ref.issuercode;
 
