
  CREATE OR REPLACE  VIEW HVM_SCHEME (AMC_CODE, SCHEME, SCHEME_NAME, SCHEME_TYPE, SCHEMECATEGORY, SCHEMETYPE, SCHEMETYPETWO, SEBISCHEMECLASS, FF_VC1, DESC1, DESC2, DESC3, SALE_LOAD, PUR_LOAD, DISTRIBUTABLE_INC_ACCT, PRFT_LOSS_ACCT, UNIT_RESERVE, UNIT_CAPAC, RECTYPE, CURRNO, SCH_NUMBER, UNITS, FACE_VALUE, CAPITAL, ISSUE_VAL, PURCH_VAL, NAV, START_DATE, END_DATE, PREV_DATE, CUR_DATE, NEXT_DATE, PRV_NAV_DT, NXT_NAV_DT, ACTIVATE_Y_N, PORT_TYPE, CURRENCY, RELATED_Y_N, PRV_YREND, STATUS, INP_DT_TM, FF_N1, FF_N2, FF_N3, FF_VC2, FF_VC3, FF_VC4, FF_VC5, FF_D1, FF_D2, FF_D3, CR_ID, CR_DT, UPD_ID, UPD_DT, ACTIVE, ACTIVATION_DT, DEACTIVATION_DT) AS 
  SELECT hs.amc_code,
  hs.scheme,
  hs.scheme_name,
  hs.scheme_type,
  hsa.schemecategory,
  hsa.schemetype,
  hsa.schemetypetwo,
  hsa.sebischemeclass,
  hsa.ff_vc1,
  hs.desc1,
  hs.desc2,
  hs.desc3,
  hs.sale_load,
  hs.pur_load,
  hs.distributable_inc_acct,
  hs.prft_loss_acct,
  hs.unit_reserve,
  hs.unit_capac,
  hs.rectype,
  hs.currno,
  hs.sch_number,
  hs.units,
  hs.face_value,
  hs.capital,
  hs.issue_val,
  hs.purch_val,
  hs.nav,
  hs.start_date,
  hs.end_date,
  hs.prev_date,
  hs.cur_date,
  hs.next_date,
  hs.prv_nav_dt,
  hs.nxt_nav_dt,
  hs.activate_y_n,
  hs.port_type,
  hs.currency,
  hs.related_y_n,
  hs.prv_yrend,
  hs.status,
  hs.inp_dt_tm,
  hs.ff_n1,
  hs.ff_n2,
  hs.ff_n3,
  hs.ff_vc2,
  hs.ff_vc3,
  hs.ff_vc4,
  hs.ff_vc5,
  hs.ff_d1,
  hs.ff_d2,
  hs.ff_d3,
  hs.cr_id,
  hs.cr_dt,
  hs.upd_id,
  hs.upd_dt,
  hs.active,
  hs.activation_dt,
  hs.DEACTIVATION_DT
FROM hm_scheme hs,
  hm_scheme_alt hsa
WHERE hs.scheme = hsa.schemecode;
 
